export interface CharacterModel {
  id: string;
  name: string;
  category: "cartoon" | "realistic";
  subcategory?: string;
  emoji: string;
  description: string;
  path: string;
  thumbnailPath?: string;
  pose?: "T-Pose" | "A-Pose";
  available: boolean;
  tags: string[];
}

export const MODELS: CharacterModel[] = [
  // ── Cartoon / Pop-Culture ────────────────────────────────────────────────
  {
    id: "spiderman",
    name: "Spider-Man",
    category: "cartoon",
    subcategory: "Superhéroe",
    emoji: "🕷️",
    description: "Peter Parker en traje de Spider-Man, pose heroica de A-Pose para rigging.",
    path: "/assets/3d/models/spiderman.glb",
    thumbnailPath: "/assets/3d/models/spiderman.txt",
    pose: "A-Pose",
    available: false,
    tags: ["marvel", "superhero", "action", "iconic"],
  },
  {
    id: "bob_esponja",
    name: "Bob Esponja",
    category: "cartoon",
    subcategory: "Animación",
    emoji: "🧽",
    description: "Bob Esponja cuadrado y alegre, listo para animaciones expresivas.",
    path: "/assets/3d/models/bob_esponja.glb",
    thumbnailPath: "/assets/3d/models/bob_esponja.txt",
    pose: "T-Pose",
    available: false,
    tags: ["nickelodeon", "cartoon", "fun", "expressive"],
  },
  {
    id: "mickey_mouse",
    name: "Mickey Mouse",
    category: "cartoon",
    subcategory: "Disney",
    emoji: "🐭",
    description: "Mickey Mouse clásico con guantes blancos y pantalón rojo.",
    path: "/assets/3d/models/mickey_mouse.glb",
    thumbnailPath: "/assets/3d/models/mickey_mouse.txt",
    pose: "A-Pose",
    available: false,
    tags: ["disney", "classic", "iconic", "family"],
  },
  {
    id: "payaso_plim_plim",
    name: "Payaso Plim Plim",
    category: "cartoon",
    subcategory: "Animación Latinoamericana",
    emoji: "🤡",
    description: "Plim Plim el payaso mágico, colorido y perfecto para contenido infantil.",
    path: "/assets/3d/models/payaso_plim_plim.glb",
    thumbnailPath: "/assets/3d/models/payaso_plim_plim.txt",
    pose: "A-Pose",
    available: false,
    tags: ["latin", "clown", "kids", "colorful"],
  },
  {
    id: "minnie_mouse",
    name: "Minnie Mouse",
    category: "cartoon",
    subcategory: "Disney",
    emoji: "🎀",
    description: "Minnie Mouse con lunares y lazo rojo característico.",
    path: "/assets/3d/models/minnie_mouse.glb",
    thumbnailPath: "/assets/3d/models/minnie_mouse.txt",
    pose: "A-Pose",
    available: false,
    tags: ["disney", "classic", "feminine", "iconic"],
  },
  {
    id: "alec_monopoly",
    name: "Alec Monopoly",
    category: "cartoon",
    subcategory: "Arte Urbano",
    emoji: "🎩",
    description: "El personaje de Alec Monopoly con sombrero de copa y traje del magnate.",
    path: "/assets/3d/models/alec_monopoly.glb",
    thumbnailPath: "/assets/3d/models/alec_monopoly.txt",
    pose: "T-Pose",
    available: false,
    tags: ["streetart", "luxury", "monopoly", "urban"],
  },
  {
    id: "batman",
    name: "Batman",
    category: "cartoon",
    subcategory: "Superhéroe",
    emoji: "🦇",
    description: "Batman con capa y traje negro oscuro, pose de A-Pose heroica.",
    path: "/assets/3d/models/batman.glb",
    thumbnailPath: "/assets/3d/models/batman.txt",
    pose: "A-Pose",
    available: false,
    tags: ["dc", "superhero", "dark", "iconic"],
  },
  {
    id: "bugs_bunny",
    name: "Bugs Bunny",
    category: "cartoon",
    subcategory: "Looney Tunes",
    emoji: "🐰",
    description: "Bugs Bunny con su zanahoria, pose relajada y expresiva.",
    path: "/assets/3d/models/bugs_bunny.glb",
    thumbnailPath: "/assets/3d/models/bugs_bunny.txt",
    pose: "T-Pose",
    available: false,
    tags: ["looney-tunes", "classic", "comedic", "wb"],
  },
  {
    id: "ted",
    name: "TED (Oso)",
    category: "cartoon",
    subcategory: "Película",
    emoji: "🐻",
    description: "TED el oso de peluche de la película, con cara expresiva adulta.",
    path: "/assets/3d/models/ted.glb",
    thumbnailPath: "/assets/3d/models/ted.txt",
    pose: "T-Pose",
    available: false,
    tags: ["movie", "bear", "adult-humor", "plush"],
  },
  {
    id: "pikachu",
    name: "Pikachu",
    category: "cartoon",
    subcategory: "Pokémon",
    emoji: "⚡",
    description: "Pikachu listo para el combate en A-Pose, con orejas negras.",
    path: "/assets/3d/models/pikachu.glb",
    thumbnailPath: "/assets/3d/models/pikachu.txt",
    pose: "A-Pose",
    available: false,
    tags: ["pokemon", "nintendo", "cute", "iconic"],
  },

  // ── Realista Humanoide ───────────────────────────────────────────────────
  {
    id: "chica_ejecutiva",
    name: "Mujer Ejecutiva",
    category: "realistic",
    subcategory: "Profesional",
    emoji: "👩‍💼",
    description: "Mujer de negocios moderna, traje formal, pelo recogido. Perfecta para landing pages corporativas.",
    path: "/assets/3d/models/chica_ejecutiva.glb",
    thumbnailPath: "/assets/3d/models/chica_ejecutiva.txt",
    pose: "A-Pose",
    available: false,
    tags: ["female", "corporate", "modern", "professional"],
  },
  {
    id: "chico_casual",
    name: "Hombre Casual Tech",
    category: "realistic",
    subcategory: "Casual",
    emoji: "👨‍💻",
    description: "Hombre joven con hoodie y jeans, estilo Silicon Valley. Ideal para startups y apps.",
    path: "/assets/3d/models/chico_casual.glb",
    thumbnailPath: "/assets/3d/models/chico_casual.txt",
    pose: "A-Pose",
    available: false,
    tags: ["male", "tech", "casual", "startup"],
  },
  {
    id: "chica_creativa",
    name: "Mujer Creativa Agencia",
    category: "realistic",
    subcategory: "Creativo",
    emoji: "👩‍🎨",
    description: "Mujer creativa con estilo agencia, ropa colorida y actitud dinámica.",
    path: "/assets/3d/models/chica_creativa.glb",
    thumbnailPath: "/assets/3d/models/chica_creativa.txt",
    pose: "A-Pose",
    available: false,
    tags: ["female", "creative", "agency", "dynamic"],
  },
  {
    id: "chico_formal",
    name: "Hombre Traje Formal",
    category: "realistic",
    subcategory: "Formal",
    emoji: "🤵",
    description: "Hombre con traje completo y corbata, aspecto ejecutivo clásico. Ideal para sector financiero.",
    path: "/assets/3d/models/chico_formal.glb",
    thumbnailPath: "/assets/3d/models/chico_formal.txt",
    pose: "A-Pose",
    available: false,
    tags: ["male", "formal", "executive", "finance"],
  },
];

export const MODELS_BY_CATEGORY = {
  cartoon: MODELS.filter((m) => m.category === "cartoon"),
  realistic: MODELS.filter((m) => m.category === "realistic"),
};

export function getModelById(id: string): CharacterModel | undefined {
  return MODELS.find((m) => m.id === id);
}
