export const DEFAULT_CMS_CONTENT = {
  meta: {
    lastUpdated: new Date().toISOString(),
    updatedBy: "system",
    version: 1,
  },
  sectionOrder: ["site", "backgrounds", "nav", "hero", "features", "stats", "how", "results", "pricing", "calculator", "contact", "howCards", "sectionNav", "apkLabels", "errorMessages", "heroDemoTitles", "adminPanel", "clientPanel", "adminNav", "labels", "footer"],
  backgrounds: {
    hero: { type: "particles", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
    features: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#2dd49f" },
    pricing: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
    how: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
    results: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#2dd49f" },
    calculator: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
    contact: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
  },
  site: {
    name: "Shopy Crafter",
    tagline: "Optimización IA para tu tienda Shopify",
    logo: { type: "image", value: "SC", imageUrl: "/images/logo-sc-default.png" },
    favicon: "/favicon.png",
    primaryColor: "#c8a84b",
    accentColor: "#2dd49f",
    font_heading: "Instrument Serif",
    font_body: "Geist",
  },
  nav: {
    links: [
      { id: "nav-1", label: "Motores", href: "#features" },
      { id: "nav-2", label: "Cómo funciona", href: "#how" },
      { id: "nav-3", label: "Precios", href: "#pricing" },
      { id: "nav-4", label: "Clientes", href: "#testimonials" },
    ],
    ctaPrimary: { label: "Solicitar acceso →", href: "#cta" },
    ctaSecondary: { label: "Iniciar sesión", href: "/login" },
  },
  hero: {
    pill: { text: "Nuevo · 6 motores de IA activos · Versión 2.0", visible: true },
    headline: "Optimizamos tu tienda\nShopify con IA\n24/7 por ti",
    headlineHighlight: "24/7",
    subheadline: "Shopy Crafter gestiona, optimiza y potencia tiendas Shopify de manera completamente autónoma. Imágenes profesionales, pricing inteligente, SEO técnico y tests A/B — todo en piloto automático. Un solo cerebro para toda tu agencia.",
    ctaPrimary: { label: "Empezar gratis 14 días →", href: "#cta" },
    ctaSecondary: { label: "▶ Ver en acción", href: "#how" },
    ctaApk: { label: "📱 Descargar App Android", href: "#" },
    trustItems: ["Sin tarjeta de crédito", "Setup en 5 minutos", "Cancela cuando quieras", "RGPD compliant"],
    scrollHint: "Desliza para explorar",
    imageUrl: null as string | null,
    demo: {
      url: "app.shopifyai.pro/admin — Moda Urbana",
      status: "6 motores activos",
      navItems: ["Overview", "Productos", "Imágenes IA", "Pricing + P&L", "SEO Técnico", "A/B Tests"],
      metrics: [
        { label: "Revenue", value: "€32.4K", change: "↑ 22%" },
        { label: "Conversión", value: "4.2%", change: "↑ 0.9pp" },
        { label: "Margen", value: "61%", change: "↑ 8pts" },
        { label: "SEO", value: "88", change: "↑ 23pts" },
      ],
      stores: [
        { name: "Moda Urbana", score: "88" },
        { name: "TechGadgets", score: "71" },
        { name: "Casa & Arte", score: "42" },
      ],
      activity: [
        "A/B Test ganador · +28% conv.",
        "48 imágenes · €13.44",
        "Schema SEO · 234 productos",
      ],
    },
  },
  features: {
    pill: "Motores IA",
    headline: "Seis motores. Una sola plataforma.",
    subheadline: "Cada motor trabaja de forma autónoma y coordinada para potenciar todos los aspectos de tu tienda.",
    items: [
      { id: "feat-1", num: "M01", icon: "🖼️", iconBg: "rgba(45,212,159,0.1)", title: "Generación de Imágenes", description: "8 tipos de imagen profesional por producto usando Replicate flux-1.1-pro. Hero, Lifestyle, Detalle, Packaging, UGC, Escala, Bundle e Infografía SVG generada directamente.", tags: ["flux-1.1-pro", "recraft-v3", "~€0.25/prod"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "94%" }, { label: "Velocidad", value: "<2s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-2", num: "M02", icon: "🎨", iconBg: "rgba(200,168,75,0.1)", title: "Consistencia Visual", description: "Extrae el ADN visual de tu tienda y aplica StyleLock a todas las generaciones. Garantiza coherencia de marca en cada imagen, colección y set fotográfico.", tags: ["StyleLock", "Visual DNA", "Set Mode"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "97%" }, { label: "Velocidad", value: "<3s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-3", num: "M03", icon: "⚗️", iconBg: "rgba(74,158,221,0.1)", title: "A/B Testing Automático", description: "Pixel tracker propio, z-test estadístico al 95% de confianza, declaración automática de ganador y generación inmediata del siguiente challenger.", tags: ["Z-test 95%", "Pixel tracker", "Auto-winner"], imageUrl: null as string | null, stats: [{ label: "Confianza", value: "95%" }, { label: "Velocidad", value: "<1s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-4", num: "M04", icon: "⚡", iconBg: "rgba(200,168,75,0.08)", title: "Auto-Pilot 24/7", description: "Webhook trigger en cada nuevo producto. Auditoría inmediata, generación automática de Hero y Lifestyle, test A/B creado y activo sin intervención manual.", tags: ["Webhook", "Cron jobs", "Informe mensual"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "99%" }, { label: "Velocidad", value: "<5s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-5", num: "M05", icon: "📊", iconBg: "rgba(200,168,75,0.1)", title: "Pricing Financiero", description: "Motor COGS completo, análisis de competencia en tiempo real, economista IA con pricing psicológico, dashboard P&L y alertas de margen.", tags: ["COGS Engine", "Competencia", "P&L en vivo"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "92%" }, { label: "Velocidad", value: "<2s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-6", num: "M06", icon: "🔍", iconBg: "rgba(45,212,159,0.08)", title: "SEO Técnico", description: "Schema JSON-LD completo, meta tags optimizados por Claude, sitemap dinámico, Core Web Vitals, estrategia de keywords y generación automática de blog posts.", tags: ["Schema JSON-LD", "CWV", "Blog IA"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "96%" }, { label: "Velocidad", value: "<4s" }, { label: "Uptime", value: "99.9%" }] },
    ],
  },
  stats: [
    { id: "s1", num: "3.4×", label: "Más conversión con 5+ imágenes" },
    { id: "s2", num: "€0.25", label: "Coste por producto optimizado" },
    { id: "s3", num: "95%", label: "Confianza estadística en A/B tests" },
    { id: "s4", num: "24/7", label: "Auto-pilot completamente autónomo" },
  ],
  how: {
    pill: "Cómo funciona",
    headline: "De zero a tienda optimizada\nen minutos",
    headlineHighlight: "tienda optimizada",
    steps: [
      { num: "01", title: "Conecta tu tienda Shopify", desc: "Introduce tu dominio y Access Token. La plataforma se conecta al instante con la API de Shopify y escanea todo tu catálogo, configuración y métricas actuales." },
      { num: "02", title: "La IA audita cada producto", desc: "Claude analiza título, descripción, precio, imágenes y SEO de cada producto. Asigna una nota A–F y genera una lista priorizada de mejoras con impacto estimado en revenue." },
      { num: "03", title: "Activa los 6 motores", desc: "Con un clic, los 6 motores se ponen en marcha: generan imágenes, optimizan precios, aplican SEO técnico, inician tests A/B y configuran automatizaciones." },
      { num: "04", title: "Resultados compuestos cada semana", desc: "El sistema mejora solo. Cada test que termina genera el siguiente. Cada precio optimizado se monitoriza. Cada imagen que convierte se convierte en el nuevo estándar." },
    ],
  },
  pricing: {
    pill: "Precios",
    headline: "Transparente. Sin sorpresas.",
    subheadline: "Retainer mensual + setup único. Sin permanencia. Cancela cuando quieras.",
    plans: [
      {
        id: "plan-emprendedor", name: "Emprendedor", price: "19", currency: "€", period: "por mes · sin setup",
        featured: false, badge: "NUEVO",
        features: [
          { text: "Optimización de hasta 5 productos/mes con IA", included: true },
          { text: "Generación de 10 imágenes de producto con IA", included: true },
          { text: "Auditoría SEO básica con recomendaciones", included: true },
          { text: "Análisis de precios y márgenes (COGS)", included: true },
          { text: "Dashboard de métricas esencial", included: true },
          { text: "Soporte por email (respuesta <48h)", included: true },
          { text: "A/B testing", included: false },
          { text: "Auto-pilot", included: false },
          { text: "Imágenes ilimitadas", included: false },
        ],
        cta: { label: "Empezar por €19/mes →", href: "#fp-contact", style: "ghost" },
      },
      {
        id: "plan-pro", name: "Pro", price: "89", currency: "€", period: "por mes · sin setup",
        featured: false, badge: "POPULAR",
        features: [
          { text: "Optimización de hasta 20 productos/mes con IA", included: true },
          { text: "Generación de 50 imágenes de producto con IA", included: true },
          { text: "Auditoría SEO completa con implementación automática", included: true },
          { text: "Motor de pricing financiero (COGS + márgenes + competencia)", included: true },
          { text: "A/B testing visual en 2 productos simultáneos", included: true },
          { text: "Dashboard de analytics con métricas de conversión", included: true },
          { text: "Informe mensual de rendimiento con recomendaciones IA", included: true },
          { text: "Soporte por email y chat (respuesta <24h)", included: true },
          { text: "Auto-pilot", included: false },
          { text: "Imágenes ilimitadas", included: false },
          { text: "Custom AI model training", included: false },
        ],
        cta: { label: "Empezar por €89/mes →", href: "#fp-contact", style: "ghost" },
      },
      {
        id: "plan-photoshoot", name: "Photoshoot Pro", price: "497", currency: "€", period: "pago único · sin retainer",
        featured: false, badge: "SIN RETAINER",
        features: [
          { text: "Generación de 120 imágenes de producto con IA (4 variantes × 30 SKUs)", included: true },
          { text: "Consistencia visual automática aplicando tu guía de marca", included: true },
          { text: "Motor de iluminación cinematográfica (5:1 Rembrandt ratio)", included: true },
          { text: "Semantic SEO audit de 30 fichas de producto", included: true },
          { text: "1 sesión estratégica de pricing financiero (análisis de margen óptimo)", included: true },
          { text: "Entrega en 7 días laborables", included: true },
          { text: "Soporte por email durante 30 días post-entrega", included: true },
          { text: "A/B testing automático", included: false },
          { text: "Auto-pilot continuo", included: false },
          { text: "Acceso a futuros motores IA", included: false },
        ],
        cta: { label: "Pagar una vez →", href: "https://comic-crafter.myshopify.com/cart/57686488711513:1", style: "ghost" },
      },
      {
        id: "plan-growth", name: "Growth Studio", price: "297", currency: "€", period: "por mes · €197 setup único",
        featured: false, badge: null,
        features: [
          { text: "Generación ilimitada de imágenes de producto con IA", included: true },
          { text: "Consistencia visual automática (brand guidelines encoding)", included: true },
          { text: "A/B testing visual automático en 3 productos simultáneos", included: true },
          { text: "Motor de pricing financiero: análisis de elasticidad precio-demanda", included: true },
          { text: "SEO técnico automático para hasta 100 URLs/mes", included: true },
          { text: "Auto-pilot básico: ejecución automática de ganadores A/B", included: true },
          { text: "Dashboard de analytics con atribución multicanal", included: true },
          { text: "Soporte por email y chat (respuesta <24h)", included: true },
          { text: "Integraciones: Shopify, Google Analytics, Meta Pixel", included: true },
          { text: "A/B testing ilimitado", included: false },
          { text: "Custom AI model training", included: false },
          { text: "Soporte dedicado", included: false },
        ],
        cta: { label: "Empezar prueba 14 días →", href: "https://comic-crafter.myshopify.com/cart/57686492479833:1", style: "ghost" },
      },
      {
        id: "plan-performance", name: "Performance Lab", price: "797", currency: "€", period: "por mes · €397 setup único",
        featured: true, badge: "MÁS POPULAR",
        features: [
          { text: "Todo lo incluido en Growth Studio +", included: true },
          { text: "A/B testing visual ilimitado (productos simultáneos ilimitados)", included: true },
          { text: "Auto-pilot avanzado: optimización 24/7 cross-producto", included: true },
          { text: "Pricing financiero predictivo con simulación de escenarios", included: true },
          { text: "SEO técnico automático ilimitado (crawling y fixes automáticos)", included: true },
          { text: "Motor de recomendaciones de producto basado en semantic search", included: true },
          { text: "Algorithmic Schema Augmentation: contenido SEO generado por IA a escala", included: true },
          { text: "Custom AI model fine-tuning con tus datos históricos", included: true },
          { text: "Soporte prioritario por chat y videollamada (respuesta <4h)", included: true },
          { text: "Sesión mensual de estrategia con especialista (60 min)", included: true },
          { text: "Acceso anticipado a nuevos motores IA", included: true },
          { text: "Account manager dedicado", included: false },
        ],
        cta: { label: "Solicitar demo personalizada →", href: "https://comic-crafter.myshopify.com/cart/57686492709209:1", style: "gold" },
      },
      {
        id: "plan-enterprise", name: "Enterprise", price: "Personalizado", currency: "€", period: "desde €2,497/mes · setup incluido",
        featured: false, badge: "ENTERPRISE",
        features: [
          { text: "Todo lo incluido en Performance Lab +", included: true },
          { text: "Account manager dedicado con SLA contractual", included: true },
          { text: "Custom AI development: motores IA diseñados para tus casos de uso", included: true },
          { text: "Infraestructura dedicada (no multi-tenant)", included: true },
          { text: "API privada con webhooks personalizados", included: true },
          { text: "Integración con ERPs, PIMs y custom stacks", included: true },
          { text: "White-label completo (remoción de branding Shopy Crafter)", included: true },
          { text: "SSO enterprise (SAML, OAuth, AD integration)", included: true },
          { text: "Compliance GDPR, SOC2, ISO 27001 certificado", included: true },
          { text: "Soporte 24/7 con respuesta garantizada <1h (critical issues)", included: true },
          { text: "Sesiones estratégicas semanales + quarterly business reviews", included: true },
          { text: "Training continuo del equipo (onboarding ilimitado)", included: true },
          { text: "Desarrollo de features custom bajo demanda", included: true },
        ],
        cta: { label: "Hablar con Enterprise →", href: "#fp-contact", style: "ghost" },
      },
    ],
  },
  testimonials: {
    pill: "Clientes",
    headline: "Lo que dicen los que ya lo usan",
    headlineHighlight: "los que ya lo usan",
    items: [
      { id: "t1", stars: 5, text: "En 3 semanas pasamos de una tasa de conversión del 1.8% al 4.1%. Las imágenes generadas por IA parecen de sesión fotográfica profesional. Mis clientes no pueden creer el antes y el después.", metric: "↑ +128% conversión en 3 semanas", author: "Miguel Rodríguez", role: "Agencia eCommerce · Madrid", initials: "MR", avatarColor: "rgba(200,168,75,0.1)", avatarTextColor: "#e6c668", avatarUrl: null as string | null },
      { id: "t2", stars: 5, text: "El motor de pricing me descubrió que tenía 6 productos vendiendo por debajo del break-even. Después de aplicar el COGS real y la estrategia de precios, el margen medio subió del 28% al 54%.", metric: "↑ +26pts de margen medio", author: "Ana López", role: "Tienda de moda · Barcelona", initials: "AL", avatarColor: "rgba(45,212,159,0.1)", avatarTextColor: "#2dd49f", avatarUrl: null as string | null },
      { id: "t3", stars: 5, text: "Gestiono 11 tiendas para clientes. Antes me llevaba días actualizar imágenes y precios manualmente. Ahora el sistema lo hace solo y yo solo superviso. Me ha triplicado la capacidad de la agencia.", metric: "↑ 3× capacidad de la agencia", author: "Jordi Martínez", role: "Gestión de tiendas Shopify · Valencia", initials: "JM", avatarColor: "rgba(74,158,221,0.1)", avatarTextColor: "#4a9edd", avatarUrl: null as string | null },
    ],
  },
  calculator: {
    pill: "Calcula tu precio",
    headline: "¿Cuánto cuesta optimizar tu tienda?",
    headlineHighlight: "optimizar tu tienda",
    subheadline: "Selecciona los servicios que necesitas y obtén un precio estimado al instante.",
    disclaimer: "* Los precios son orientativos y pueden variar según las necesidades específicas de cada cliente y el nivel de personalización requerido.",
    resultLabel: "Precio estimado",
    oneTimeLabel: "Pago único",
    recurringLabel: "Suscripción mensual",
    ctaLabel: "Solicitar presupuesto personalizado →",
    emptyLabel: "Selecciona al menos un servicio para ver el precio",
    oneTimeServices: [
      { id: "calc-audit", name: "Auditoría Completa", description: "Análisis de todos tus productos + SEO + COGS + plan de acción", price: 197, icon: "📊" },
      { id: "calc-redesign", name: "Rediseño IA (hasta 30 productos)", description: "Títulos, descripciones y SEO optimizados con IA profesional", price: 147, icon: "✏️" },
      { id: "calc-images", name: "Pack 30 Imágenes IA", description: "Fotos profesionales de producto generadas con IA (Hero, Lifestyle, Detalle)", price: 89, icon: "🖼️" },
      { id: "calc-pricing-report", name: "Informe de Precios y Márgenes", description: "COGS real, márgenes, precios competitivos, estrategia de pricing", price: 97, icon: "💰" },
      { id: "calc-seo", name: "Optimización SEO Completa", description: "Meta tags, keywords, Schema JSON-LD, plan de contenido", price: 147, icon: "🔍" },
      { id: "calc-competitor", name: "Informe de Competidores", description: "Análisis detallado de tu competencia directa con estrategia", price: 97, icon: "🎯" },
      { id: "calc-supplier", name: "Investigación de Proveedores", description: "Búsqueda, comparativa y negociación con proveedores", price: 97, icon: "🏭" },
      { id: "calc-email-setup", name: "Setup Email Marketing", description: "Plantillas profesionales, flujos automatizados y configuración", price: 197, icon: "📧" },
      { id: "calc-projection", name: "Informe de Proyección de Ventas", description: "Forecast a 3-6 meses con escenarios y recomendaciones", price: 127, icon: "📈" },
    ],
    recurringServices: [
      { id: "calc-maintenance", name: "Mantenimiento Básico", description: "Monitorización, actualizaciones mensuales y soporte por email", price: 49, period: "/mes", icon: "🛠️" },
      { id: "calc-active", name: "Gestión Activa", description: "Optimización continua + informes semanales + A/B testing", price: 149, period: "/mes", icon: "🚀" },
      { id: "calc-premium", name: "Premium Ilimitado", description: "Todo incluido + prioridad + SLA 99.9% + account manager", price: 399, period: "/mes", icon: "👑" },
    ],
  },
  results: {
    pill: "Resultados probados",
    headline: "Números que hablan solos",
    headlineHighlight: "hablan solos",
    stats: [
      { prefix: "+", num: "234", suffix: "%", label: "Incremento medio en conversión", color: "var(--l-jade)" },
      { prefix: "€", num: "8400", suffix: "/mes", label: "Ingresos adicionales promedio", color: "var(--l-gold)" },
      { prefix: "", num: "99", suffix: ".9%", label: "Uptime garantizado de la plataforma", color: "var(--l-sky)" },
      { prefix: "", num: "6", suffix: " motores", label: "Optimizando tu tienda 24/7", color: "#8b5cf6" },
    ],
    techBadges: [
      { icon: "🛍️", label: "Shopify API" },
      { icon: "🤖", label: "Claude AI" },
      { icon: "🎨", label: "Replicate" },
      { icon: "🔍", label: "GSC" },
      { icon: "📧", label: "Klaviyo" },
      { icon: "🔐", label: "AES-256" },
      { icon: "⚡", label: "Shopify Flow" },
    ],
  },
  contact: {
    pill: "Trabaja con nosotros",
    headline: "Cuéntanos sobre tu negocio.",
    headlineHighlight: "Te contactamos en menos de 24h.",
    subheadline: "Necesitamos conocer tu tienda para personalizar cada motor de IA a tu nicho, ticket medio y modelo de negocio.",
    buttonLabel: "Solicitar acceso gratuito →",
    successTitle: "¡Solicitud recibida!",
    successText: "Nuestra IA ya está analizando tu negocio, mercado, competencia y SEO.",
    successSubtext: "Te contactaremos con un informe detallado en menos de 24h. Revisa también tu carpeta de spam.",
    finePrint: "Sin spam. Solo te contactamos para hablar de tu proyecto.",
    labels: {
      name: "Nombre completo *",
      email: "Email de contacto *",
      phone: "Teléfono",
      storeUrl: "URL de tu tienda Shopify",
      niche: "Nicho / tipo de productos",
      revenue: "Facturación mensual aprox.",
      message: "¿Qué te gustaría mejorar?",
    },
    placeholders: {
      name: "Tu nombre y apellidos",
      email: "tu@email.com",
      phone: "+34 600 000 000",
      storeUrl: "mitienda.myshopify.com",
      niche: "Selecciona tu nicho",
      revenue: "Selecciona rango",
      message: "Cuéntanos sobre tu tienda, tus retos actuales y qué te gustaría conseguir...",
    },
    nicheOptions: ["Moda y ropa", "Electrónica y gadgets", "Hogar y decoración", "Belleza y cosmética", "Deporte y fitness", "Alimentación y gourmet", "Arte y coleccionismo", "Mascotas", "Joyería y accesorios", "Otro"],
    revenueOptions: ["Menos de €1.000", "€1.000 – €5.000", "€5.000 – €15.000", "€15.000 – €50.000", "Más de €50.000"],
    socialLabel: "Redes sociales / Instagram",
    socialPlaceholder: "@tutienda o https://instagram.com/tutienda",
    servicesLabel: "Servicios que necesitas",
    serviceOptions: ["SEO y contenido", "Rediseño de producto", "Imágenes IA", "Pricing y márgenes", "Email marketing", "A/B Testing", "Auditoría completa"],
  },
  cta: {
    pill: "Empieza hoy",
    headline: "Tu tienda merece\nmás que esto.",
    headlineHighlight: "más que esto.",
    subheadline: "14 días gratis. Sin tarjeta. Cancela cuando quieras.\nSetup completo en menos de 5 minutos.",
    placeholder: "tu@agencia.com",
    buttonLabel: "Empezar →",
    finePrint: "Al registrarte aceptas nuestros Términos de Servicio y Política de Privacidad",
  },
  howCards: [
    { icon: "✓", title: "Auditoría completada", sub: "234 productos analizados · 12 acciones urgentes", barPercent: "88" },
    { icon: "🎨", title: "Imágenes generándose", sub: "flux-1.1-pro · 48/234 productos", barPercent: "21" },
    { icon: "⚗️", title: "A/B Test activo", sub: "Bomber Hero · 342 visitas · 67% confianza", barPercent: "67" },
  ],
  howImpact: { icon: "💰", title: "Impacto estimado", sub: "+€8,400/mes proyectados este mes" },
  sectionNav: ["Inicio", "Motores", "Demo", "Resultados", "Precios", "Calculadora", "Contactar"],
  adminBackLabel: "← Volver al panel",
  apkLabels: {
    idle: "📱 Descargar App Android",
    checking: "Verificando...",
    downloading: "⬇ Descargando...",
    building: "🔜 Disponible próximamente",
    unavailable: "No disponible",
  },
  errorMessages: {
    sendFail: "Error al enviar",
    unexpected: "Error inesperado. Inténtalo de nuevo.",
  },
  heroDemoTitles: {
    storeHealth: "Salud de tiendas",
    recentActivity: "Actividad reciente",
  },
  adminPanel: {
    sidebarLabels: {
      yourStores: "Tus Tiendas",
      noStores: "Sin tiendas aún",
      newStore: "Nueva tienda",
      admin: "Administración",
      config: "Configuración",
      madeBy: "Hecho por",
    },
    header: {
      offline: "Sin conexión — tus cambios se guardan localmente",
      search: "Búsqueda",
      active: "Activo",
    },
    user: {
      unlimited: "Ilimitados",
      adminRole: "Administrador",
    },
    tooltips: {
      lightMode: "Modo claro",
      darkMode: "Modo oscuro",
      activateLight: "Activar modo claro",
      activateDark: "Activar modo oscuro",
      logout: "Cerrar sesión",
      mainNav: "Navegación principal",
      shopify: "Tienda Shopify",
      accountSettings: "Ajustes de cuenta",
      notifications: "Notificaciones",
      openNotifications: "Abrir notificaciones",
      closeMenu: "Cerrar menú",
      openMenu: "Abrir menú",
    },
    notifications: {
      title: "Notificaciones",
      empty: "Sin notificaciones nuevas",
      emptyHint: "Las alertas de stock, competidores y logros aparecerán aquí",
    },
  },
  clientPanel: {
    navItems: [
      { href: "/client", label: "Dashboard", icon: "📊" },
      { href: "/client/products", label: "Productos", icon: "📦" },
      { href: "/client/approvals", label: "Aprobaciones", icon: "✅" },
      { href: "/client/messages", label: "Mensajes", icon: "💬" },
      { href: "/client/reports", label: "Reportes", icon: "📈" },
    ],
    sidebar: {
      yourStore: "Tu Tienda",
      defaultName: "Cliente",
      storePanel: "Panel de tienda",
      managedBy: "Gestionado por",
      agency: "tu agencia",
      enginesActive: "6 motores IA activos",
      navigation: "Navegación",
      aiOptimizations: "Optimizaciones IA",
    },
    topbar: "Tu agencia trabaja para ti 24/7",
    tooltips: {
      logout: "Cerrar sesión",
      notifications: "Notificaciones",
    },
    statusOnline: "Online",
    logoBadge: "CLIENT",
  },
  adminNav: {
    modules: [
      { id: "audit", label: "Auditoría", icon: "📊" },
      { id: "redesign", label: "Rediseño IA", icon: "✏️" },
      { id: "images", label: "Imágenes", icon: "🖼" },
      { id: "consistency", label: "Consistencia", icon: "🎨" },
      { id: "ab-testing", label: "A/B Testing", icon: "📈" },
      { id: "pricing", label: "Pricing", icon: "💰" },
      { id: "seo", label: "SEO Engine", icon: "🔍" },
      { id: "vault", label: "Repositorio", icon: "🗄️" },
      { id: "exports", label: "Exportar", icon: "📥" },
    ],
    shopybrain: [
      { label: "IA Brain", icon: "🧠", href: "/admin/shopybrain" },
      { label: "Centro de Comando", icon: "⚡", href: "/admin/command-center" },
      { label: "Memorias", icon: "💾", href: "/admin/shopybrain/memories" },
      { label: "Knowledge Domains", icon: "🔬", href: "/admin/shopybrain/insights" },
      { label: "Sesiones Estudio", icon: "📚", href: "/admin/shopybrain/study" },
      { label: "Mi Pricing CFO", icon: "💰", href: "/admin/my-pricing" },
      { label: "Email Marketing", icon: "📧", href: "/admin/emails" },
      { label: "Flujos de Email", icon: "🔄", href: "/admin/email-flows" },
      { label: "Editor Landing", icon: "✏️", href: "/admin/cms" },
      { label: "Ver Landing", icon: "🌐", href: "/landing" },
    ],
    admin: [
      { label: "CRM Clientes", icon: "👥", href: "/admin/clients" },
      { label: "Productos Global", icon: "📦", href: "/admin/products" },
      { label: "A/B Tests Global", icon: "📈", href: "/admin/abtests" },
      { label: "Automaciones", icon: "⚡", href: "/admin/automations" },
      { label: "Revenue & CRM", icon: "💰", href: "/admin/revenue" },
      { label: "Revenue Intel", icon: "📊", href: "/admin/intelligence" },
      { label: "Gemini Research", icon: "🔬", href: "/admin/gemini-intel" },
      { label: "M7 Inventario", icon: "🗄", href: "/admin/inventory" },
      { label: "Competitor Intel", icon: "🎯", href: "/admin/competitors" },
      { label: "Predicciones ML", icon: "🔮", href: "/admin/forecast" },
      { label: "Logros", icon: "🏆", href: "/admin/achievements" },
      { label: "Plan 30-60-90", icon: "🗺", href: "/admin/roadmap" },
      { label: "APK Android", icon: "📱", href: "/admin/apk" },
      { label: "Tienda / Store", icon: "🛒", href: "/tienda" },
      { label: "System Health", icon: "🖥", href: "/admin/system" },
    ],
  },
  labels: {
    home: {
      welcome: "Bienvenida,",
      subtitle: "Shopy Crafter · Panel de control",
      storesActive: "Tiendas activas",
      aiMemories: "Memorias IA",
      systemStatus: "Estado del sistema",
      systemOk: "Operativo",
      aiEnginesActive: "Motores IA activos",
      connectedStores: "Tiendas conectadas",
      newStore: "Nueva tienda",
      noStores: "Sin tiendas conectadas",
      noStoresDesc: "Conecta tu primera tienda Shopify para empezar a optimizar con IA.",
      connectFirst: "Conectar primera tienda",
      quickActions: "Acciones rápidas",
      actions: {
        shopyCrafter: "Shopy Crafter",
        shopyCrafterDesc: "IA central · memorias activas",
        revenue: "Revenue",
        revenueDesc: "Métricas de ingresos y KPIs",
        emailMarketing: "Email Marketing",
        emailMarketingDesc: "Flujos y campañas automatizadas",
        competitors: "Competitors",
        competitorsDesc: "Análisis de competencia",
        forecast: "Forecast",
        forecastDesc: "Predicciones de revenue ML",
        pricingCfo: "Mi Pricing CFO",
        pricingCfoDesc: "Estructura de costes · propuestas",
        roadmap: "Roadmap",
        roadmapDesc: "Fases de implementación",
        settings: "Configuración",
        settingsDesc: "Ajustes del sistema",
      },
    },
    login: {
      title: "Shopy Crafter",
      subtitle: "Plataforma de agencia premium",
      heading: "Iniciar sesión",
      email: "Email",
      emailPlaceholder: "tu@email.com",
      password: "Contraseña",
      loginBtn: "Entrar",
      loggingIn: "Iniciando sesión...",
      forgotPassword: "¿Olvidaste tu contraseña?",
      loginError: "Error al iniciar sesión",
    },
    forgotPassword: {
      title: "Recuperar contraseña",
      subtitle: "Introduce tu email y te enviaremos un enlace de recuperación",
      emailLabel: "Email",
      emailPlaceholder: "tu@email.com",
      sendBtn: "Enviar enlace de recuperación",
      sending: "Enviando…",
      sentTitle: "Email enviado",
      sentDesc: "Si el email está registrado, recibirás un enlace para restablecer tu contraseña. Revisa también la carpeta de spam.",
      backToLogin: "← Volver al login",
      backLink: "Volver al login",
      errorProcess: "Error al procesar la solicitud",
      errorConnection: "Error de conexión. Inténtalo de nuevo.",
    },
    resetPassword: {
      title: "Restablecer contraseña",
      subtitle: "Crea una nueva contraseña segura para tu cuenta",
      newPassword: "Nueva contraseña",
      newPasswordPlaceholder: "Mínimo 8 caracteres",
      confirmPassword: "Confirmar nueva contraseña",
      confirmPlaceholder: "Repite la nueva contraseña",
      resetBtn: "Restablecer contraseña",
      resetting: "Restableciendo…",
      successTitle: "¡Contraseña actualizada!",
      successDesc: "Ya puedes iniciar sesión con tu nueva contraseña.",
      goToLogin: "Ir al login",
      errorNoToken: "Token de recuperación no encontrado en la URL.",
      errorMinLength: "La contraseña debe tener al menos 8 caracteres.",
      errorMismatch: "Las contraseñas no coinciden.",
      strength: ["", "Muy débil", "Débil", "Aceptable", "Fuerte", "Muy fuerte"],
    },
    inviteSetup: {
      title: "Configura tu acceso",
      subtitle: "Crea tu contraseña para acceder al panel de tu tienda.",
      name: "Tu nombre",
      namePlaceholder: "Nombre completo",
      password: "Contraseña",
      passwordPlaceholder: "Mínimo 8 caracteres",
      confirmPassword: "Confirmar contraseña",
      confirmPlaceholder: "Repite tu contraseña",
      setupBtn: "Activar mi cuenta",
      settingUp: "Configurando...",
      errorMismatch: "Las contraseñas no coinciden",
      errorMinLength: "Mínimo 8 caracteres",
      errorSetup: "Error al configurar la cuenta",
    },
    connectionGuides: {
      expandAll: "Expandir todo",
      collapseAll: "Colapsar todo",
      backToDashboard: "Volver al dashboard",
      helpTitle: "Guías de Conexión",
      helpSubtitle: "Instrucciones paso a paso para conectar tu tienda con Shopy Crafter. Selecciona tu plataforma para ver la guía completa.",
      testConnection: "Probar Conexión",
      testing: "Probando...",
      testSuccess: "Conexión exitosa",
      testFailed: "Error de conexión",
      shopify: {
        guideTitle: "Guía de conexión: Shopify",
        guideSubtitle: "5 pasos para conectar tu tienda",
        step1: {
          title: "Crea una app personalizada en Shopify",
          description: "Ve a tu panel de Shopify Admin → Configuración → Apps y canales de venta → Desarrollar apps → Crear una app. Dale un nombre descriptivo como \"Shopy Crafter\".",
          tip: "Si no ves la opción \"Desarrollar apps\", necesitas ser propietario de la tienda o tener permisos de desarrollador.",
          linkLabel: "Documentación de Shopify Apps",
          validation: "App creada en el panel de Shopify",
        },
        step2: {
          title: "Configura los permisos (scopes) de la API",
          description: "En la configuración de tu app, ve a \"Configuración de la API de Admin\" y activa los siguientes permisos: read_products, write_products, read_orders, read_customers, read_analytics, read_inventory, write_inventory, read_price_rules, write_price_rules, read_content, write_content, read_themes, write_themes.",
          tip: "Estos permisos permiten a Shopy Crafter optimizar productos, gestionar imágenes, analizar ventas y mejorar el SEO de tu tienda.",
          validation: "Permisos configurados correctamente",
        },
        step3: {
          title: "Instala la app en tu tienda",
          description: "Haz clic en \"Instalar app\" en la parte superior de la página de configuración. Shopify te pedirá que confirmes los permisos. Acepta para completar la instalación.",
          validation: "App instalada en la tienda",
        },
        step4: {
          title: "Copia las credenciales API",
          description: "Una vez instalada la app, ve a la pestaña \"Credenciales de la API\". Copia el Client ID (API Key) y genera un Client Secret (API Secret Key). El token de acceso se mostrará una sola vez — cópialo inmediatamente.",
          tip: "Guarda el API Secret Key en un lugar seguro. Si lo pierdes, tendrás que generar uno nuevo.",
          validation: "Client ID y Client Secret copiados",
        },
        step5: {
          title: "Pega las credenciales en el formulario",
          description: "Introduce tu dominio de Shopify (ej: mi-tienda.myshopify.com), pega el Client ID en el campo \"API Key\" y el Client Secret en el campo \"Clave secreta\". Haz clic en \"Probar Conexión\" para verificar.",
          validation: "Credenciales introducidas y conexión verificada",
        },
      },
      woocommerce: {
        guideTitle: "Guía de conexión: WooCommerce",
        guideSubtitle: "8 pasos para conectar tu tienda",
        step1: { title: "Accede al panel de WordPress", description: "Inicia sesión en tu panel de administración de WordPress. Normalmente accedes desde tutienda.com/wp-admin con tus credenciales de administrador.", validation: "Sesión iniciada en WordPress Admin" },
        step2: { title: "Navega a WooCommerce → REST API", description: "Ve a WooCommerce → Ajustes → Avanzado → REST API. Esta sección te permite crear claves de acceso para aplicaciones externas.", tip: "Si no ves la pestaña \"REST API\", asegúrate de tener WooCommerce actualizado a la última versión.", validation: "Sección REST API encontrada" },
        step3: { title: "Crea una nueva clave API", description: "Haz clic en \"Añadir clave\". En el formulario: Descripción: \"Shopy Crafter\", Usuario: Selecciona tu usuario administrador, Permisos: Selecciona \"Lectura/Escritura\".", tip: "Es importante seleccionar \"Lectura/Escritura\" (no solo \"Lectura\") para que Shopy Crafter pueda optimizar tus productos.", validation: "Clave creada con permisos de Lectura/Escritura" },
        step4: { title: "Copia las claves INMEDIATAMENTE", description: "Al hacer clic en \"Generar clave API\", se mostrarán el Consumer Key (empieza por ck_) y el Consumer Secret (empieza por cs_). ¡COPIA AMBOS AHORA! El Consumer Secret solo se muestra una vez.", tip: "Si pierdes el Consumer Secret, tendrás que eliminar la clave y crear una nueva.", validation: "Consumer Key y Consumer Secret copiados" },
        step5: { title: "Verifica los Permalinks", description: "Ve a Ajustes → Enlaces permanentes. Asegúrate de que NO esté seleccionada la opción \"Simple\" (Plain). Recomendamos \"Nombre de la entrada\" (Post name). Guarda los cambios.", tip: "WooCommerce REST API requiere URLs amigables (pretty permalinks). Si usas \"Simple\", la API no funcionará.", validation: "Permalinks configurados correctamente" },
        step6: { title: "Verifica que tu tienda usa HTTPS", description: "Tu tienda debe usar HTTPS (certificado SSL) para proteger las credenciales durante la comunicación.", tip: "Si tu tienda no tiene SSL, contacta con tu proveedor de hosting para activarlo. La mayoría ofrecen certificados Let's Encrypt gratuitos.", validation: "HTTPS activo en la tienda" },
        step7: { title: "(Opcional) Habilitar acceso SEO con Yoast", description: "Si tienes Yoast SEO instalado, añade el snippet PHP a functions.php para que Shopy Crafter pueda gestionar los meta títulos y descripciones SEO.", codeLabel: "Snippet PHP para functions.php:", tip: "Este paso es opcional. Sin él, Shopy Crafter puede optimizar productos pero no podrá gestionar los campos SEO de Yoast directamente." },
        step8: { title: "Pega las credenciales en el formulario", description: "Introduce la URL de tu tienda (ej: https://mitienda.com), pega el Consumer Key (ck_...) y el Consumer Secret (cs_...). Haz clic en \"Probar Conexión\" para verificar.", validation: "Credenciales introducidas y conexión verificada" },
      },
      prestashop: {
        guideTitle: "Guía de conexión: PrestaShop",
        guideSubtitle: "8 pasos para conectar tu tienda",
        step1: { title: "Accede al back office de PrestaShop", description: "Inicia sesión en tu panel de administración de PrestaShop.", validation: "Sesión iniciada en el back office" },
        step2: { title: "Navega a Parámetros Avanzados → Webservice", description: "En el menú lateral, ve a Parámetros Avanzados → Webservice.", validation: "Sección Webservice encontrada" },
        step3: { title: "Activa el webservice", description: "Asegúrate de que el interruptor \"Activar el servicio web\" esté en \"Sí\".", tip: "Sin el webservice activado, ninguna aplicación externa podrá conectarse a tu tienda.", validation: "Webservice activado" },
        step4: { title: "Crea una nueva clave de webservice", description: "Haz clic en \"Añadir nueva clave de webservice\" y luego en \"Generar\" para crear una clave de 32 caracteres.", tip: "La clave debe tener exactamente 32 caracteres alfanuméricos.", validation: "Clave de 32 caracteres generada" },
        step5: { title: "Configura los permisos de recursos", description: "Activa TODAS las casillas (GET, POST, PUT, DELETE) para: products, categories, images, stock_availables, combinations, product_option_values, orders, customers, manufacturers, tags.", tip: "Puedes hacer clic en la cabecera de columna para marcar todas las casillas a la vez.", validation: "Permisos configurados para todos los recursos necesarios" },
        step6: { title: "Guarda la clave", description: "Haz clic en \"Guardar\" en la parte inferior de la página.", validation: "Clave guardada correctamente" },
        step7: { title: "Verifica las URLs amigables", description: "Ve a Preferencias → SEO y URLs. Activa \"URLs amigables\" (Friendly URLs).", tip: "Si tu servidor no tiene mod_rewrite habilitado, las URLs amigables no funcionarán.", validation: "URLs amigables activadas" },
        step8: { title: "Pega la clave en el formulario", description: "Introduce la URL de tu tienda y pega la clave de 32 caracteres. Haz clic en \"Probar Conexión\" para verificar.", validation: "Clave introducida y conexión verificada" },
      },
      universal: {
        guideTitle: "Guía: Auditoría Universal",
        guideSubtitle: "4 pasos — sin configuración técnica",
        step1: { title: "Introduce el nombre de tu negocio", description: "Escribe el nombre de tu empresa o marca.", validation: "Nombre introducido" },
        step2: { title: "Introduce la URL de tu web", description: "Introduce la URL completa de tu sitio web (ej: https://miempresa.com).", validation: "URL introducida" },
        step3: { title: "(Opcional) Añade tu Instagram", description: "Si tienes cuenta de Instagram, añade la URL en el campo de contexto de marca." },
        step4: { title: "Haz clic en Guardar", description: "No necesitas credenciales API. Nuestro sistema analizará automáticamente tu web.", validation: "Proyecto guardado y análisis iniciado" },
        whatWeAnalyze: "¿Qué analizamos?",
        analyze1: "Estructura y navegación del sitio web",
        analyze2: "SEO técnico: meta tags, schema, sitemap, robots.txt",
        analyze3: "Velocidad de carga y Core Web Vitals",
        analyze4: "Calidad del contenido y copywriting",
        analyze5: "Presencia en redes sociales",
        analyze6: "Oportunidades de mejora y recomendaciones",
      },
      errors: {
        AUTH_FAILED: "Credenciales inválidas. Verifica tu Consumer Key y Consumer Secret.",
        PERMISSIONS_INSUFFICIENT: "La clave API no tiene permisos suficientes. Habilita Lectura/Escritura.",
        SSL_REQUIRED: "Tu tienda necesita HTTPS para conectarse.",
        WEBSERVICE_DISABLED: "El webservice de PrestaShop está desactivado. Actívalo en Parámetros Avanzados.",
        URL_UNREACHABLE: "No podemos acceder a la URL. Verifica que sea correcta y esté online.",
        STORE_NOT_FOUND: "No se encontró la tienda. Verifica que el dominio sea correcto.",
        INVALID_API_KEY: "La clave API no es válida. Verifica que tenga 32 caracteres.",
        TIMEOUT: "La conexión ha tardado demasiado. Inténtalo de nuevo.",
        UNKNOWN: "Error desconocido. Inténtalo de nuevo o contacta con soporte.",
      },
    },
    newProject: {
      backToDashboard: "Volver al dashboard",
      title: "Añadir Tienda",
      subtitle: "Con el Client ID y la Clave Secreta, el sistema genera el token de acceso automáticamente. Solo necesitas 2 credenciales.",
      projectName: "Nombre del proyecto",
      projectNamePlaceholder: "Ej: Comic Crafter",
      shopDomain: "Dominio Shopify *",
      shopDomainPlaceholder: "mi-tienda.myshopify.com",
      credentialsHint: "Credenciales — Shopify Admin → Apps → Desarrollar apps → tu app → Credenciales de la API",
      apiKey: "API Key (Client ID) *",
      apiSecret: "Clave secreta de la API *",
      encryptionNote: "🔒 Credenciales cifradas con AES-256. El token de acceso se genera automáticamente al guardar.",
      clientPlan: "Plan del cliente",
      brandContext: "Contexto de marca (opcional — mejora los resultados de la IA)",
      niche: "Nicho del negocio",
      nichePlaceholder: "Moda urbana, Gadgets tech...",
      brandTone: "Tono de marca",
      brandTonePlaceholder: "Premium y sofisticado...",
      audience: "Audiencia objetivo",
      audiencePlaceholder: "Hombres 25-40 streetwear",
      markets: "Mercados principales",
      marketsPlaceholder: "España, México, Colombia",
      domainRequired: "Dominio requerido",
      apiKeyRequired: "API Key requerida",
      secretRequired: "Clave secreta requerida",
      saving: "Guardando...",
      save: "Guardar tienda",
      errorSave: "Error al guardar la tienda",
      errorConnection: "Error de conexión. Comprueba la red e inténtalo de nuevo.",
    },
    adminClients: {
      title: "CRM Clientes",
      inviteBtn: "Invitar Cliente",
      inviteTitle: "📨 Invitar Cliente",
      inviteSubtitle: "El enlace generado es exclusivo e intransferible para esa tienda.",
      clientName: "Nombre del cliente",
      clientNamePlaceholder: "Ej: María García",
      clientEmail: "Email del cliente",
      clientEmailPlaceholder: "cliente@tienda.com",
      storeLabel: "Tienda (proyecto)",
      loadingStores: "Cargando tiendas...",
      noStores: "No hay tiendas creadas aún. Crea un proyecto primero.",
      selectStore: "— Selecciona la tienda —",
      selectStoreError: "Selecciona la tienda del cliente",
      exclusive: "EXCLUSIVO",
      cancel: "Cancelar",
      generateLink: "Generar enlace",
      inviteError: "Error al invitar",
      linkCreated: "✅ Enlace creado para",
      emailSent: "📧 Invitación enviada por email a",
      importantNote: "⚠️ Importante:",
      copyLink: "Copiar enlace",
      copied: "¡Copiado!",
      close: "Cerrar",
      never: "Nunca",
      today: "Hoy",
      yesterday: "Ayer",
      paymentTitle: "Generar Link de Pago",
      loadingServices: "Cargando servicios...",
      serviceLabel: "Servicio a cobrar",
      selectService: "— Selecciona un servicio —",
      internalNote: "Nota interna (opcional)",
      generatePayment: "Generar link Shopify",
      generating: "Generando...",
      copyPaymentLink: "Copiar link",
      sendViaChat: "Enviar por chat",
      proposalTitle: "Nueva Propuesta",
      proposalSent: "Propuesta Enviada",
      proposalSentDesc: "El cliente la verá en su panel de Aprobaciones",
      proposalType: "Tipo de propuesta",
      proposalTitleField: "Título *",
      proposalDesc: "Descripción *",
      currentValue: "Valor Actual",
      proposedValue: "Valor Propuesto",
      reasoning: "Razonamiento",
      estimatedImpact: "Impacto Estimado",
      sendProposal: "Enviar Propuesta",
      proposalError: "Error al enviar propuesta",
      typeLabels: {
        price_change: "Cambio de Precio",
        seo_update: "Mejora SEO",
        product_update: "Actualización Producto",
        image_change: "Cambio de Imagen",
        strategy: "Estrategia General",
        other: "Otro",
      },
    },
    clientDashboard: {
      optimizingNote: "Tu tienda está siendo optimizada activamente",
      welcome: "Bienvenido,",
      lastOptimized: "Última optimización",
      products: "Productos",
      inCatalog: "en tu catálogo",
      avgScore: "Score promedio",
      aiQuality: "calidad IA",
      approvals: "Aprobaciones",
      pending: "pendientes",
      enginesActive: "Motores activos",
      optimizing: "optimizando",
      engineStatus: "Motores IA — Estado",
      engineActive: "Activo",
      engineOptimizing: "Optimizando tu tienda",
      recentActivity: "Actividad Reciente",
      emptyActivity: "La actividad aparecerá aquí cuando tu agencia realice optimizaciones.",
      catalogScore: "Score promedio de tu catálogo",
      catalogExcellent: "Tu catálogo está en excelente estado.",
      catalogGood: "Tu catálogo tiene margen de mejora. Tu agencia ya está trabajando en ello.",
      catalogImproving: "Tu agencia está priorizando mejoras en tu catálogo.",
      engineNames: {
        M1: "Auditoría de Productos",
        M2: "Rediseño IA",
        M3: "Generación de Imágenes",
        M4: "Consistencia Visual",
        M5: "A/B Testing",
        M6: "SEO & Contenido",
        M7: "Precios Inteligentes",
      },
      timeAgo: {
        justNow: "hace un momento",
        min: "min",
        h: "h",
        d: "d",
      },
    },
    clientProducts: {
      title: "Tus Productos",
      subtitle: "productos en tu catálogo, ordenados por score de calidad.",
      loading: "Cargando productos...",
      emptyTitle: "Sin productos todavía",
      emptyDesc: "Tu agencia aún no ha sincronizado tu catálogo.",
      score: "Score",
      images: "imágenes",
    },
    clientApprovals: {
      title: "Aprobaciones Pendientes",
      subtitle: "Tu agencia necesita tu confirmación antes de aplicar estos cambios en tu tienda.",
      allClear: "Todo al día",
      allClearDesc: "No tienes aprobaciones pendientes por ahora.",
      approve: "Aprobar",
      reject: "Rechazar",
      approved: "Aprobado",
      rejected: "Rechazado",
      pending: "Pendiente",
      before: "Antes",
      after: "Después",
      reasoning: "Razonamiento IA",
      estimatedImpact: "Impacto estimado",
      commentLabel: "Comentario (opcional para rechazo)",
      commentPlaceholder: "¿Por qué rechazas este cambio?",
      history: "Historial",
      commentPrefix: "Comentario:",
    },
    clientMessages: {
      title: "Mensajes",
      subtitle: "Comunicación directa con tu agencia.",
      agencyName: "Tu Agencia",
      agencyStatus: "En línea · Respuesta en <24h",
      placeholder: "Escribe tu mensaje...",
      send: "Enviar",
      emptyTitle: "No hay mensajes aún. ¡Escribe a tu agencia!",
    },
    clientReports: {
      title: "Reportes",
      subtitle: "Resumen de KPIs y actividad de optimización de tu tienda",
      exportCsv: "CSV",
      exportTxt: "TXT",
      exporting: "Exportando...",
      generating: "Generando...",
      kpiProducts: "Productos optimizados",
      kpiProductsSub: "por los motores IA",
      kpiImages: "Imágenes generadas",
      kpiImagesSub: "con IA generativa",
      kpiSeo: "Score SEO promedio",
      kpiSeoSub: "de tu catálogo",
      kpiImpact: "Impacto estimado",
      kpiImpactSub: "en conversiones",
      seoTitle: "Rendimiento SEO",
      seoGeneral: "Score general",
      seoTitles: "Títulos y descripciones",
      seoMeta: "Meta tags",
      seoAlt: "Imágenes ALT text",
      seoEmpty: "Los datos SEO aparecerán cuando se ejecute la primera auditoría.",
      activityTitle: "Actividad reciente",
      activityEmpty: "La actividad aparecerá aquí cuando se realicen optimizaciones.",
      periodTitle: "Resumen del período",
      periodExportHint: "Usa los botones de exportar arriba para descargar un reporte completo.",
      download: "Descargar",
      viewReport: "Ver reporte",
    },
    common: {
      loading: "Cargando...",
      save: "Guardar",
      cancel: "Cancelar",
      close: "Cerrar",
      delete: "Eliminar",
      edit: "Editar",
      back: "Volver",
      next: "Siguiente",
      confirm: "Confirmar",
      error: "Error",
      success: "Éxito",
      search: "Buscar",
      noResults: "Sin resultados",
      retry: "Reintentar",
      yes: "Sí",
      no: "No",
    },
  },
  footer: {
    tagline: "Shopy Crafter — Optimización IA para tiendas Shopify. Powered by Claude AI + Gemini + Replicate.",
    columns: [
      { title: "Producto", links: [{ label: "Motores IA", href: "#features" }, { label: "Precios", href: "#pricing" }, { label: "Changelog", href: "#" }, { label: "Documentación", href: "#" }, { label: "API Reference", href: "#" }] },
      { title: "Empresa", links: [{ label: "Sobre nosotros", href: "#" }, { label: "Blog", href: "#" }, { label: "Casos de éxito", href: "#" }, { label: "Afiliados", href: "#" }, { label: "Contacto", href: "#" }] },
      { title: "Legal", links: [{ label: "Privacidad", href: "#" }, { label: "Términos", href: "#" }, { label: "Cookies", href: "#" }, { label: "RGPD", href: "#" }, { label: "Seguridad", href: "#" }] },
    ],
    copyright: "© 2026 Shopy Crafter · Agency Platform. Todos los derechos reservados.",
    badges: ["RGPD", "AES-256", "SOC2"],
  },
};
