export const DEFAULT_CMS_CONTENT = {
  meta: {
    lastUpdated: new Date().toISOString(),
    updatedBy: "system",
    version: 1,
  },
  sectionOrder: ["site", "backgrounds", "nav", "hero", "features", "stats", "how", "results", "pricing", "calculator", "contact", "howCards", "sectionNav", "apkLabels", "errorMessages", "heroDemoTitles", "adminPanel", "clientPanel", "adminNav", "footer"],
  backgrounds: {
    hero: { type: "particles", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
    features: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#2dd49f" },
    pricing: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
    how: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
    results: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#2dd49f" },
    calculator: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
    contact: { type: "none", videoUrl: "", galleryImages: [], particleColor: "#c8a84b" },
  },
  site: {
    name: "Shopy Crafter",
    tagline: "La plataforma de agencia Shopify más completa",
    logo: { type: "emoji", value: "⚡", imageUrl: null },
    favicon: "⚡",
    primaryColor: "#c8a84b",
    accentColor: "#2dd49f",
    font_heading: "Instrument Serif",
    font_body: "Geist",
  },
  nav: {
    links: [
      { id: "nav-1", label: "Motores", href: "#features" },
      { id: "nav-2", label: "Cómo funciona", href: "#how" },
      { id: "nav-3", label: "Precios", href: "#pricing" },
      { id: "nav-4", label: "Clientes", href: "#testimonials" },
    ],
    ctaPrimary: { label: "Solicitar acceso →", href: "#cta" },
    ctaSecondary: { label: "Iniciar sesión", href: "/login" },
  },
  hero: {
    pill: { text: "Nuevo · 6 motores de IA activos · Versión 2.0", visible: true },
    headline: "La agencia Shopify\nque trabaja 24/7\npor ti",
    headlineHighlight: "24/7",
    subheadline: "Shopy Crafter gestiona, optimiza y potencia tiendas Shopify de manera completamente autónoma. Imágenes profesionales, pricing inteligente, SEO técnico y tests A/B — todo en piloto automático. Un solo cerebro para toda tu agencia.",
    ctaPrimary: { label: "Empezar gratis 14 días →", href: "#cta" },
    ctaSecondary: { label: "▶ Ver en acción", href: "#how" },
    ctaApk: { label: "📱 Descargar App Android", href: "#" },
    trustItems: ["Sin tarjeta de crédito", "Setup en 5 minutos", "Cancela cuando quieras", "RGPD compliant"],
    scrollHint: "Desliza para explorar",
    imageUrl: null as string | null,
    demo: {
      url: "app.shopifyai.pro/admin — Moda Urbana",
      status: "6 motores activos",
      navItems: ["Overview", "Productos", "Imágenes IA", "Pricing + P&L", "SEO Técnico", "A/B Tests"],
      metrics: [
        { label: "Revenue", value: "€32.4K", change: "↑ 22%" },
        { label: "Conversión", value: "4.2%", change: "↑ 0.9pp" },
        { label: "Margen", value: "61%", change: "↑ 8pts" },
        { label: "SEO", value: "88", change: "↑ 23pts" },
      ],
      stores: [
        { name: "Moda Urbana", score: "88" },
        { name: "TechGadgets", score: "71" },
        { name: "Casa & Arte", score: "42" },
      ],
      activity: [
        "A/B Test ganador · +28% conv.",
        "48 imágenes · €13.44",
        "Schema SEO · 234 productos",
      ],
    },
  },
  features: {
    pill: "Motores IA",
    headline: "Seis motores. Una sola plataforma.",
    subheadline: "Cada motor trabaja de forma autónoma y coordinada para potenciar todos los aspectos de tu tienda.",
    items: [
      { id: "feat-1", num: "M01", icon: "🖼️", iconBg: "rgba(45,212,159,0.1)", title: "Generación de Imágenes", description: "8 tipos de imagen profesional por producto usando Replicate flux-1.1-pro. Hero, Lifestyle, Detalle, Packaging, UGC, Escala, Bundle e Infografía SVG generada directamente.", tags: ["flux-1.1-pro", "recraft-v3", "~€0.25/prod"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "94%" }, { label: "Velocidad", value: "<2s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-2", num: "M02", icon: "🎨", iconBg: "rgba(200,168,75,0.1)", title: "Consistencia Visual", description: "Extrae el ADN visual de tu tienda y aplica StyleLock a todas las generaciones. Garantiza coherencia de marca en cada imagen, colección y set fotográfico.", tags: ["StyleLock", "Visual DNA", "Set Mode"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "97%" }, { label: "Velocidad", value: "<3s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-3", num: "M03", icon: "⚗️", iconBg: "rgba(74,158,221,0.1)", title: "A/B Testing Automático", description: "Pixel tracker propio, z-test estadístico al 95% de confianza, declaración automática de ganador y generación inmediata del siguiente challenger.", tags: ["Z-test 95%", "Pixel tracker", "Auto-winner"], imageUrl: null as string | null, stats: [{ label: "Confianza", value: "95%" }, { label: "Velocidad", value: "<1s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-4", num: "M04", icon: "⚡", iconBg: "rgba(200,168,75,0.08)", title: "Auto-Pilot 24/7", description: "Webhook trigger en cada nuevo producto. Auditoría inmediata, generación automática de Hero y Lifestyle, test A/B creado y activo sin intervención manual.", tags: ["Webhook", "Cron jobs", "Informe mensual"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "99%" }, { label: "Velocidad", value: "<5s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-5", num: "M05", icon: "📊", iconBg: "rgba(200,168,75,0.1)", title: "Pricing Financiero", description: "Motor COGS completo, análisis de competencia en tiempo real, economista IA con pricing psicológico, dashboard P&L y alertas de margen.", tags: ["COGS Engine", "Competencia", "P&L en vivo"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "92%" }, { label: "Velocidad", value: "<2s" }, { label: "Uptime", value: "99.9%" }] },
      { id: "feat-6", num: "M06", icon: "🔍", iconBg: "rgba(45,212,159,0.08)", title: "SEO Técnico", description: "Schema JSON-LD completo, meta tags optimizados por Claude, sitemap dinámico, Core Web Vitals, estrategia de keywords y generación automática de blog posts.", tags: ["Schema JSON-LD", "CWV", "Blog IA"], imageUrl: null as string | null, stats: [{ label: "Precisión", value: "96%" }, { label: "Velocidad", value: "<4s" }, { label: "Uptime", value: "99.9%" }] },
    ],
  },
  stats: [
    { id: "s1", num: "3.4×", label: "Más conversión con 5+ imágenes" },
    { id: "s2", num: "€0.25", label: "Coste por producto optimizado" },
    { id: "s3", num: "95%", label: "Confianza estadística en A/B tests" },
    { id: "s4", num: "24/7", label: "Auto-pilot completamente autónomo" },
  ],
  how: {
    pill: "Cómo funciona",
    headline: "De zero a tienda optimizada\nen minutos",
    headlineHighlight: "tienda optimizada",
    steps: [
      { num: "01", title: "Conecta tu tienda Shopify", desc: "Introduce tu dominio y Access Token. La plataforma se conecta al instante con la API de Shopify y escanea todo tu catálogo, configuración y métricas actuales." },
      { num: "02", title: "La IA audita cada producto", desc: "Claude analiza título, descripción, precio, imágenes y SEO de cada producto. Asigna una nota A–F y genera una lista priorizada de mejoras con impacto estimado en revenue." },
      { num: "03", title: "Activa los 6 motores", desc: "Con un clic, los 6 motores se ponen en marcha: generan imágenes, optimizan precios, aplican SEO técnico, inician tests A/B y configuran automatizaciones." },
      { num: "04", title: "Resultados compuestos cada semana", desc: "El sistema mejora solo. Cada test que termina genera el siguiente. Cada precio optimizado se monitoriza. Cada imagen que convierte se convierte en el nuevo estándar." },
    ],
  },
  pricing: {
    pill: "Precios",
    headline: "Transparente. Sin sorpresas.",
    subheadline: "Retainer mensual + setup único. Sin permanencia. Cancela cuando quieras.",
    plans: [
      {
        id: "plan-photoshoot", name: "Photoshoot Pro", price: "497", currency: "€", period: "pago único · sin retainer",
        featured: false, badge: "SIN RETAINER",
        features: [
          { text: "Generación de 120 imágenes de producto con IA (4 variantes × 30 SKUs)", included: true },
          { text: "Consistencia visual automática aplicando tu guía de marca", included: true },
          { text: "Motor de iluminación cinematográfica (5:1 Rembrandt ratio)", included: true },
          { text: "Semantic SEO audit de 30 fichas de producto", included: true },
          { text: "1 sesión estratégica de pricing financiero (análisis de margen óptimo)", included: true },
          { text: "Entrega en 7 días laborables", included: true },
          { text: "Soporte por email durante 30 días post-entrega", included: true },
          { text: "A/B testing automático", included: false },
          { text: "Auto-pilot continuo", included: false },
          { text: "Acceso a futuros motores IA", included: false },
        ],
        cta: { label: "Pagar una vez →", href: "https://comic-crafter.myshopify.com/cart/57686488711513:1", style: "ghost" },
      },
      {
        id: "plan-growth", name: "Growth Studio", price: "297", currency: "€", period: "por mes · €197 setup único",
        featured: false, badge: null,
        features: [
          { text: "Generación ilimitada de imágenes de producto con IA", included: true },
          { text: "Consistencia visual automática (brand guidelines encoding)", included: true },
          { text: "A/B testing visual automático en 3 productos simultáneos", included: true },
          { text: "Motor de pricing financiero: análisis de elasticidad precio-demanda", included: true },
          { text: "SEO técnico automático para hasta 100 URLs/mes", included: true },
          { text: "Auto-pilot básico: ejecución automática de ganadores A/B", included: true },
          { text: "Dashboard de analytics con atribución multicanal", included: true },
          { text: "Soporte por email y chat (respuesta <24h)", included: true },
          { text: "Integraciones: Shopify, Google Analytics, Meta Pixel", included: true },
          { text: "A/B testing ilimitado", included: false },
          { text: "Custom AI model training", included: false },
          { text: "Soporte dedicado", included: false },
        ],
        cta: { label: "Empezar prueba 14 días →", href: "https://comic-crafter.myshopify.com/cart/57686492479833:1", style: "ghost" },
      },
      {
        id: "plan-performance", name: "Performance Lab", price: "797", currency: "€", period: "por mes · €397 setup único",
        featured: true, badge: "MÁS POPULAR",
        features: [
          { text: "Todo lo incluido en Growth Studio +", included: true },
          { text: "A/B testing visual ilimitado (productos simultáneos ilimitados)", included: true },
          { text: "Auto-pilot avanzado: optimización 24/7 cross-producto", included: true },
          { text: "Pricing financiero predictivo con simulación de escenarios", included: true },
          { text: "SEO técnico automático ilimitado (crawling y fixes automáticos)", included: true },
          { text: "Motor de recomendaciones de producto basado en semantic search", included: true },
          { text: "Algorithmic Schema Augmentation: contenido SEO generado por IA a escala", included: true },
          { text: "Custom AI model fine-tuning con tus datos históricos", included: true },
          { text: "Soporte prioritario por chat y videollamada (respuesta <4h)", included: true },
          { text: "Sesión mensual de estrategia con especialista (60 min)", included: true },
          { text: "Acceso anticipado a nuevos motores IA", included: true },
          { text: "Account manager dedicado", included: false },
        ],
        cta: { label: "Solicitar demo personalizada →", href: "https://comic-crafter.myshopify.com/cart/57686492709209:1", style: "gold" },
      },
      {
        id: "plan-enterprise", name: "Enterprise Omnicore", price: "Personalizado", currency: "€", period: "desde €2,497/mes · setup incluido",
        featured: false, badge: "ENTERPRISE",
        features: [
          { text: "Todo lo incluido en Performance Lab +", included: true },
          { text: "Account manager dedicado con SLA contractual", included: true },
          { text: "Custom AI development: motores IA diseñados para tus casos de uso", included: true },
          { text: "Infraestructura dedicada (no multi-tenant)", included: true },
          { text: "API privada con webhooks personalizados", included: true },
          { text: "Integración con ERPs, PIMs y custom stacks", included: true },
          { text: "White-label completo (remoción de branding ShopyBrain)", included: true },
          { text: "SSO enterprise (SAML, OAuth, AD integration)", included: true },
          { text: "Compliance GDPR, SOC2, ISO 27001 certificado", included: true },
          { text: "Soporte 24/7 con respuesta garantizada <1h (critical issues)", included: true },
          { text: "Sesiones estratégicas semanales + quarterly business reviews", included: true },
          { text: "Training continuo del equipo (onboarding ilimitado)", included: true },
          { text: "Desarrollo de features custom bajo demanda", included: true },
        ],
        cta: { label: "Hablar con Enterprise →", href: "#fp-contact", style: "ghost" },
      },
    ],
  },
  testimonials: {
    pill: "Clientes",
    headline: "Lo que dicen los que ya lo usan",
    headlineHighlight: "los que ya lo usan",
    items: [
      { id: "t1", stars: 5, text: "En 3 semanas pasamos de una tasa de conversión del 1.8% al 4.1%. Las imágenes generadas por IA parecen de sesión fotográfica profesional. Mis clientes no pueden creer el antes y el después.", metric: "↑ +128% conversión en 3 semanas", author: "Miguel Rodríguez", role: "Agencia eCommerce · Madrid", initials: "MR", avatarColor: "rgba(200,168,75,0.1)", avatarTextColor: "#e6c668", avatarUrl: null as string | null },
      { id: "t2", stars: 5, text: "El motor de pricing me descubrió que tenía 6 productos vendiendo por debajo del break-even. Después de aplicar el COGS real y la estrategia de precios, el margen medio subió del 28% al 54%.", metric: "↑ +26pts de margen medio", author: "Ana López", role: "Tienda de moda · Barcelona", initials: "AL", avatarColor: "rgba(45,212,159,0.1)", avatarTextColor: "#2dd49f", avatarUrl: null as string | null },
      { id: "t3", stars: 5, text: "Gestiono 11 tiendas para clientes. Antes me llevaba días actualizar imágenes y precios manualmente. Ahora el sistema lo hace solo y yo solo superviso. Me ha triplicado la capacidad de la agencia.", metric: "↑ 3× capacidad de la agencia", author: "Jordi Martínez", role: "Agencia Shopify · Valencia", initials: "JM", avatarColor: "rgba(74,158,221,0.1)", avatarTextColor: "#4a9edd", avatarUrl: null as string | null },
    ],
  },
  calculator: {
    pill: "Calcula tu precio",
    headline: "¿Cuánto cuesta optimizar tu tienda?",
    headlineHighlight: "optimizar tu tienda",
    subheadline: "Selecciona los servicios que necesitas y obtén un precio estimado al instante.",
    disclaimer: "* Los precios son orientativos y pueden variar según las necesidades específicas de cada cliente y el nivel de personalización requerido.",
    resultLabel: "Precio estimado",
    oneTimeLabel: "Pago único",
    recurringLabel: "Suscripción mensual",
    ctaLabel: "Solicitar presupuesto personalizado →",
    emptyLabel: "Selecciona al menos un servicio para ver el precio",
    oneTimeServices: [
      { id: "calc-audit", name: "Auditoría Completa", description: "Análisis de todos tus productos + SEO + COGS + plan de acción", price: 197, icon: "📊" },
      { id: "calc-redesign", name: "Rediseño IA (hasta 30 productos)", description: "Títulos, descripciones y SEO optimizados con IA profesional", price: 147, icon: "✏️" },
      { id: "calc-images", name: "Pack 30 Imágenes IA", description: "Fotos profesionales de producto generadas con IA (Hero, Lifestyle, Detalle)", price: 89, icon: "🖼️" },
      { id: "calc-pricing-report", name: "Informe de Precios y Márgenes", description: "COGS real, márgenes, precios competitivos, estrategia de pricing", price: 97, icon: "💰" },
      { id: "calc-seo", name: "Optimización SEO Completa", description: "Meta tags, keywords, Schema JSON-LD, plan de contenido", price: 147, icon: "🔍" },
      { id: "calc-competitor", name: "Informe de Competidores", description: "Análisis detallado de tu competencia directa con estrategia", price: 97, icon: "🎯" },
      { id: "calc-supplier", name: "Investigación de Proveedores", description: "Búsqueda, comparativa y negociación con proveedores", price: 97, icon: "🏭" },
      { id: "calc-email-setup", name: "Setup Email Marketing", description: "Plantillas profesionales, flujos automatizados y configuración", price: 197, icon: "📧" },
      { id: "calc-projection", name: "Informe de Proyección de Ventas", description: "Forecast a 3-6 meses con escenarios y recomendaciones", price: 127, icon: "📈" },
    ],
    recurringServices: [
      { id: "calc-maintenance", name: "Mantenimiento Básico", description: "Monitorización, actualizaciones mensuales y soporte por email", price: 49, period: "/mes", icon: "🛠️" },
      { id: "calc-active", name: "Gestión Activa", description: "Optimización continua + informes semanales + A/B testing", price: 149, period: "/mes", icon: "🚀" },
      { id: "calc-premium", name: "Premium Ilimitado", description: "Todo incluido + prioridad + SLA 99.9% + account manager", price: 399, period: "/mes", icon: "👑" },
    ],
  },
  results: {
    pill: "Resultados probados",
    headline: "Números que hablan solos",
    headlineHighlight: "hablan solos",
    stats: [
      { prefix: "+", num: "234", suffix: "%", label: "Incremento medio en conversión", color: "var(--l-jade)" },
      { prefix: "€", num: "8400", suffix: "/mes", label: "Ingresos adicionales promedio", color: "var(--l-gold)" },
      { prefix: "", num: "99", suffix: ".9%", label: "Uptime garantizado de la plataforma", color: "var(--l-sky)" },
      { prefix: "", num: "6", suffix: " motores", label: "Optimizando tu tienda 24/7", color: "#8b5cf6" },
    ],
    techBadges: [
      { icon: "🛍️", label: "Shopify API" },
      { icon: "🤖", label: "Claude AI" },
      { icon: "🎨", label: "Replicate" },
      { icon: "🔍", label: "GSC" },
      { icon: "📧", label: "Klaviyo" },
      { icon: "🔐", label: "AES-256" },
      { icon: "⚡", label: "Shopify Flow" },
    ],
  },
  contact: {
    pill: "Trabaja con nosotros",
    headline: "Cuéntanos sobre tu negocio.",
    headlineHighlight: "Te contactamos en menos de 24h.",
    subheadline: "Necesitamos conocer tu tienda para personalizar cada motor de IA a tu nicho, ticket medio y modelo de negocio.",
    buttonLabel: "Solicitar acceso gratuito →",
    successTitle: "¡Solicitud recibida!",
    successText: "Nuestra IA ya está analizando tu negocio, mercado, competencia y SEO.",
    successSubtext: "Te contactaremos con un informe detallado en menos de 24h. Revisa también tu carpeta de spam.",
    finePrint: "Sin spam. Solo te contactamos para hablar de tu proyecto.",
    labels: {
      name: "Nombre completo *",
      email: "Email de contacto *",
      phone: "Teléfono",
      storeUrl: "URL de tu tienda Shopify",
      niche: "Nicho / tipo de productos",
      revenue: "Facturación mensual aprox.",
      message: "¿Qué te gustaría mejorar?",
    },
    placeholders: {
      name: "Tu nombre y apellidos",
      email: "tu@email.com",
      phone: "+34 600 000 000",
      storeUrl: "mitienda.myshopify.com",
      niche: "Selecciona tu nicho",
      revenue: "Selecciona rango",
      message: "Cuéntanos sobre tu tienda, tus retos actuales y qué te gustaría conseguir...",
    },
    nicheOptions: ["Moda y ropa", "Electrónica y gadgets", "Hogar y decoración", "Belleza y cosmética", "Deporte y fitness", "Alimentación y gourmet", "Arte y coleccionismo", "Mascotas", "Joyería y accesorios", "Otro"],
    revenueOptions: ["Menos de €1.000", "€1.000 – €5.000", "€5.000 – €15.000", "€15.000 – €50.000", "Más de €50.000"],
    socialLabel: "Redes sociales / Instagram",
    socialPlaceholder: "@tutienda o https://instagram.com/tutienda",
    servicesLabel: "Servicios que necesitas",
    serviceOptions: ["SEO y contenido", "Rediseño de producto", "Imágenes IA", "Pricing y márgenes", "Email marketing", "A/B Testing", "Auditoría completa"],
  },
  cta: {
    pill: "Empieza hoy",
    headline: "Tu tienda merece\nmás que esto.",
    headlineHighlight: "más que esto.",
    subheadline: "14 días gratis. Sin tarjeta. Cancela cuando quieras.\nSetup completo en menos de 5 minutos.",
    placeholder: "tu@agencia.com",
    buttonLabel: "Empezar →",
    finePrint: "Al registrarte aceptas nuestros Términos de Servicio y Política de Privacidad",
  },
  howCards: [
    { icon: "✓", title: "Auditoría completada", sub: "234 productos analizados · 12 acciones urgentes", barPercent: "88" },
    { icon: "🎨", title: "Imágenes generándose", sub: "flux-1.1-pro · 48/234 productos", barPercent: "21" },
    { icon: "⚗️", title: "A/B Test activo", sub: "Bomber Hero · 342 visitas · 67% confianza", barPercent: "67" },
  ],
  howImpact: { icon: "💰", title: "Impacto estimado", sub: "+€8,400/mes proyectados este mes" },
  sectionNav: ["Inicio", "Motores", "Demo", "Resultados", "Precios", "Calculadora", "Contactar"],
  adminBackLabel: "← Volver al panel",
  apkLabels: {
    idle: "📱 Descargar App Android",
    checking: "Verificando...",
    downloading: "⬇ Descargando...",
    building: "🔜 Disponible próximamente",
    unavailable: "No disponible",
  },
  errorMessages: {
    sendFail: "Error al enviar",
    unexpected: "Error inesperado. Inténtalo de nuevo.",
  },
  heroDemoTitles: {
    storeHealth: "Salud de tiendas",
    recentActivity: "Actividad reciente",
  },
  adminPanel: {
    sidebarLabels: {
      yourStores: "Tus Tiendas",
      noStores: "Sin tiendas aún",
      newStore: "Nueva tienda",
      admin: "Administración",
      config: "Configuración",
      madeBy: "Hecho por",
    },
    header: {
      offline: "Sin conexión — tus cambios se guardan localmente",
      search: "Búsqueda",
      active: "Activo",
    },
    user: {
      unlimited: "Ilimitados",
      adminRole: "Administrador",
    },
    tooltips: {
      lightMode: "Modo claro",
      darkMode: "Modo oscuro",
      activateLight: "Activar modo claro",
      activateDark: "Activar modo oscuro",
      logout: "Cerrar sesión",
      mainNav: "Navegación principal",
      shopify: "Tienda Shopify",
      accountSettings: "Ajustes de cuenta",
      notifications: "Notificaciones",
      openNotifications: "Abrir notificaciones",
      closeMenu: "Cerrar menú",
      openMenu: "Abrir menú",
    },
    notifications: {
      title: "Notificaciones",
      empty: "Sin notificaciones nuevas",
      emptyHint: "Las alertas de stock, competidores y logros aparecerán aquí",
    },
  },
  clientPanel: {
    navItems: [
      { href: "/client", label: "Dashboard", icon: "📊" },
      { href: "/client/products", label: "Productos", icon: "📦" },
      { href: "/client/approvals", label: "Aprobaciones", icon: "✅" },
      { href: "/client/messages", label: "Mensajes", icon: "💬" },
      { href: "/client/reports", label: "Reportes", icon: "📈" },
    ],
    sidebar: {
      yourStore: "Tu Tienda",
      defaultName: "Cliente",
      storePanel: "Panel de tienda",
      managedBy: "Gestionado por",
      agency: "tu agencia",
      enginesActive: "6 motores IA activos",
      navigation: "Navegación",
      aiOptimizations: "Optimizaciones IA",
    },
    topbar: "Tu agencia trabaja para ti 24/7",
    tooltips: {
      logout: "Cerrar sesión",
      notifications: "Notificaciones",
    },
    statusOnline: "Online",
    logoBadge: "CLIENT",
  },
  adminNav: {
    modules: [
      { id: "audit", label: "Auditoría", icon: "📊" },
      { id: "redesign", label: "Rediseño IA", icon: "✏️" },
      { id: "images", label: "Imágenes", icon: "🖼" },
      { id: "consistency", label: "Consistencia", icon: "🎨" },
      { id: "ab-testing", label: "A/B Testing", icon: "📈" },
      { id: "pricing", label: "Pricing", icon: "💰" },
      { id: "seo", label: "SEO Engine", icon: "🔍" },
      { id: "vault", label: "Repositorio", icon: "🗄️" },
      { id: "exports", label: "Exportar", icon: "📥" },
    ],
    shopybrain: [
      { label: "Shopy Brain", icon: "🧠", href: "/admin/shopybrain" },
      { label: "Centro de Comando", icon: "⚡", href: "/admin/command-center" },
      { label: "Memorias", icon: "💾", href: "/admin/shopybrain/memories" },
      { label: "Knowledge Domains", icon: "🔬", href: "/admin/shopybrain/insights" },
      { label: "Sesiones Estudio", icon: "📚", href: "/admin/shopybrain/study" },
      { label: "Mi Pricing CFO", icon: "💰", href: "/admin/my-pricing" },
      { label: "Email Marketing", icon: "📧", href: "/admin/emails" },
      { label: "Flujos de Email", icon: "🔄", href: "/admin/email-flows" },
      { label: "Editor Landing", icon: "✏️", href: "/admin/cms" },
      { label: "Ver Landing", icon: "🌐", href: "/landing" },
    ],
    admin: [
      { label: "CRM Clientes", icon: "👥", href: "/admin/clients" },
      { label: "Productos Global", icon: "📦", href: "/admin/products" },
      { label: "A/B Tests Global", icon: "📈", href: "/admin/abtests" },
      { label: "Automaciones", icon: "⚡", href: "/admin/automations" },
      { label: "Revenue & CRM", icon: "💰", href: "/admin/revenue" },
      { label: "Revenue Intel", icon: "📊", href: "/admin/intelligence" },
      { label: "Gemini Research", icon: "🔬", href: "/admin/gemini-intel" },
      { label: "M7 Inventario", icon: "🗄", href: "/admin/inventory" },
      { label: "Competitor Intel", icon: "🎯", href: "/admin/competitors" },
      { label: "Predicciones ML", icon: "🔮", href: "/admin/forecast" },
      { label: "Logros", icon: "🏆", href: "/admin/achievements" },
      { label: "Plan 30-60-90", icon: "🗺", href: "/admin/roadmap" },
      { label: "APK Android", icon: "📱", href: "/admin/apk" },
      { label: "Tienda / Store", icon: "🛒", href: "/tienda" },
      { label: "System Health", icon: "🖥", href: "/admin/system" },
    ],
  },
  footer: {
    tagline: "Shopy Crafter — La plataforma de agencia Shopify con OmniCore Brain. Powered by Claude AI + Gemini + Replicate.",
    columns: [
      { title: "Producto", links: [{ label: "Motores IA", href: "#features" }, { label: "Precios", href: "#pricing" }, { label: "Changelog", href: "#" }, { label: "Documentación", href: "#" }, { label: "API Reference", href: "#" }] },
      { title: "Empresa", links: [{ label: "Sobre nosotros", href: "#" }, { label: "Blog", href: "#" }, { label: "Casos de éxito", href: "#" }, { label: "Afiliados", href: "#" }, { label: "Contacto", href: "#" }] },
      { title: "Legal", links: [{ label: "Privacidad", href: "#" }, { label: "Términos", href: "#" }, { label: "Cookies", href: "#" }, { label: "RGPD", href: "#" }, { label: "Seguridad", href: "#" }] },
    ],
    copyright: "© 2026 Shopy Crafter · OmniCore Agency Platform. Todos los derechos reservados.",
    badges: ["RGPD", "AES-256", "SOC2"],
  },
};
