export const DEFAULT_CMS_CONTENT = {
  meta: {
    lastUpdated: new Date().toISOString(),
    updatedBy: "system",
    version: 1,
  },
  site: {
    name: "ShopifyAI Pro",
    tagline: "La agencia Shopify del futuro",
    logo: { type: "emoji", value: "⚡", imageUrl: null },
    favicon: "⚡",
    primaryColor: "#c8a84b",
    accentColor: "#2dd49f",
    font_heading: "Instrument Serif",
    font_body: "Geist",
  },
  nav: {
    links: [
      { id: "nav-1", label: "Motores", href: "#features" },
      { id: "nav-2", label: "Cómo funciona", href: "#how" },
      { id: "nav-3", label: "Precios", href: "#pricing" },
      { id: "nav-4", label: "Clientes", href: "#testimonials" },
    ],
    ctaPrimary: { label: "Solicitar acceso →", href: "#cta" },
    ctaSecondary: { label: "Iniciar sesión", href: "/login" },
  },
  hero: {
    pill: { text: "Nuevo · 6 motores de IA activos · Versión 2.0", visible: true },
    headline: "La agencia Shopify\nque trabaja 24/7\npor ti",
    headlineHighlight: "24/7",
    subheadline: "ShopifyAI Pro gestiona, optimiza y potencia tiendas Shopify de manera completamente autónoma. Imágenes profesionales, pricing inteligente, SEO técnico y tests A/B — todo en piloto automático.",
    ctaPrimary: { label: "Empezar gratis 14 días →", href: "#cta" },
    ctaSecondary: { label: "▶ Ver en acción", href: "#how" },
    trustItems: ["Sin tarjeta de crédito", "Setup en 5 minutos", "Cancela cuando quieras", "RGPD compliant"],
  },
  features: {
    pill: "Motores IA",
    headline: "Seis motores. Una sola plataforma.",
    subheadline: "Cada motor trabaja de forma autónoma y coordinada para potenciar todos los aspectos de tu tienda.",
    items: [
      { id: "feat-1", num: "M01", icon: "🖼️", iconBg: "rgba(45,212,159,0.1)", title: "Generación de Imágenes", description: "8 tipos de imagen profesional por producto usando Replicate flux-1.1-pro. Hero, Lifestyle, Detalle, Packaging, UGC, Escala, Bundle e Infografía SVG generada directamente.", tags: ["flux-1.1-pro", "recraft-v3", "~€0.25/prod"] },
      { id: "feat-2", num: "M02", icon: "🎨", iconBg: "rgba(200,168,75,0.1)", title: "Consistencia Visual", description: "Extrae el ADN visual de tu tienda y aplica StyleLock a todas las generaciones. Garantiza coherencia de marca en cada imagen, colección y set fotográfico.", tags: ["StyleLock", "Visual DNA", "Set Mode"] },
      { id: "feat-3", num: "M03", icon: "⚗️", iconBg: "rgba(74,158,221,0.1)", title: "A/B Testing Automático", description: "Pixel tracker propio, z-test estadístico al 95% de confianza, declaración automática de ganador y generación inmediata del siguiente challenger.", tags: ["Z-test 95%", "Pixel tracker", "Auto-winner"] },
      { id: "feat-4", num: "M04", icon: "⚡", iconBg: "rgba(200,168,75,0.08)", title: "Auto-Pilot 24/7", description: "Webhook trigger en cada nuevo producto. Auditoría inmediata, generación automática de Hero y Lifestyle, test A/B creado y activo sin intervención manual.", tags: ["Webhook", "Cron jobs", "Informe mensual"] },
      { id: "feat-5", num: "M05", icon: "📊", iconBg: "rgba(200,168,75,0.1)", title: "Pricing Financiero", description: "Motor COGS completo, análisis de competencia en tiempo real, economista IA con pricing psicológico, dashboard P&L y alertas de margen.", tags: ["COGS Engine", "Competencia", "P&L en vivo"] },
      { id: "feat-6", num: "M06", icon: "🔍", iconBg: "rgba(45,212,159,0.08)", title: "SEO Técnico", description: "Schema JSON-LD completo, meta tags optimizados por Claude, sitemap dinámico, Core Web Vitals, estrategia de keywords y generación automática de blog posts.", tags: ["Schema JSON-LD", "CWV", "Blog IA"] },
    ],
  },
  stats: [
    { id: "s1", num: "3.4×", label: "Más conversión con 5+ imágenes" },
    { id: "s2", num: "€0.25", label: "Coste por producto optimizado" },
    { id: "s3", num: "95%", label: "Confianza estadística en A/B tests" },
    { id: "s4", num: "24/7", label: "Auto-pilot completamente autónomo" },
  ],
  how: {
    pill: "Cómo funciona",
    headline: "De zero a tienda optimizada\nen minutos",
    headlineHighlight: "tienda optimizada",
    steps: [
      { num: "01", title: "Conecta tu tienda Shopify", desc: "Introduce tu dominio y Access Token. La plataforma se conecta al instante con la API de Shopify y escanea todo tu catálogo, configuración y métricas actuales." },
      { num: "02", title: "La IA audita cada producto", desc: "Claude analiza título, descripción, precio, imágenes y SEO de cada producto. Asigna una nota A–F y genera una lista priorizada de mejoras con impacto estimado en revenue." },
      { num: "03", title: "Activa los 6 motores", desc: "Con un clic, los 6 motores se ponen en marcha: generan imágenes, optimizan precios, aplican SEO técnico, inician tests A/B y configuran automatizaciones." },
      { num: "04", title: "Resultados compuestos cada semana", desc: "El sistema mejora solo. Cada test que termina genera el siguiente. Cada precio optimizado se monitoriza. Cada imagen que convierte se convierte en el nuevo estándar." },
    ],
  },
  pricing: {
    pill: "Precios",
    headline: "Transparente. Sin sorpresas.",
    subheadline: "Retainer mensual + setup único. Sin permanencia. Cancela cuando quieras.",
    plans: [
      {
        id: "plan-starter", name: "Starter", price: "49", currency: "€", period: "por mes · + €297 setup único",
        featured: false, badge: null,
        features: [
          { text: "Hasta 3 tiendas Shopify", included: true },
          { text: "Auditoría automática completa", included: true },
          { text: "M1 Generación de imágenes (100/mes)", included: true },
          { text: "M5 Pricing COGS básico", included: true },
          { text: "M6 SEO técnico", included: true },
          { text: "OmniCore Brain", included: false },
          { text: "A/B Testing automático", included: false },
          { text: "Portal cliente + Reportes PDF", included: false },
        ],
        cta: { label: "Solicitar Starter →", style: "ghost" },
      },
      {
        id: "plan-pro", name: "Agency Pro", price: "149", currency: "€", period: "por mes · + €597 setup único",
        featured: true, badge: "MÁS POPULAR",
        features: [
          { text: "Hasta 15 tiendas Shopify", included: true },
          { text: "Los 6 motores completos (500 imgs/mes)", included: true },
          { text: "OmniCore Brain — memoria acumulada", included: true },
          { text: "A/B Testing con pixel propio", included: true },
          { text: "Portal cliente read-only", included: true },
          { text: "Reportes PDF con tu branding", included: true },
          { text: "Auto-pilot 24/7 + aprobaciones", included: true },
          { text: "Soporte prioritario", included: true },
        ],
        cta: { label: "Solicitar Agency Pro →", style: "gold" },
      },
      {
        id: "plan-ent", name: "Enterprise", price: "399", currency: "€", period: "por mes · + €1.497 setup único",
        featured: false, badge: null,
        features: [
          { text: "Tiendas ilimitadas", included: true },
          { text: "Todo de Agency Pro (imgs ilimitadas)", included: true },
          { text: "OmniCore Brain Premium + tuning manual", included: true },
          { text: "White-label completo", included: true },
          { text: "API acceso completo", included: true },
          { text: "Onboarding + SLA 99.9% uptime", included: true },
          { text: "Slack dedicado + account manager", included: true },
          { text: "Facturación anual con descuento", included: true },
        ],
        cta: { label: "Hablar con Joan →", style: "ghost" },
      },
      {
        id: "plan-oneshot", name: "One-Shot Audit", price: "197", currency: "€", period: "pago único · sin permanencia",
        featured: false, badge: "SIN RETAINER",
        features: [
          { text: "Auditoría completa de 1 tienda", included: true },
          { text: "Rediseño IA de hasta 30 productos", included: true },
          { text: "Pack 30 imágenes profesionales IA", included: true },
          { text: "Informe SEO + plan de acción", included: true },
          { text: "Análisis COGS + pricing recomendado", included: true },
          { text: "Entrega en 48h · Informe PDF premium", included: true },
          { text: "Sin retainer mensual", included: true },
          { text: "Soporte post-entrega 15 días", included: false },
        ],
        cta: { label: "Solicitar One-Shot →", style: "ghost" },
      },
    ],
  },
  testimonials: {
    pill: "Clientes",
    headline: "Lo que dicen los que ya lo usan",
    headlineHighlight: "los que ya lo usan",
    items: [
      { id: "t1", stars: 5, text: "En 3 semanas pasamos de una tasa de conversión del 1.8% al 4.1%. Las imágenes generadas por IA parecen de sesión fotográfica profesional. Mis clientes no pueden creer el antes y el después.", metric: "↑ +128% conversión en 3 semanas", author: "Miguel Rodríguez", role: "Agencia eCommerce · Madrid", initials: "MR", avatarColor: "rgba(200,168,75,0.1)", avatarTextColor: "#e6c668" },
      { id: "t2", stars: 5, text: "El motor de pricing me descubrió que tenía 6 productos vendiendo por debajo del break-even. Después de aplicar el COGS real y la estrategia de precios, el margen medio subió del 28% al 54%.", metric: "↑ +26pts de margen medio", author: "Ana López", role: "Tienda de moda · Barcelona", initials: "AL", avatarColor: "rgba(45,212,159,0.1)", avatarTextColor: "#2dd49f" },
      { id: "t3", stars: 5, text: "Gestiono 11 tiendas para clientes. Antes me llevaba días actualizar imágenes y precios manualmente. Ahora el sistema lo hace solo y yo solo superviso. Me ha triplicado la capacidad de la agencia.", metric: "↑ 3× capacidad de la agencia", author: "Jordi Martínez", role: "Agencia Shopify · Valencia", initials: "JM", avatarColor: "rgba(74,158,221,0.1)", avatarTextColor: "#4a9edd" },
    ],
  },
  cta: {
    pill: "Empieza hoy",
    headline: "Tu tienda merece\nmás que esto.",
    headlineHighlight: "más que esto.",
    subheadline: "14 días gratis. Sin tarjeta. Cancela cuando quieras.\nSetup completo en menos de 5 minutos.",
    placeholder: "tu@agencia.com",
    buttonLabel: "Empezar →",
    finePrint: "Al registrarte aceptas nuestros Términos de Servicio y Política de Privacidad",
  },
  footer: {
    tagline: "La plataforma de gestión y optimización de tiendas Shopify más completa. Powered by Claude AI y Replicate.",
    columns: [
      { title: "Producto", links: [{ label: "Motores IA", href: "#features" }, { label: "Precios", href: "#pricing" }, { label: "Changelog", href: "#" }, { label: "Documentación", href: "#" }, { label: "API Reference", href: "#" }] },
      { title: "Empresa", links: [{ label: "Sobre nosotros", href: "#" }, { label: "Blog", href: "#" }, { label: "Casos de éxito", href: "#" }, { label: "Afiliados", href: "#" }, { label: "Contacto", href: "#" }] },
      { title: "Legal", links: [{ label: "Privacidad", href: "#" }, { label: "Términos", href: "#" }, { label: "Cookies", href: "#" }, { label: "RGPD", href: "#" }, { label: "Seguridad", href: "#" }] },
    ],
    copyright: "© 2025 ShopifyAI Pro. Todos los derechos reservados.",
    badges: ["RGPD", "AES-256", "SOC2"],
  },
};
