/**
 * Plugins Catalog — 261 Workflow Plugins
 * Cada plugin es una unidad ejecutable de automatización/mejora.
 */

export interface Plugin {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  tags: string[];
  action: "prompt" | "transform" | "webhook" | "integration" | "analysis" | "generator";
  endpoint?: string;
  promptTemplate?: string;
  isPremium: boolean;
  isNew?: boolean;
  usageCount?: number;
}

export const PLUGINS_CATALOG: Plugin[] = [

  // ── SEO (30) ─────────────────────────────────────────────────────────────
  { id: "seo-title-gen",        name: "Title Tag Generator",         category: "SEO",        icon: "🏷️", description: "Genera títulos SEO perfectos (50-60 chars) con keyword y power words.",             action: "prompt",      tags: ["seo","title","keyword"],          isPremium: false },
  { id: "seo-meta-gen",         name: "Meta Description AI",         category: "SEO",        icon: "📋", description: "Meta descriptions de 155 chars con CTA y keyword natural.",                          action: "prompt",      tags: ["seo","meta","ctr"],               isPremium: false },
  { id: "seo-schema-product",   name: "Product Schema Markup",       category: "SEO",        icon: "📦", description: "Schema JSON-LD Product con offers, rating y availability.",                          action: "generator",   tags: ["schema","json-ld","product"],     isPremium: false },
  { id: "seo-schema-faq",       name: "FAQ Schema Builder",          category: "SEO",        icon: "❓", description: "Schema JSON-LD FAQPage con pares Q&A para rich snippets.",                           action: "generator",   tags: ["schema","faq","rich-snippet"],    isPremium: false },
  { id: "seo-schema-org",       name: "Organization Schema",         category: "SEO",        icon: "🏢", description: "Schema Organization con sitelinks, logo y contacto.",                               action: "generator",   tags: ["schema","organization"],         isPremium: false },
  { id: "seo-schema-breadcrumb",name: "Breadcrumb Schema",           category: "SEO",        icon: "🔗", description: "Schema BreadcrumbList para navegación en SERPs.",                                   action: "generator",   tags: ["schema","breadcrumb","nav"],     isPremium: false },
  { id: "seo-schema-review",    name: "Review Schema",               category: "SEO",        icon: "⭐", description: "Schema AggregateRating y Review para estrellas en SERP.",                            action: "generator",   tags: ["schema","review","stars"],       isPremium: false },
  { id: "seo-schema-local",     name: "LocalBusiness Schema",        category: "SEO",        icon: "📍", description: "Schema LocalBusiness con horarios, dirección y teléfono.",                          action: "generator",   tags: ["schema","local","business"],     isPremium: false },
  { id: "seo-schema-article",   name: "Article Schema",              category: "SEO",        icon: "📰", description: "Schema Article/NewsArticle para blogs y noticias.",                                  action: "generator",   tags: ["schema","article","blog"],       isPremium: false },
  { id: "seo-schema-howto",     name: "HowTo Schema",                category: "SEO",        icon: "📋", description: "Schema HowTo con pasos para featured snippets de receta/tutorial.",                 action: "generator",   tags: ["schema","howto","tutorial"],     isPremium: false },
  { id: "seo-robots-gen",       name: "Robots.txt Generator",        category: "SEO",        icon: "🤖", description: "Genera robots.txt optimizado para tu plataforma.",                                   action: "generator",   tags: ["seo","robots","crawl"],          isPremium: false },
  { id: "seo-sitemap-xml",      name: "XML Sitemap Builder",         category: "SEO",        icon: "🗺️", description: "Sitemap XML con prioridades, changefreq y imágenes.",                               action: "generator",   tags: ["seo","sitemap","xml"],           isPremium: false },
  { id: "seo-redirect-map",     name: "Redirect Map Generator",      category: "SEO",        icon: "➡️", description: "Mapa de redirects 301/302 para migraciones de URL.",                                action: "generator",   tags: ["seo","redirects","migration"],   isPremium: true  },
  { id: "seo-canonical-audit",  name: "Canonical Tag Auditor",       category: "SEO",        icon: "🔍", description: "Audita y corrige tags canónicas duplicadas.",                                        action: "analysis",    tags: ["seo","canonical","duplicate"],   isPremium: false },
  { id: "seo-page-speed",       name: "Page Speed Analyzer",         category: "SEO",        icon: "⚡", description: "Analiza y prioriza mejoras de Core Web Vitals.",                                    action: "analysis",    tags: ["seo","speed","cwv"],              isPremium: false },
  { id: "seo-keyword-density",  name: "Keyword Density Checker",     category: "SEO",        icon: "📊", description: "Analiza densidad de keyword en texto y sugiere ajustes.",                           action: "analysis",    tags: ["seo","keyword","density"],       isPremium: false },
  { id: "seo-internal-link",    name: "Internal Link Suggester",     category: "SEO",        icon: "🔗", description: "Sugiere internal links basados en contexto del contenido.",                          action: "analysis",    tags: ["seo","linking","architecture"],  isPremium: true  },
  { id: "seo-image-alt",        name: "Image Alt Text Generator",    category: "SEO",        icon: "🖼️", description: "Genera alt text SEO para imágenes de producto a escala.",                           action: "prompt",      tags: ["seo","alt","images"],            isPremium: false },
  { id: "seo-url-optimizer",    name: "URL Slug Optimizer",          category: "SEO",        icon: "🌐", description: "Optimiza slugs de URL: minúsculas, guiones, sin stopwords.",                        action: "transform",   tags: ["seo","url","slug"],              isPremium: false },
  { id: "seo-heading-analyzer", name: "Heading Hierarchy Analyzer",  category: "SEO",        icon: "📑", description: "Analiza y corrige jerarquía H1-H6 para SEO.",                                       action: "analysis",    tags: ["seo","headings","structure"],    isPremium: false },
  { id: "seo-serp-preview",     name: "SERP Preview Generator",      category: "SEO",        icon: "🔍", description: "Vista previa de cómo aparece en Google desktop y mobile.",                          action: "generator",   tags: ["seo","serp","preview"],          isPremium: false },
  { id: "seo-hreflang",         name: "Hreflang Tag Generator",      category: "SEO",        icon: "🌍", description: "Genera hreflang tags para SEO internacional multi-idioma.",                         action: "generator",   tags: ["seo","hreflang","international"],isPremium: true  },
  { id: "seo-paginated",        name: "Pagination SEO Handler",      category: "SEO",        icon: "📄", description: "Gestiona SEO de páginas paginadas con rel=next/prev.",                              action: "generator",   tags: ["seo","pagination","ecommerce"],  isPremium: false },
  { id: "seo-faceted-nav",      name: "Faceted Navigation Fix",      category: "SEO",        icon: "🗂️", description: "Resuelve crawl budget de navegación facetada en ecommerce.",                        action: "analysis",    tags: ["seo","faceted","ecommerce"],     isPremium: true  },
  { id: "seo-duplicate-content",name: "Duplicate Content Detector",  category: "SEO",        icon: "📋", description: "Detecta contenido duplicado y sugiere canonicales.",                                action: "analysis",    tags: ["seo","duplicate","content"],     isPremium: false },
  { id: "seo-local-citations",  name: "Local Citations Builder",     category: "SEO",        icon: "📍", description: "Lista de directorios locales para citas NAP consistentes.",                         action: "generator",   tags: ["seo","local","citations"],       isPremium: false },
  { id: "seo-rich-snippet",     name: "Rich Snippet Tester",         category: "SEO",        icon: "✅", description: "Verifica markup de datos estructurados y valida.",                                  action: "analysis",    tags: ["seo","rich-snippet","validate"], isPremium: false },
  { id: "seo-competitor-gaps",  name: "Competitor Keyword Gaps",     category: "SEO",        icon: "🎯", description: "Identifica keywords donde ranquea la competencia y tú no.",                         action: "analysis",    tags: ["seo","competitor","gaps"],       isPremium: true  },
  { id: "seo-voice-search",     name: "Voice Search Optimizer",      category: "SEO",        icon: "🎙️", description: "Optimiza contenido para búsquedas conversacionales de voz.",                       action: "prompt",      tags: ["seo","voice","conversational"],  isPremium: false },
  { id: "seo-featured-snippet", name: "Featured Snippet Optimizer",  category: "SEO",        icon: "🌟", description: "Formatea respuestas para capturar featured snippets.",                              action: "prompt",      tags: ["seo","snippet","position-zero"], isPremium: false },

  // ── CONTENT (30) ──────────────────────────────────────────────────────────
  { id: "content-product-desc", name: "Product Description AI",      category: "Content",    icon: "📝", description: "Descripciones de producto SEO con AIDA/PAS para alta conversión.",                  action: "prompt",      tags: ["content","product","copywriting"],isPremium: false },
  { id: "content-blog-gen",     name: "Blog Post Generator",         category: "Content",    icon: "✍️", description: "Artículos de blog 1200+ palabras con estructura SEO y CTA.",                       action: "prompt",      tags: ["content","blog","seo"],          isPremium: false },
  { id: "content-faq-gen",      name: "FAQ Content Builder",         category: "Content",    icon: "❓", description: "15 FAQs reales por producto con schema markup incluido.",                            action: "prompt",      tags: ["content","faq","schema"],        isPremium: false },
  { id: "content-title-variants",name: "Headline Variants A/B",      category: "Content",    icon: "💡", description: "10 variantes de headline para A/B testing en landing pages.",                       action: "prompt",      tags: ["content","headline","ab-test"],  isPremium: false },
  { id: "content-usp-gen",      name: "USP Generator",               category: "Content",    icon: "⭐", description: "10 propuestas de valor únicas con diferentes ángulos persuasivos.",                  action: "prompt",      tags: ["content","usp","value-prop"],    isPremium: false },
  { id: "content-brand-story",  name: "Brand Story Writer",          category: "Content",    icon: "📖", description: "Narrativa de marca auténtica con storytelling y arco emocional.",                   action: "prompt",      tags: ["content","brand","narrative"],   isPremium: false },
  { id: "content-case-study",   name: "Case Study Builder",          category: "Content",    icon: "🏆", description: "Case study con problema-solución-resultados y métricas.",                            action: "prompt",      tags: ["content","case-study","b2b"],    isPremium: false },
  { id: "content-press-release",name: "Press Release Generator",     category: "Content",    icon: "📰", description: "Nota de prensa en formato AP con quotes y boilerplate.",                            action: "prompt",      tags: ["content","pr","media"],          isPremium: false },
  { id: "content-comparison",   name: "Comparison Page Writer",      category: "Content",    icon: "⚖️", description: "Página vs competidor con tabla y argumentos de venta.",                             action: "prompt",      tags: ["content","comparison","seo"],    isPremium: false },
  { id: "content-size-guide",   name: "Size Guide Generator",        category: "Content",    icon: "📏", description: "Guía de tallas con conversiones EU/UK/US y instrucciones.",                         action: "prompt",      tags: ["content","size","fashion"],      isPremium: false },
  { id: "content-about-page",   name: "About Us Page Writer",        category: "Content",    icon: "🏢", description: "Página Sobre Nosotros con historia, equipo y timeline.",                            action: "prompt",      tags: ["content","about","company"],     isPremium: false },
  { id: "content-mission",      name: "Mission/Vision/Values",       category: "Content",    icon: "🌟", description: "Declaraciones de misión, visión y 5 valores con ejemplos.",                         action: "prompt",      tags: ["content","mission","brand"],     isPremium: false },
  { id: "content-product-launch",name: "Product Launch Copy",        category: "Content",    icon: "🚀", description: "Copy completo de lanzamiento: email, redes, landing, ads.",                          action: "prompt",      tags: ["content","launch","campaign"],   isPremium: true  },
  { id: "content-seasonal",     name: "Seasonal Campaign Writer",    category: "Content",    icon: "🎄", description: "Copy para campañas estacionales: Navidad, Black Friday, etc.",                       action: "prompt",      tags: ["content","seasonal","campaign"], isPremium: false },
  { id: "content-testimonials", name: "Testimonial Templates",       category: "Content",    icon: "💬", description: "Plantillas para recopilar y presentar testimonios de clientes.",                    action: "prompt",      tags: ["content","testimonials","trust"],isPremium: false },
  { id: "content-care-instruct",name: "Product Care Instructions",   category: "Content",    icon: "🌿", description: "Instrucciones de cuidado/uso claras y en tono de marca.",                           action: "prompt",      tags: ["content","care","product"],      isPremium: false },
  { id: "content-sustainability",name: "Sustainability Story",       category: "Content",    icon: "♻️", description: "Narrativa de sostenibilidad auténtica y medible para la marca.",                   action: "prompt",      tags: ["content","sustainability","esg"],isPremium: false },
  { id: "content-newsletter",   name: "Newsletter Content Planner",  category: "Content",    icon: "📧", description: "Plan de contenido mensual para newsletter con 4 temas semanales.",                   action: "prompt",      tags: ["content","newsletter","email"],  isPremium: false },
  { id: "content-content-calendar",name: "Content Calendar Generator",category: "Content",  icon: "📅", description: "Calendario editorial de 30 días con temas, formatos y canales.",                    action: "prompt",      tags: ["content","calendar","planning"], isPremium: false },
  { id: "content-localizer",    name: "Content Localizer",           category: "Content",    icon: "🌍", description: "Adapta contenido a mercados locales (cultura, idioma, referencias).",               action: "transform",   tags: ["content","localization","i18n"], isPremium: true  },
  { id: "content-tone-adjuster",name: "Brand Voice Tone Adjuster",   category: "Content",    icon: "🎚️", description: "Ajusta cualquier texto al tono de voz de la marca.",                               action: "transform",   tags: ["content","tone","brand-voice"],  isPremium: false },
  { id: "content-readability",  name: "Readability Improver",        category: "Content",    icon: "📖", description: "Mejora legibilidad Flesch-Kincaid y simplifica frases largas.",                     action: "transform",   tags: ["content","readability","ux"],    isPremium: false },
  { id: "content-summary",      name: "Long Content Summarizer",     category: "Content",    icon: "📋", description: "Resume artículos/docs largos en bullet points clave.",                              action: "transform",   tags: ["content","summary","tldr"],      isPremium: false },
  { id: "content-repurpose",    name: "Content Repurposer",          category: "Content",    icon: "♻️", description: "Convierte blog posts en 5 formatos: social, email, video, podcast, web.",          action: "transform",   tags: ["content","repurpose","multichannel"],isPremium: false },
  { id: "content-seo-rewrite",  name: "SEO Content Rewriter",        category: "Content",    icon: "✏️", description: "Reescribe contenido existente para posicionar keywords objetivo.",                  action: "transform",   tags: ["content","seo","rewrite"],       isPremium: false },
  { id: "content-glossary",     name: "Industry Glossary Builder",   category: "Content",    icon: "📚", description: "Genera glosario de 50 términos clave del sector con definiciones SEO.",             action: "prompt",      tags: ["content","glossary","seo"],      isPremium: false },
  { id: "content-listicle",     name: "Listicle Generator",          category: "Content",    icon: "📋", description: "Artículos 'Los 10 mejores...' con formato SEO y CTA.",                              action: "prompt",      tags: ["content","listicle","seo"],      isPremium: false },
  { id: "content-infographic",  name: "Infographic Content Planner", category: "Content",    icon: "📊", description: "Estructura y datos para infografías de alto valor compartible.",                    action: "prompt",      tags: ["content","infographic","visual"],isPremium: false },
  { id: "content-interview",    name: "Interview Questions Builder", category: "Content",    icon: "🎤", description: "20 preguntas de entrevista para podcast/blog de liderazgo.",                        action: "prompt",      tags: ["content","interview","podcast"], isPremium: false },
  { id: "content-legal-boiler", name: "Legal Boilerplate Generator", category: "Content",    icon: "⚖️", description: "Términos, privacidad y cookies adaptados al sector.",                               action: "prompt",      tags: ["content","legal","compliance"],  isPremium: true  },

  // ── DESIGN (25) ───────────────────────────────────────────────────────────
  { id: "design-color-palette", name: "Color Palette Generator",     category: "Design",     icon: "🎨", description: "Genera paletas de 5 colores harmonizadas basadas en el color primario.",             action: "generator",   tags: ["design","color","palette"],      isPremium: false },
  { id: "design-font-pairer",   name: "Font Pair Recommender",       category: "Design",     icon: "🔤", description: "Sugiere 5 pares de fuentes Google Fonts para heading+body.",                        action: "analysis",    tags: ["design","typography","fonts"],   isPremium: false },
  { id: "design-contrast",      name: "WCAG Contrast Checker",       category: "Design",     icon: "⚪", description: "Verifica ratio de contraste AA/AAA para accesibilidad.",                            action: "analysis",    tags: ["design","accessibility","wcag"], isPremium: false },
  { id: "design-spacing",       name: "Spacing System Builder",      category: "Design",     icon: "📐", description: "Define sistema de espaciado base-4/8 con tokens CSS.",                              action: "generator",   tags: ["design","spacing","tokens"],     isPremium: false },
  { id: "design-css-variables", name: "CSS Variables Generator",     category: "Design",     icon: "💻", description: "Genera sistema de design tokens CSS de la paleta de la marca.",                     action: "generator",   tags: ["design","css","tokens"],         isPremium: false },
  { id: "design-dark-mode",     name: "Dark Mode Color Generator",   category: "Design",     icon: "🌙", description: "Genera variante dark mode de la paleta de colores actual.",                         action: "generator",   tags: ["design","dark-mode","color"],    isPremium: false },
  { id: "design-animation-css", name: "CSS Animation Library",       category: "Design",     icon: "✨", description: "20 animaciones CSS listas: fade, slide, bounce, shake, etc.",                       action: "generator",   tags: ["design","animation","css"],      isPremium: false },
  { id: "design-hover-effects", name: "Hover Effects Generator",     category: "Design",     icon: "🖱️", description: "Efectos hover para botones, cards e imágenes en CSS puro.",                        action: "generator",   tags: ["design","hover","interactions"], isPremium: false },
  { id: "design-scroll-effects",name: "Scroll Animation Generator",  category: "Design",     icon: "📜", description: "Animaciones de entrada en scroll con Intersection Observer.",                       action: "generator",   tags: ["design","scroll","animation"],   isPremium: false },
  { id: "design-loading-anim",  name: "Loading Animation Pack",      category: "Design",     icon: "⏳", description: "Pack de 10 animaciones de loading/skeleton en CSS/SVG.",                            action: "generator",   tags: ["design","loading","skeleton"],   isPremium: false },
  { id: "design-empty-state",   name: "Empty State Designer",        category: "Design",     icon: "🗒️", description: "Diseña empty states con ilustración, mensaje y CTA.",                              action: "generator",   tags: ["design","empty-state","ux"],     isPremium: false },
  { id: "design-error-page",    name: "Error Page Designer",         category: "Design",     icon: "🚫", description: "Páginas 404/500 creativas en tono de marca con recuperación.",                      action: "generator",   tags: ["design","error","404"],          isPremium: false },
  { id: "design-modal-gen",     name: "Modal Component Generator",   category: "Design",     icon: "🪟", description: "Modal accesible con overlay, focus trap y animación.",                              action: "generator",   tags: ["design","modal","component"],    isPremium: false },
  { id: "design-toast-gen",     name: "Toast Notification System",   category: "Design",     icon: "🍞", description: "Sistema de toast notifications con 4 tipos y animaciones.",                         action: "generator",   tags: ["design","toast","feedback"],     isPremium: false },
  { id: "design-badge-gen",     name: "Badge & Tag Generator",       category: "Design",     icon: "🏷️", description: "Sistema de badges/pills para estados, categorías y etiquetas.",                    action: "generator",   tags: ["design","badge","tag"],          isPremium: false },
  { id: "design-gradient-gen",  name: "Gradient Background Creator", category: "Design",     icon: "🌈", description: "Gradientes CSS multi-stop para fondos de secciones.",                               action: "generator",   tags: ["design","gradient","background"],isPremium: false },
  { id: "design-shadow-system", name: "Box Shadow System",           category: "Design",     icon: "🌑", description: "Sistema de sombras en 5 niveles con elevación y neumorphism.",                      action: "generator",   tags: ["design","shadow","elevation"],   isPremium: false },
  { id: "design-grid-builder",  name: "CSS Grid Layout Builder",     category: "Design",     icon: "⬛", description: "Layouts CSS Grid para features, cards y dashboards.",                               action: "generator",   tags: ["design","grid","layout"],        isPremium: false },
  { id: "design-flex-patterns", name: "Flexbox Pattern Library",     category: "Design",     icon: "↔️", description: "Patrones Flexbox para navbars, footers y centering complejos.",                    action: "generator",   tags: ["design","flexbox","layout"],     isPremium: false },
  { id: "design-icon-set",      name: "SVG Icon Set Generator",      category: "Design",     icon: "🔷", description: "Genera set de 20 iconos SVG coherentes para la marca.",                             action: "generator",   tags: ["design","icons","svg"],          isPremium: true  },
  { id: "design-logo-concept",  name: "Logo Concept Generator",      category: "Design",     icon: "✴️", description: "Conceptos de logo SVG basados en nombre, sector y valores.",                       action: "generator",   tags: ["design","logo","branding"],      isPremium: true  },
  { id: "design-favicon",       name: "Favicon Generator",           category: "Design",     icon: "⬜", description: "Favicon SVG/PNG en múltiples tamaños desde logo existente.",                        action: "transform",   tags: ["design","favicon","brand"],      isPremium: false },
  { id: "design-og-image",      name: "Open Graph Image Template",   category: "Design",     icon: "🖼️", description: "Template HTML para Open Graph images consistentes con la marca.",                  action: "generator",   tags: ["design","og","social"],          isPremium: false },
  { id: "design-print-assets",  name: "Print Asset Templates",       category: "Design",     icon: "🖨️", description: "Templates HTML→PDF para tarjetas, flyers y packaging.",                            action: "generator",   tags: ["design","print","templates"],    isPremium: true  },
  { id: "design-component-doc", name: "Component Documentation",     category: "Design",     icon: "📚", description: "Documenta componentes UI con uso, props y ejemplos en Storybook.",                  action: "generator",   tags: ["design","components","storybook"],isPremium: false },

  // ── ANALYTICS (20) ────────────────────────────────────────────────────────
  { id: "analytics-kpi-dash",   name: "KPI Dashboard Builder",       category: "Analytics",  icon: "📊", description: "Dashboard de KPIs en HTML con Chart.js y datos simulados.",                        action: "generator",   tags: ["analytics","dashboard","kpi"],   isPremium: false },
  { id: "analytics-ab-test",    name: "A/B Test Designer",           category: "Analytics",  icon: "🔬", description: "Diseña A/B tests con tamaño de muestra y análisis estadístico.",                   action: "analysis",    tags: ["analytics","ab-test","stats"],   isPremium: false },
  { id: "analytics-funnel",     name: "Funnel Analyzer",             category: "Analytics",  icon: "📉", description: "Analiza tasas de conversión por etapa e identifica cuellos.",                       action: "analysis",    tags: ["analytics","funnel","cvr"],      isPremium: false },
  { id: "analytics-cohort",     name: "Cohort Analysis Builder",     category: "Analytics",  icon: "👥", description: "Framework de cohortes con retención y LTV por período.",                           action: "analysis",    tags: ["analytics","cohort","retention"],isPremium: true  },
  { id: "analytics-forecast",   name: "Revenue Forecaster",          category: "Analytics",  icon: "🔮", description: "Modelo de pronóstico 12 meses con 3 escenarios (pesimista/base/optimista).",        action: "analysis",    tags: ["analytics","forecast","revenue"],isPremium: true  },
  { id: "analytics-attribution",name: "Multi-Touch Attribution",     category: "Analytics",  icon: "🗺️", description: "Modelo de atribución multicanal con distribución de crédito.",                     action: "analysis",    tags: ["analytics","attribution","media"],isPremium: true  },
  { id: "analytics-rfm",        name: "RFM Segmentation Engine",     category: "Analytics",  icon: "🎯", description: "Segmentación RFM de clientes con estrategia por segmento.",                        action: "analysis",    tags: ["analytics","rfm","segmentation"],isPremium: true  },
  { id: "analytics-ga4-events", name: "GA4 Events Planner",          category: "Analytics",  icon: "📈", description: "Plan de implementación GA4 con enhanced ecommerce y conversiones.",                 action: "generator",   tags: ["analytics","ga4","tracking"],    isPremium: false },
  { id: "analytics-heatmap",    name: "Heatmap Insights Analyzer",   category: "Analytics",  icon: "🌡️", description: "Interpreta datos de heatmap e identifica áreas de mejora UX.",                    action: "analysis",    tags: ["analytics","heatmap","ux"],      isPremium: false },
  { id: "analytics-cro-audit",  name: "CRO Audit Checklist",         category: "Analytics",  icon: "⚡", description: "Auditoría de 50 puntos para optimización de conversión.",                          action: "analysis",    tags: ["analytics","cro","audit"],       isPremium: false },
  { id: "analytics-nps",        name: "NPS Survey Builder",          category: "Analytics",  icon: "😊", description: "Survey NPS con análisis de promotores/detractores y seguimiento.",                  action: "generator",   tags: ["analytics","nps","survey"],      isPremium: false },
  { id: "analytics-churn",      name: "Churn Predictor",             category: "Analytics",  icon: "⚠️", description: "Identifica señales de churn y acciones preventivas por segmento.",                 action: "analysis",    tags: ["analytics","churn","retention"], isPremium: true  },
  { id: "analytics-ltv",        name: "Customer LTV Calculator",     category: "Analytics",  icon: "💰", description: "Calcula LTV por canal, cohorte y segmento de cliente.",                            action: "analysis",    tags: ["analytics","ltv","customer"],    isPremium: false },
  { id: "analytics-cac",        name: "CAC Analyzer",                category: "Analytics",  icon: "💸", description: "Calcula CAC por canal y ratio LTV:CAC por segmento.",                              action: "analysis",    tags: ["analytics","cac","efficiency"],  isPremium: false },
  { id: "analytics-benchmark",  name: "Industry Benchmarker",        category: "Analytics",  icon: "🏆", description: "Compara KPIs vs benchmarks del sector con gap analysis.",                          action: "analysis",    tags: ["analytics","benchmark","kpi"],   isPremium: false },
  { id: "analytics-roi-calc",   name: "ROI Calculator",              category: "Analytics",  icon: "📐", description: "Calculadora interactiva de ROI para campañas e inversiones.",                      action: "generator",   tags: ["analytics","roi","calculator"],  isPremium: false },
  { id: "analytics-budget-opt", name: "Budget Optimizer",            category: "Analytics",  icon: "⚖️", description: "Distribución óptima de presupuesto entre canales con ROAS.",                      action: "analysis",    tags: ["analytics","budget","allocation"],isPremium: true  },
  { id: "analytics-report-gen", name: "Auto-Report Generator",       category: "Analytics",  icon: "📋", description: "Genera informe ejecutivo mensual con KPIs y comentarios.",                         action: "generator",   tags: ["analytics","reporting","executive"],isPremium: false },
  { id: "analytics-price-elast",name: "Price Elasticity Analyzer",   category: "Analytics",  icon: "📊", description: "Analiza elasticidad precio-demanda y precio óptimo.",                              action: "analysis",    tags: ["analytics","pricing","elasticity"],isPremium: true  },
  { id: "analytics-session-rec",name: "Session Recording Insights",  category: "Analytics",  icon: "🎥", description: "Interpreta grabaciones de sesión e identifica patrones de UX.",                    action: "analysis",    tags: ["analytics","sessions","ux"],     isPremium: false },

  // ── EMAIL (20) ────────────────────────────────────────────────────────────
  { id: "email-welcome",        name: "Welcome Email Sequence",      category: "Email",      icon: "👋", description: "Secuencia 3 emails: bienvenida + valor + primera compra.",                          action: "prompt",      tags: ["email","welcome","onboarding"],  isPremium: false },
  { id: "email-abandoned-cart", name: "Abandoned Cart Recovery",     category: "Email",      icon: "🛒", description: "Secuencia 3 emails recuperación carrito (1h, 24h, 72h).",                          action: "prompt",      tags: ["email","cart","recovery"],       isPremium: false },
  { id: "email-winback",        name: "Win-Back Campaign",           category: "Email",      icon: "💔", description: "Secuencia 3 emails reactivación de clientes inactivos.",                            action: "prompt",      tags: ["email","win-back","reactivation"],isPremium: false },
  { id: "email-post-purchase",  name: "Post-Purchase Flow",          category: "Email",      icon: "✅", description: "Secuencia post-compra: confirmación + upsell + review request.",                    action: "prompt",      tags: ["email","post-purchase","upsell"],isPremium: false },
  { id: "email-review-request", name: "Review Request Email",        category: "Email",      icon: "⭐", description: "Email de solicitud de reseña con timing óptimo y incentivo.",                       action: "prompt",      tags: ["email","review","social-proof"], isPremium: false },
  { id: "email-back-in-stock",  name: "Back-in-Stock Alert",         category: "Email",      icon: "📦", description: "Email de alerta cuando el producto vuelve a estar disponible.",                     action: "prompt",      tags: ["email","stock","alert"],         isPremium: false },
  { id: "email-price-drop",     name: "Price Drop Alert",            category: "Email",      icon: "🏷️", description: "Email de bajada de precio para wishlisters y visitantes.",                        action: "prompt",      tags: ["email","price","wishlist"],      isPremium: false },
  { id: "email-birthday",       name: "Birthday Email Campaign",     category: "Email",      icon: "🎂", description: "Email de cumpleaños personalizado con oferta especial.",                             action: "prompt",      tags: ["email","birthday","personalization"],isPremium: false },
  { id: "email-vip-program",    name: "VIP Program Email",           category: "Email",      icon: "👑", description: "Email de bienvenida al programa VIP con beneficios exclusivos.",                    action: "prompt",      tags: ["email","vip","loyalty"],         isPremium: false },
  { id: "email-referral",       name: "Referral Program Email",      category: "Email",      icon: "🤝", description: "Email para invitar a referidos con código personalizado.",                           action: "prompt",      tags: ["email","referral","viral"],      isPremium: false },
  { id: "email-flash-sale",     name: "Flash Sale Announcement",     category: "Email",      icon: "⚡", description: "Email de flash sale con countdown y urgencia máxima.",                              action: "prompt",      tags: ["email","flash-sale","urgency"],  isPremium: false },
  { id: "email-newsletter",     name: "Newsletter Content Block",    category: "Email",      icon: "📰", description: "Bloque de contenido semanal para newsletter con curation.",                         action: "prompt",      tags: ["email","newsletter","content"],  isPremium: false },
  { id: "email-re-engagement",  name: "Re-Engagement Series",        category: "Email",      icon: "🔄", description: "Serie de 3 emails para reactivar suscriptores inactivos.",                         action: "prompt",      tags: ["email","re-engagement","list"],  isPremium: false },
  { id: "email-subject-lines",  name: "Subject Line A/B Tester",     category: "Email",      icon: "✉️", description: "10 variantes de subject line con emojis y A/B recommendations.",                   action: "prompt",      tags: ["email","subject-line","ab"],     isPremium: false },
  { id: "email-preview-text",   name: "Preview Text Optimizer",      category: "Email",      icon: "👁️", description: "Optimiza el preview text para maximizar open rate.",                               action: "prompt",      tags: ["email","preview","open-rate"],   isPremium: false },
  { id: "email-unsubscribe",    name: "Unsubscribe Page Designer",   category: "Email",      icon: "🚪", description: "Página de baja que salva suscriptores con preferencias.",                          action: "generator",   tags: ["email","unsubscribe","retention"],isPremium: false },
  { id: "email-drip-sequence",  name: "Drip Campaign Builder",       category: "Email",      icon: "💧", description: "Secuencia de nurturing de 7 emails para leads fríos.",                             action: "prompt",      tags: ["email","drip","nurturing"],      isPremium: false },
  { id: "email-transactional",  name: "Transactional Email Templates",category: "Email",     icon: "📧", description: "Templates para emails transaccionales: orden, envío, factura.",                    action: "generator",   tags: ["email","transactional","order"], isPremium: false },
  { id: "email-survey",         name: "Customer Survey Email",       category: "Email",      icon: "📋", description: "Email de encuesta de satisfacción con formulario embebido.",                        action: "prompt",      tags: ["email","survey","nps"],          isPremium: false },
  { id: "email-signature",      name: "Email Signature Builder",     category: "Email",      icon: "✍️", description: "Firma de email HTML profesional con logo y redes sociales.",                       action: "generator",   tags: ["email","signature","brand"],     isPremium: false },

  // ── SOCIAL MEDIA (20) ─────────────────────────────────────────────────────
  { id: "social-ig-pack",       name: "Instagram 7-Day Pack",        category: "Social",     icon: "📸", description: "7 publicaciones Instagram con caption, hashtags y tipo de contenido.",               action: "prompt",      tags: ["social","instagram","calendar"], isPremium: false },
  { id: "social-linkedin-posts",name: "LinkedIn Thought Leadership", category: "Social",     icon: "💼", description: "5 posts de liderazgo de opinión en LinkedIn con gancho.",                           action: "prompt",      tags: ["social","linkedin","b2b"],       isPremium: false },
  { id: "social-tiktok-scripts",name: "TikTok/Reels Scripts",        category: "Social",     icon: "🎵", description: "5 scripts 15-60s con hooks, estructura y CTA.",                                    action: "prompt",      tags: ["social","tiktok","reels"],       isPremium: false },
  { id: "social-twitter-thread",name: "Twitter/X Thread Creator",    category: "Social",     icon: "🐦", description: "Thread de 12 tweets con gancho, datos y alto potencial viral.",                    action: "prompt",      tags: ["social","twitter","thread"],     isPremium: false },
  { id: "social-youtube-seo",   name: "YouTube SEO Optimizer",       category: "Social",     icon: "▶️", description: "Título, descripción, tags y chapters para YouTube SEO.",                           action: "prompt",      tags: ["social","youtube","video-seo"],  isPremium: false },
  { id: "social-hashtag",       name: "Hashtag Research Pack",       category: "Social",     icon: "#️⃣", description: "65 hashtags por nicho con categorización y sets de rotación.",                     action: "analysis",    tags: ["social","hashtags","reach"],     isPremium: false },
  { id: "social-community",     name: "Community Reply Templates",   category: "Social",     icon: "💬", description: "Plantillas de respuesta para comentarios, quejas y preguntas.",                     action: "generator",   tags: ["social","community","management"],isPremium: false },
  { id: "social-influencer",    name: "Influencer Brief Creator",    category: "Social",     icon: "⭐", description: "Brief profesional para colaboraciones de influencer marketing.",                    action: "generator",   tags: ["social","influencer","ugc"],     isPremium: false },
  { id: "social-ugc-campaign",  name: "UGC Campaign Builder",        category: "Social",     icon: "📷", description: "Estrategia UGC completa con mecánica, premios y copy.",                            action: "prompt",      tags: ["social","ugc","campaign"],       isPremium: true  },
  { id: "social-pinterest",     name: "Pinterest Strategy Builder",  category: "Social",     icon: "📌", description: "Boards, pins y keywords para Pinterest SEO visual.",                               action: "prompt",      tags: ["social","pinterest","visual"],   isPremium: false },
  { id: "social-facebook-ads",  name: "Facebook Ad Copy Pack",       category: "Social",     icon: "📘", description: "Copy para Meta Ads: headlines, textos primarios y descripciones.",                 action: "prompt",      tags: ["social","facebook","ads"],       isPremium: false },
  { id: "social-story-pack",    name: "Story Templates Pack",        category: "Social",     icon: "📲", description: "Pack de 10 story templates Instagram/TikTok en HTML.",                             action: "generator",   tags: ["social","stories","template"],   isPremium: false },
  { id: "social-carousel",      name: "Carousel Post Generator",     category: "Social",     icon: "🎠", description: "Script y estructura para carruseles de Instagram educativos.",                      action: "prompt",      tags: ["social","carousel","instagram"], isPremium: false },
  { id: "social-bio-optimizer", name: "Social Bio Optimizer",        category: "Social",     icon: "👤", description: "Bios optimizadas para Instagram, Twitter, LinkedIn y TikTok.",                     action: "prompt",      tags: ["social","bio","profile"],        isPremium: false },
  { id: "social-competitor",    name: "Competitor Social Monitor",   category: "Social",     icon: "🎯", description: "Framework para monitorear estrategia social de competidores.",                     action: "analysis",    tags: ["social","competitor","monitoring"],isPremium: false },
  { id: "social-viral-hook",    name: "Viral Hook Generator",        category: "Social",     icon: "🎣", description: "10 hooks virales para primers 3 segundos de cualquier video.",                     action: "prompt",      tags: ["social","viral","hook"],         isPremium: false },
  { id: "social-crisis-comms",  name: "Crisis Communications Plan",  category: "Social",     icon: "🚨", description: "Plan de comunicación para crisis en redes sociales.",                              action: "generator",   tags: ["social","crisis","pr"],          isPremium: true  },
  { id: "social-linkinbio",     name: "Link-in-Bio Page Builder",    category: "Social",     icon: "🔗", description: "Página link-in-bio HTML con todos los CTA de la marca.",                           action: "generator",   tags: ["social","linkinbio","landing"],  isPremium: false },
  { id: "social-content-rules", name: "Platform Content Rules Guide",category: "Social",     icon: "📏", description: "Guía de especificaciones técnicas por plataforma social.",                         action: "generator",   tags: ["social","specs","guidelines"],   isPremium: false },
  { id: "social-month-calendar",name: "Monthly Social Calendar",     category: "Social",     icon: "📅", description: "Calendario social mensual con temas, formatos y horarios óptimos.",                 action: "prompt",      tags: ["social","calendar","planning"],  isPremium: false },

  // ── COMMERCE (25) ─────────────────────────────────────────────────────────
  { id: "commerce-bundles",     name: "Bundle Strategy Builder",     category: "Commerce",   icon: "🎁", description: "Diseña 5 bundles con pricing psychology y copy de presentación.",                  action: "prompt",      tags: ["commerce","bundle","aov"],       isPremium: false },
  { id: "commerce-pricing-psych",name: "Pricing Psychology Advisor", category: "Commerce",   icon: "🧠", description: "Aplica charm pricing, anchoring y decoy pricing a tu catálogo.",                    action: "analysis",    tags: ["commerce","pricing","psychology"],isPremium: false },
  { id: "commerce-loyalty",     name: "Loyalty Program Designer",    category: "Commerce",   icon: "⭐", description: "Programa de puntos/niveles con gamificación y beneficios.",                        action: "prompt",      tags: ["commerce","loyalty","retention"],isPremium: true  },
  { id: "commerce-cart-recovery",name: "Cart Recovery Sequence",     category: "Commerce",   icon: "🛒", description: "Secuencia email+SMS de recuperación de carritos abandonados.",                      action: "prompt",      tags: ["commerce","cart","recovery"],    isPremium: false },
  { id: "commerce-flash-sale",  name: "Flash Sale Campaign",         category: "Commerce",   icon: "⚡", description: "Campaign completa: countdown page + emails + social posts.",                       action: "prompt",      tags: ["commerce","flash-sale","urgency"],isPremium: false },
  { id: "commerce-pdp-optimizer",name: "PDP Optimizer",              category: "Commerce",   icon: "📦", description: "Optimización completa de Product Detail Page para conversión.",                    action: "prompt",      tags: ["commerce","pdp","conversion"],   isPremium: false },
  { id: "commerce-seasonal-cal",name: "Annual Commerce Calendar",    category: "Commerce",   icon: "📅", description: "Calendario comercial anual con fechas clave por mercado.",                         action: "prompt",      tags: ["commerce","seasonal","calendar"],isPremium: false },
  { id: "commerce-checkout-opt",name: "Checkout Optimizer",          category: "Commerce",   icon: "💳", description: "Mejoras del proceso de checkout para reducir abandono.",                           action: "analysis",    tags: ["commerce","checkout","ux"],      isPremium: false },
  { id: "commerce-subscription",name: "Subscription Model Builder",  category: "Commerce",   icon: "🔄", description: "Diseño completo de modelo de suscripción con planes y MRR.",                      action: "prompt",      tags: ["commerce","subscription","saas"],isPremium: true  },
  { id: "commerce-returns",     name: "Returns Policy Optimizer",    category: "Commerce",   icon: "↩️", description: "Política de devoluciones que convierte el miedo en confianza.",                    action: "prompt",      tags: ["commerce","returns","trust"],    isPremium: false },
  { id: "commerce-upsell",      name: "Upsell Script Generator",     category: "Commerce",   icon: "↑",  description: "Scripts de upsell y cross-sell para checkout y post-compra.",                     action: "prompt",      tags: ["commerce","upsell","revenue"],   isPremium: false },
  { id: "commerce-gifting",     name: "Gift Card Program Builder",   category: "Commerce",   icon: "🎁", description: "Programa de tarjetas de regalo con landing y email flow.",                         action: "generator",   tags: ["commerce","gift-card","holiday"],isPremium: false },
  { id: "commerce-preorder",    name: "Pre-Order Campaign Builder",  category: "Commerce",   icon: "⏰", description: "Campaign de pre-orders con landing, email y urgencia.",                            action: "generator",   tags: ["commerce","pre-order","launch"], isPremium: false },
  { id: "commerce-wholesale",   name: "Wholesale Pricing Strategy",  category: "Commerce",   icon: "🏭", description: "Estrategia de precios mayorista con niveles de volumen.",                         action: "analysis",    tags: ["commerce","wholesale","b2b"],    isPremium: true  },
  { id: "commerce-tiered-disc", name: "Tiered Discount Engine",      category: "Commerce",   icon: "🎚️", description: "Sistema de descuentos por volumen con reglas y comunicación.",                    action: "generator",   tags: ["commerce","discount","tiered"],  isPremium: false },
  { id: "commerce-free-ship",   name: "Free Shipping Threshold Optimizer",category: "Commerce",icon: "🚚",description: "Calcula y comunica el umbral de envío gratis para +AOV.",                       action: "analysis",    tags: ["commerce","shipping","aov"],     isPremium: false },
  { id: "commerce-social-proof",name: "Social Proof Strategy",       category: "Commerce",   icon: "⭐", description: "Sistema de proof: reviews, UGC, contadores y trust badges.",                      action: "analysis",    tags: ["commerce","social-proof","trust"],isPremium: false },
  { id: "commerce-referral-prog",name: "Referral Program Builder",   category: "Commerce",   icon: "🤝", description: "Programa de referidos con mecánica, incentivos y copy.",                           action: "prompt",      tags: ["commerce","referral","viral"],   isPremium: false },
  { id: "commerce-cross-border",name: "Cross-Border Commerce Guide", category: "Commerce",   icon: "🌍", description: "Guía de expansión internacional: impuestos, envíos y pagos.",                     action: "analysis",    tags: ["commerce","international","global"],isPremium: true  },
  { id: "commerce-marketplace", name: "Marketplace Listing Optimizer",category: "Commerce",  icon: "🏪", description: "Optimiza listings en Amazon, eBay y Etsy para más visibilidad.",                  action: "prompt",      tags: ["commerce","marketplace","amazon"],isPremium: false },
  { id: "commerce-inventory",   name: "Inventory Urgency Messaging", category: "Commerce",   icon: "📦", description: "Mensajes de urgencia por stock: 'Solo quedan 3' y variantes.",                    action: "generator",   tags: ["commerce","inventory","scarcity"],isPremium: false },
  { id: "commerce-dynamic-pricing",name: "Dynamic Pricing Strategy", category: "Commerce",   icon: "📊", description: "Estrategia de precios dinámicos basada en demanda y estacionalidad.",             action: "analysis",    tags: ["commerce","pricing","dynamic"],  isPremium: true  },
  { id: "commerce-post-purchase",name: "Post-Purchase Experience",    category: "Commerce",   icon: "🎉", description: "Optimiza la experiencia post-compra para NPS y repeat purchase.",                 action: "analysis",    tags: ["commerce","post-purchase","nps"],isPremium: false },
  { id: "commerce-abandoned-browse",name: "Browse Abandonment Flow", category: "Commerce",   icon: "👁️", description: "Flow de remarketing para visitantes que vieron producto pero no compraron.",     action: "prompt",      tags: ["commerce","remarketing","browse"],isPremium: false },
  { id: "commerce-sample-strategy",name: "Product Sampling Strategy",category: "Commerce",   icon: "🧪", description: "Estrategia de muestras para conversión de nuevos clientes.",                     action: "analysis",    tags: ["commerce","samples","acquisition"],isPremium: false },

  // ── AUTOMATION (20) ───────────────────────────────────────────────────────
  { id: "auto-order-webhook",   name: "Order Webhook Setup",         category: "Automation", icon: "🔔", description: "Configura webhooks de pedido hacia Slack/Discord/Telegram.",                      action: "webhook",     tags: ["automation","webhook","order"],  isPremium: false },
  { id: "auto-inventory-sync",  name: "Inventory Sync Manager",      category: "Automation", icon: "📦", description: "Sincroniza inventario entre Shopify y sistemas externos.",                       action: "integration", tags: ["automation","inventory","sync"],  isPremium: true  },
  { id: "auto-email-trigger",   name: "Email Trigger Builder",       category: "Automation", icon: "📧", description: "Define triggers de email basados en comportamiento del cliente.",                 action: "generator",   tags: ["automation","email","trigger"],  isPremium: false },
  { id: "auto-sms-alert",       name: "SMS Alert Configurator",      category: "Automation", icon: "📱", description: "Alertas SMS para pedidos, stock y eventos críticos.",                            action: "generator",   tags: ["automation","sms","alert"],      isPremium: false },
  { id: "auto-push-notif",      name: "Push Notification Builder",   category: "Automation", icon: "🔔", description: "Notificaciones push web y móvil con segmentación.",                              action: "generator",   tags: ["automation","push","mobile"],    isPremium: false },
  { id: "auto-slack-notify",    name: "Slack Notification Template", category: "Automation", icon: "💬", description: "Templates de notificaciones Slack para métricas de negocio.",                    action: "generator",   tags: ["automation","slack","notify"],   isPremium: false },
  { id: "auto-zapier",          name: "Zapier Workflow Builder",     category: "Automation", icon: "⚡", description: "Describe flujos de Zapier para automatizar tareas repetitivas.",                  action: "generator",   tags: ["automation","zapier","workflow"], isPremium: false },
  { id: "auto-make",            name: "Make.com Scenario Builder",   category: "Automation", icon: "🔧", description: "Escenarios Make.com para automatizaciones complejas multi-paso.",                 action: "generator",   tags: ["automation","make","scenario"],  isPremium: false },
  { id: "auto-tagging",         name: "Auto-Tagging Rules Engine",   category: "Automation", icon: "🏷️", description: "Reglas de etiquetado automático de clientes y pedidos.",                        action: "generator",   tags: ["automation","tagging","segmentation"],isPremium: false },
  { id: "auto-customer-segment",name: "Customer Segmenter",          category: "Automation", icon: "👥", description: "Segmentación automática de clientes por comportamiento.",                        action: "analysis",    tags: ["automation","segmentation","crm"],isPremium: true  },
  { id: "auto-product-tagger",  name: "Product Auto-Tagger",         category: "Automation", icon: "🏷️", description: "Reglas de etiquetado automático de productos por atributos.",                   action: "generator",   tags: ["automation","products","tags"],  isPremium: false },
  { id: "auto-price-updater",   name: "Bulk Price Updater",          category: "Automation", icon: "💰", description: "Reglas de actualización masiva de precios por categoría/tag.",                   action: "generator",   tags: ["automation","price","bulk"],     isPremium: false },
  { id: "auto-report-scheduler",name: "Report Scheduler",            category: "Automation", icon: "📊", description: "Programa envío automático de informes por email en cron.",                       action: "generator",   tags: ["automation","report","scheduler"],isPremium: false },
  { id: "auto-review-requester",name: "Review Request Automator",    category: "Automation", icon: "⭐", description: "Automatiza solicitudes de reseña con timing óptimo post-entrega.",                action: "generator",   tags: ["automation","review","trigger"], isPremium: false },
  { id: "auto-follow-up",       name: "Follow-Up Sequence Builder",  category: "Automation", icon: "🔄", description: "Secuencias de seguimiento automatizadas por evento.",                            action: "generator",   tags: ["automation","follow-up","crm"],  isPremium: false },
  { id: "auto-data-export",     name: "Data Export Scheduler",       category: "Automation", icon: "📤", description: "Exportación automática de datos a CSV/Google Sheets.",                          action: "integration", tags: ["automation","export","data"],    isPremium: false },
  { id: "auto-collection-update",name: "Collection Auto-Update",     category: "Automation", icon: "📁", description: "Reglas para actualizar colecciones Shopify automáticamente.",                    action: "generator",   tags: ["automation","shopify","collection"],isPremium: false },
  { id: "auto-low-stock",       name: "Low Stock Alert System",      category: "Automation", icon: "⚠️", description: "Alertas multi-canal cuando el stock baja del umbral.",                          action: "webhook",     tags: ["automation","stock","alert"],    isPremium: false },
  { id: "auto-api-connector",   name: "API Connector Builder",       category: "Automation", icon: "🔌", description: "Genera código de conexión entre APIs con autenticación.",                        action: "generator",   tags: ["automation","api","connector"],  isPremium: true  },
  { id: "auto-cron-scheduler",  name: "Cron Job Scheduler",          category: "Automation", icon: "⏰", description: "Define tareas programadas con expresiones cron y descripción.",                  action: "generator",   tags: ["automation","cron","scheduled"], isPremium: false },

  // ── AI & LLM (15) ─────────────────────────────────────────────────────────
  { id: "ai-claude-prompt",     name: "Claude Prompt Optimizer",     category: "AI & LLM",   icon: "🤖", description: "Optimiza prompts para Claude con chain-of-thought y few-shot.",                   action: "transform",   tags: ["ai","claude","prompts"],         isPremium: false, isNew: true },
  { id: "ai-gpt-prompt",        name: "GPT Prompt Engineer",         category: "AI & LLM",   icon: "💬", description: "Estructura prompts para GPT-4 con system/user/context.",                         action: "transform",   tags: ["ai","gpt","prompts"],            isPremium: false, isNew: true },
  { id: "ai-gemini-prompt",     name: "Gemini Prompt Optimizer",     category: "AI & LLM",   icon: "♊", description: "Prompts multi-modal para Gemini con imágenes y contexto.",                       action: "transform",   tags: ["ai","gemini","prompts"],         isPremium: false, isNew: true },
  { id: "ai-image-caption",     name: "Image Caption AI",            category: "AI & LLM",   icon: "🖼️", description: "Genera captions descriptivas para imágenes de producto.",                       action: "prompt",      tags: ["ai","image","caption"],          isPremium: false },
  { id: "ai-video-script",      name: "Video Script AI",             category: "AI & LLM",   icon: "🎬", description: "Scripts de video de 30-120 segundos con estructura probada.",                    action: "prompt",      tags: ["ai","video","script"],           isPremium: false },
  { id: "ai-voice-narration",   name: "Voice Narration Writer",      category: "AI & LLM",   icon: "🎙️", description: "Copy optimizado para text-to-speech natural y emocional.",                      action: "transform",   tags: ["ai","voice","tts"],              isPremium: false },
  { id: "ai-translation",       name: "Multilingual Translator",     category: "AI & LLM",   icon: "🌍", description: "Traduce y adapta contenido a 20 idiomas manteniendo tono de marca.",              action: "transform",   tags: ["ai","translation","i18n"],       isPremium: false },
  { id: "ai-sentiment",         name: "Sentiment Analyzer",          category: "AI & LLM",   icon: "😊", description: "Analiza el sentimiento de reviews y comentarios de clientes.",                   action: "analysis",    tags: ["ai","sentiment","reviews"],      isPremium: false },
  { id: "ai-tone-analyzer",     name: "Tone & Voice Analyzer",       category: "AI & LLM",   icon: "🎚️", description: "Analiza el tono de un texto y sugiere ajustes de voz de marca.",                action: "analysis",    tags: ["ai","tone","brand-voice"],       isPremium: false },
  { id: "ai-readability",       name: "Readability Score Checker",   category: "AI & LLM",   icon: "📖", description: "Calcula score Flesch y sugiere mejoras de legibilidad.",                         action: "analysis",    tags: ["ai","readability","flesch"],     isPremium: false },
  { id: "ai-plagiarism",        name: "Originality Checker",         category: "AI & LLM",   icon: "🔍", description: "Detecta frases genéricas de AI y sugiere variantes originales.",                 action: "analysis",    tags: ["ai","plagiarism","original"],    isPremium: false },
  { id: "ai-content-grader",    name: "AI Content Grader",           category: "AI & LLM",   icon: "📊", description: "Evalúa contenido en 10 criterios y da score con feedback.",                      action: "analysis",    tags: ["ai","grading","quality"],        isPremium: false },
  { id: "ai-brand-voice",       name: "Brand Voice Enforcer",        category: "AI & LLM",   icon: "🎯", description: "Reescribe cualquier texto para que suene como la marca.",                        action: "transform",   tags: ["ai","brand-voice","consistency"],isPremium: false },
  { id: "ai-summarizer",        name: "Document Summarizer AI",      category: "AI & LLM",   icon: "📋", description: "Resume documentos largos en key points y TL;DR.",                               action: "transform",   tags: ["ai","summary","document"],       isPremium: false },
  { id: "ai-competitor-intel",  name: "Competitor Intelligence AI",  category: "AI & LLM",   icon: "🕵️", description: "Extrae insights de competidores de sus webs y contenido.",                      action: "analysis",    tags: ["ai","competitor","intelligence"],isPremium: true, isNew: true  },

  // ── DEVELOPER (6) ─────────────────────────────────────────────────────────
  { id: "dev-api-tester",       name: "API Endpoint Tester",         category: "Developer",  icon: "🔌", description: "Genera tests curl y Postman para endpoints REST/GraphQL.",                        action: "generator",   tags: ["dev","api","testing"],           isPremium: false },
  { id: "dev-webhook-manager",  name: "Webhook Manager",             category: "Developer",  icon: "🔔", description: "Gestión de webhooks: registro, replay y logging.",                               action: "generator",   tags: ["dev","webhook","events"],        isPremium: false },
  { id: "dev-schema-validator", name: "JSON Schema Validator",       category: "Developer",  icon: "✅", description: "Valida y genera schemas JSON para APIs y formularios.",                          action: "generator",   tags: ["dev","json","schema"],           isPremium: false },
  { id: "dev-performance",      name: "Performance Profiler",        category: "Developer",  icon: "⚡", description: "Audita performance del frontend: bundle, LCP, FID, CLS.",                        action: "analysis",    tags: ["dev","performance","cwv"],       isPremium: false },
  { id: "dev-env-manager",      name: "Environment Config Manager",  category: "Developer",  icon: "⚙️", description: "Genera .env templates con variables documentadas por entorno.",                  action: "generator",   tags: ["dev","env","config"],            isPremium: false },
  { id: "dev-code-linter",      name: "Code Quality Linter",         category: "Developer",  icon: "🔍", description: "Revisa código TypeScript/JS por smells, issues y mejoras.",                     action: "analysis",    tags: ["dev","linting","quality"],       isPremium: false },

  // ── INTEGRATIONS (25) ─────────────────────────────────────────────────────
  { id: "int-shopify",          name: "Shopify Store Connector",     category: "Integrations",icon: "🛒", description: "Conexión completa Shopify: productos, pedidos, clientes, webhooks.",             action: "integration", tags: ["integration","shopify","ecommerce"],isPremium: false },
  { id: "int-google-analytics", name: "Google Analytics 4",         category: "Integrations",icon: "📊", description: "Implementación GA4 con enhanced ecommerce completo.",                            action: "integration", tags: ["integration","ga4","analytics"],  isPremium: false },
  { id: "int-google-search",    name: "Google Search Console",      category: "Integrations",icon: "🔍", description: "Conecta GSC para monitorear impresiones, CTR y posiciones.",                     action: "integration", tags: ["integration","gsc","seo"],        isPremium: false },
  { id: "int-google-merchant",  name: "Google Merchant Center",     category: "Integrations",icon: "🛍️", description: "Feed de productos para Google Shopping y Performance Max.",                     action: "integration", tags: ["integration","google","shopping"], isPremium: false },
  { id: "int-facebook-pixel",   name: "Meta Pixel & CAPI",          category: "Integrations",icon: "📘", description: "Meta Pixel + Conversions API para tracking server-side.",                       action: "integration", tags: ["integration","meta","pixel"],     isPremium: false },
  { id: "int-tiktok-pixel",     name: "TikTok Pixel",               category: "Integrations",icon: "🎵", description: "TikTok Pixel para tracking de eventos y audiencias.",                           action: "integration", tags: ["integration","tiktok","pixel"],   isPremium: false },
  { id: "int-klaviyo",          name: "Klaviyo Connect",            category: "Integrations",icon: "📧", description: "Integra Klaviyo con sincronización de eventos y listas.",                       action: "integration", tags: ["integration","klaviyo","email"],  isPremium: false },
  { id: "int-mailchimp",        name: "Mailchimp Bridge",           category: "Integrations",icon: "🐒", description: "Sincroniza Mailchimp con eventos de compra y segmentos.",                       action: "integration", tags: ["integration","mailchimp","email"], isPremium: false },
  { id: "int-hubspot",          name: "HubSpot CRM Sync",           category: "Integrations",icon: "🧩", description: "Sincroniza clientes y deals con HubSpot CRM.",                                  action: "integration", tags: ["integration","hubspot","crm"],    isPremium: true  },
  { id: "int-salesforce",       name: "Salesforce Connector",       category: "Integrations",icon: "☁️", description: "Integra datos de ecommerce con Salesforce CRM.",                               action: "integration", tags: ["integration","salesforce","crm"],  isPremium: true  },
  { id: "int-stripe",           name: "Stripe Payments",            category: "Integrations",icon: "💳", description: "Stripe checkout, subscriptions y webhooks de pago.",                            action: "integration", tags: ["integration","stripe","payments"], isPremium: false },
  { id: "int-paypal",           name: "PayPal Integration",         category: "Integrations",icon: "💰", description: "PayPal checkout y buttons para páginas de pago.",                               action: "integration", tags: ["integration","paypal","payments"], isPremium: false },
  { id: "int-zapier",           name: "Zapier Connect",             category: "Integrations",icon: "⚡", description: "Conector Zapier para automatizar con 5000+ apps.",                              action: "integration", tags: ["integration","zapier","automation"],isPremium: false },
  { id: "int-make",             name: "Make.com Connector",         category: "Integrations",icon: "🔧", description: "Integración Make.com para flujos visuales complejos.",                          action: "integration", tags: ["integration","make","automation"], isPremium: false },
  { id: "int-woocommerce",      name: "WooCommerce Connector",      category: "Integrations",icon: "🛒", description: "Sincroniza datos de WooCommerce con la plataforma.",                            action: "integration", tags: ["integration","woocommerce","ecommerce"],isPremium: false },
  { id: "int-amazon",           name: "Amazon FBA Integration",     category: "Integrations",icon: "📦", description: "Sincroniza listings y métricas de Amazon FBA.",                                  action: "integration", tags: ["integration","amazon","fba"],     isPremium: true  },
  { id: "int-google-ads",       name: "Google Ads Integration",     category: "Integrations",icon: "📢", description: "Importa conversiones y audiencias a Google Ads.",                               action: "integration", tags: ["integration","google","ads"],     isPremium: false },
  { id: "int-pinterest-catalog",name: "Pinterest Product Catalog",  category: "Integrations",icon: "📌", description: "Feed de productos para Pinterest Shopping.",                                    action: "integration", tags: ["integration","pinterest","catalog"],isPremium: false },
  { id: "int-instagram-shop",   name: "Instagram Shopping",         category: "Integrations",icon: "📸", description: "Conecta catálogo para Instagram Shopping y stories.",                           action: "integration", tags: ["integration","instagram","shopping"],isPremium: false },
  { id: "int-google-sheets",    name: "Google Sheets Export",       category: "Integrations",icon: "📊", description: "Exporta datos automáticamente a Google Sheets.",                                action: "integration", tags: ["integration","sheets","export"],  isPremium: false },
  { id: "int-airtable",         name: "Airtable Connector",         category: "Integrations",icon: "🗃️", description: "Sincroniza datos con bases Airtable para operaciones.",                        action: "integration", tags: ["integration","airtable","database"],isPremium: false },
  { id: "int-notion",           name: "Notion Database Sync",       category: "Integrations",icon: "📒", description: "Sincroniza pedidos, clientes o KPIs a Notion databases.",                       action: "integration", tags: ["integration","notion","database"], isPremium: false },
  { id: "int-slack",            name: "Slack Notifications",        category: "Integrations",icon: "💬", description: "Canal Slack dedicado para alertas de negocio en tiempo real.",                  action: "integration", tags: ["integration","slack","alerts"],   isPremium: false },
  { id: "int-twilio",           name: "Twilio SMS/WhatsApp",        category: "Integrations",icon: "📱", description: "SMS y WhatsApp Business para notificaciones y soporte.",                        action: "integration", tags: ["integration","twilio","sms"],     isPremium: false },
  { id: "int-intercom",         name: "Intercom Live Chat",         category: "Integrations",icon: "💬", description: "Chat en vivo y automatizaciones de conversación.",                              action: "integration", tags: ["integration","intercom","chat"],  isPremium: false },

  // ── MOBILE (15) ───────────────────────────────────────────────────────────
  { id: "mobile-pwa-builder",   name: "PWA Builder",                category: "Mobile",     icon: "📱", description: "Genera manifest.json y service worker para PWA.",                                action: "generator",   tags: ["mobile","pwa","offline"],        isPremium: false },
  { id: "mobile-app-icon",      name: "App Icon Generator",         category: "Mobile",     icon: "🎨", description: "Genera iconos de app en todos los tamaños (iOS/Android).",                       action: "generator",   tags: ["mobile","icon","app"],           isPremium: false },
  { id: "mobile-splash",        name: "Splash Screen Builder",      category: "Mobile",     icon: "🚀", description: "Splash screen animada para PWA y apps nativas.",                                action: "generator",   tags: ["mobile","splash","loading"],     isPremium: false },
  { id: "mobile-push-permission",name: "Push Permission Flow",      category: "Mobile",     icon: "🔔", description: "Flujo de solicitud de permisos push con alta tasa de aceptación.",               action: "generator",   tags: ["mobile","push","permission"],    isPremium: false },
  { id: "mobile-offline",       name: "Offline Mode Handler",       category: "Mobile",     icon: "✈️", description: "Implementa modo offline con cache strategy y UI feedback.",                      action: "generator",   tags: ["mobile","offline","pwa"],        isPremium: false },
  { id: "mobile-bottom-nav",    name: "Bottom Navigation Builder",  category: "Mobile",     icon: "⬇️", description: "Barra de navegación inferior mobile con tabs y badges.",                        action: "generator",   tags: ["mobile","navigation","ui"],      isPremium: false },
  { id: "mobile-swipe-gestures",name: "Swipe Gesture Handler",      category: "Mobile",     icon: "👆", description: "Implementa swipe gestures para carruseles y navegación.",                       action: "generator",   tags: ["mobile","gestures","touch"],     isPremium: false },
  { id: "mobile-bottom-sheet",  name: "Bottom Sheet Component",     category: "Mobile",     icon: "📋", description: "Bottom sheet modal para mobile con drag y snap points.",                         action: "generator",   tags: ["mobile","sheet","component"],    isPremium: false },
  { id: "mobile-pull-refresh",  name: "Pull-to-Refresh Component",  category: "Mobile",     icon: "🔄", description: "Pull-to-refresh nativo para feeds y listas.",                                   action: "generator",   tags: ["mobile","refresh","ux"],         isPremium: false },
  { id: "mobile-app-store",     name: "App Store Preview Writer",   category: "Mobile",     icon: "🏪", description: "Copy y assets para App Store y Google Play Listing.",                           action: "prompt",      tags: ["mobile","app-store","aso"],      isPremium: false },
  { id: "mobile-deep-link",     name: "Deep Link Manager",          category: "Mobile",     icon: "🔗", description: "Configura universal links e intent filters para deep linking.",                  action: "generator",   tags: ["mobile","deep-link","routing"],  isPremium: true  },
  { id: "mobile-native-share",  name: "Native Share Button",        category: "Mobile",     icon: "📤", description: "Botón de compartir nativo con Web Share API.",                                  action: "generator",   tags: ["mobile","share","native"],       isPremium: false },
  { id: "mobile-fab",           name: "Floating Action Button",     category: "Mobile",     icon: "➕", description: "FAB material con menú expandible y acciones rápidas.",                           action: "generator",   tags: ["mobile","fab","button"],         isPremium: false },
  { id: "mobile-haptic",        name: "Haptic Feedback Handler",    category: "Mobile",     icon: "📳", description: "Implementa feedback haptic via Vibration API en acciones.",                     action: "generator",   tags: ["mobile","haptic","feedback"],    isPremium: false },
  { id: "mobile-responsive",    name: "Mobile-First CSS Converter",  category: "Mobile",     icon: "📱", description: "Convierte CSS desktop-first a mobile-first con breakpoints.",                   action: "transform",   tags: ["mobile","responsive","css"],     isPremium: false },

  // ── PRODUCTIVITY (10) ─────────────────────────────────────────────────────
  { id: "prod-task-manager",    name: "Task Manager Template",       category: "Productivity",icon: "✅", description: "Template HTML interactivo de gestión de tareas con Kanban.",                    action: "generator",   tags: ["productivity","tasks","kanban"],  isPremium: false },
  { id: "prod-calendar",        name: "Calendar View Builder",       category: "Productivity",icon: "📅", description: "Vista de calendario HTML con eventos y código de colores.",                    action: "generator",   tags: ["productivity","calendar","ui"],   isPremium: false },
  { id: "prod-time-tracker",    name: "Time Tracker Component",      category: "Productivity",icon: "⏱️", description: "Componente de tracking de tiempo por proyecto y cliente.",                    action: "generator",   tags: ["productivity","time","tracker"],  isPremium: false },
  { id: "prod-note-taker",      name: "Note-Taking App Builder",     category: "Productivity",icon: "📝", description: "App de notas HTML con markdown, tags y búsqueda.",                             action: "generator",   tags: ["productivity","notes","app"],     isPremium: false },
  { id: "prod-invoice-maker",   name: "Invoice Generator",           category: "Productivity",icon: "🧾", description: "Generador de facturas HTML con exportación PDF.",                              action: "generator",   tags: ["productivity","invoice","pdf"],   isPremium: false },
  { id: "prod-contract-builder",name: "Contract Template Builder",   category: "Productivity",icon: "📄", description: "Template de contrato de servicios en HTML editable.",                         action: "generator",   tags: ["productivity","contract","legal"],isPremium: true  },
  { id: "prod-meeting-scheduler",name: "Meeting Agenda Builder",     category: "Productivity",icon: "🗓️", description: "Agenda de reunión estructurada con time boxes y acción items.",                action: "generator",   tags: ["productivity","meeting","agenda"],isPremium: false },
  { id: "prod-doc-generator",   name: "Document Generator",         category: "Productivity",icon: "📋", description: "Genera documentos estructurados: PRD, BRD, SOW, RFC.",                        action: "prompt",      tags: ["productivity","document","business"],isPremium: false },
  { id: "prod-okr-builder",     name: "OKR Framework Builder",      category: "Productivity",icon: "🎯", description: "Define Objectives & Key Results con tracking de progreso.",                    action: "prompt",      tags: ["productivity","okr","goals"],     isPremium: false },
  { id: "prod-standup-bot",     name: "Standup Report Generator",   category: "Productivity",icon: "🤝", description: "Template de standup diario con yesterday/today/blockers.",                     action: "generator",   tags: ["productivity","standup","agile"], isPremium: false },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getPluginById(id: string): Plugin | undefined {
  return PLUGINS_CATALOG.find(p => p.id === id);
}

export function getPluginsByCategory(category: string): Plugin[] {
  return PLUGINS_CATALOG.filter(p => p.category === category);
}

export function searchPlugins(query: string): Plugin[] {
  const q = query.toLowerCase();
  return PLUGINS_CATALOG.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    p.tags.some(t => t.includes(q))
  );
}

export const PLUGIN_CATEGORIES = [
  ...new Set(PLUGINS_CATALOG.map(p => p.category))
].map(cat => ({
  id: cat,
  label: cat,
  count: getPluginsByCategory(cat).length,
}));

export function getNewPlugins(): Plugin[] {
  return PLUGINS_CATALOG.filter(p => p.isNew);
}

export function getPopularPlugins(limit = 20): Plugin[] {
  return [...PLUGINS_CATALOG]
    .sort((a, b) => (b.usageCount ?? 0) - (a.usageCount ?? 0))
    .slice(0, limit);
}
