import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import projectsRouter from "./projects.js";
import productsRouter from "./products.js";
import redesignRouter from "./redesign.js";
import imagesRouter from "./images.js";
import pricingRouter from "./pricing.js";
import seoRouter from "./seo.js";
import abTestingRouter from "./ab-testing.js";
import jobsRouter from "./jobs.js";
import consistencyRouter from "./consistency.js";
import authRouter from "./auth.js";
import adminRouter from "./admin.js";
import clientRouter from "./client.js";
import cmsRouter from "./cms.js";
import intelligenceRouter from "./intelligence.js";
import inventoryRouter from "./inventory.js";
import onboardingRouter from "./onboarding.js";
import competitorsRouter from "./competitors.js";
import emailsRouter from "./emails.js";
import emailTemplatesRouter from "./email-templates.js";
import storeRouter from "./store.js";
import voiceRouter from "./voice.js";
import pushRouter from "./push.js";
import shopybrainRouter from "./shopybrain.js";
import agencyRouter from "./agency.js";
import klaviyoRouter from "./klaviyo.js";
import vaultRouter from "./vault.js";
import referenceRouter from "./reference.js";
import geminiResearchRouter from "./gemini-research.js";
import klaviyoAiRouter from "./klaviyo-ai.js";
import absorberRouter from "./absorber.js";
import entityResearchRouter from "./entity-research.js";
import contactRouter from "./contact.js";
import apkRouter from "./apk.js";
import plansRouter from "./plans.js";
import exportsRouter from "./exports.js";
import scripttagRouter from "./scripttag.js";
import automationsRouter from "./automations.js";
import brainSyncRouter from "./brain-sync.js";
import { requireAdmin } from "../lib/auth.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/admin", adminRouter);
router.use("/client", clientRouter);
router.use("/cms", (req, res, next) => {
  if (req.method === "GET" && req.path === "/content") return next();
  return requireAdmin(req, res, next);
}, cmsRouter);
router.use(storeRouter);
router.use(contactRouter);
router.use(apkRouter);

router.use(requireAdmin);
router.use(projectsRouter);
router.use(productsRouter);
router.use(redesignRouter);
router.use(imagesRouter);
router.use(pricingRouter);
router.use(seoRouter);
router.use(abTestingRouter);
router.use(jobsRouter);
router.use(consistencyRouter);
router.use(intelligenceRouter);
router.use(inventoryRouter);
router.use(onboardingRouter);
router.use(competitorsRouter);
router.use(emailsRouter);
router.use(emailTemplatesRouter);
router.use(voiceRouter);
router.use(pushRouter);
router.use(shopybrainRouter);
router.use(agencyRouter);
router.use(klaviyoRouter);
router.use(vaultRouter);
router.use(referenceRouter);
router.use("/gemini", geminiResearchRouter);
router.use(klaviyoAiRouter);
router.use(absorberRouter);
router.use(entityResearchRouter);
router.use(plansRouter);
router.use(exportsRouter);
router.use(scripttagRouter);
router.use(automationsRouter);
router.use(brainSyncRouter);

export default router;
