/**
 * Proyectos reales del equipo con los que arranca (y se actualiza) el portfolio de la landing.
 *
 * Los textos describen lo que cada proyecto HACE, sacado de su propio código y documentación:
 * sin cifras de resultados ni clientes inventados. Las imágenes son capturas reales, servidas
 * como estáticos de la web (public/portfolio/*.webp); las que se suban desde el panel van aparte.
 *
 * SEED_VERSION sube cuando cambia esta lista. Al arrancar, portfolio.ts aplica la versión nueva
 * UNA vez: añade los proyectos que falten y actualiza los que siguen con el texto genérico de la
 * versión anterior. Lo que se haya editado desde Admin → Portfolio no se toca.
 */
export const SEED_VERSION = 2;

export interface SeedImage { url: string; alt: string; w?: number; h?: number }
export interface SeedProject {
  slug: string; title: string; client: string | null; category: string; status: string;
  summary: string; description: string; features: string[]; tech: string[];
  liveUrl: string | null; appUrl: string | null; images: SeedImage[]; sortOrder: number;
}

export const SEED: SeedProject[] = [
  {"slug": "brasas-y-paellas", "title": "Brasa y Paellas · sistema integral del restaurante", "client": "Brasa y Paellas", "category": "Sistemas a medida", "status": "En producción", "summary": "Todo el restaurante en un solo sistema: carta digital por QR con IA, TPV de sala, pantalla de cocina, panel de gestión y facturación preparada para VeriFactu.", "description": "El restaurante trabajaba con papel, una caja y varias herramientas sueltas. Construimos un único sistema que une sala, cocina, carta y gestión, instalado en el ordenador del local.\n\nEl cliente escanea el QR de su mesa, ve la carta en su idioma y pide. El pedido llega a la sala y a la cocina en el momento, y la cuenta sale del mismo sitio. Funciona aunque se caiga internet y está pensado para replicarse en otros locales.", "features": ["Carta digital por QR con camarero de IA que recomienda y resuelve dudas", "TPV de sala con mesas, cuentas y cobro", "Pantalla de cocina (KDS) con los pedidos en tiempo real", "Panel de gestión: carta, precios, fotos, fichajes del equipo", "Facturación preparada para VeriFactu (AEAT)", "Funciona sin internet y se instala en el ordenador del local"], "tech": ["Python", "JavaScript", "IA conversacional", "VeriFactu", "Tiempo real", "Offline-first"], "images": [{"url": "/portfolio/brasas-y-paellas-1.webp", "alt": "Sistema completo de Brasa y Paellas", "w": 1600, "h": 1605}, {"url": "/portfolio/brasas-y-paellas-2.webp", "alt": "TPV de sala", "w": 1600, "h": 1012}, {"url": "/portfolio/brasas-y-paellas-3.webp", "alt": "Pantalla de cocina", "w": 1600, "h": 937}, {"url": "/portfolio/brasas-y-paellas-4.webp", "alt": "Camarero con IA en la carta", "w": 860, "h": 1800}], "sortOrder": 0, "liveUrl": null, "appUrl": null},
  {"slug": "smart-menu-qr", "title": "Smart Menús interactivos con QR dinámicos", "client": "Hostelería", "category": "Sistemas a medida", "status": "En producción", "summary": "La carta deja de ser un PDF: una carta interactiva en 16 idiomas, con alérgenos, fotos y pedido desde la mesa, detrás de un QR que se puede cambiar sin reimprimir.", "description": "Una carta que vende. El cliente la abre con el QR de su mesa, sin instalar nada, en su idioma y con la moneda que elija. Filtra por alérgenos o dieta, ve la información nutricional de cada plato y puede pedir desde el móvil.\n\nLos QR son dinámicos: si cambia la carta, la web o la promoción, se cambia el destino desde el panel y el papel impreso sigue valiendo. Además cuentan cuántas veces se escanea cada uno.", "features": ["16 idiomas y cambio de divisa", "Los 14 alérgenos de la UE y filtros de dieta automáticos", "Información nutricional por plato", "Pedido desde la mesa, directo a sala y cocina", "QR por mesa que se reapuntan sin reimprimir", "Estadísticas de escaneos por QR, día y hora", "Seis temas visuales adaptados a la marca del local"], "tech": ["JavaScript", "QR dinámicos", "Cloudflare Workers", "i18n", "IA"], "images": [{"url": "/portfolio/smart-menu-qr-1.webp", "alt": "Smart Menú en el móvil del cliente", "w": 860, "h": 1800}], "sortOrder": 1, "liveUrl": null, "appUrl": null},
  {"slug": "crafter-eventos", "title": "Crafter Eventos · galería de fotos por QR", "client": "Producto propio", "category": "Webs y apps", "status": "En producción", "summary": "Los invitados escanean el QR de la mesa y suben sus fotos y vídeos sin instalar nada. La organizadora lo ve en directo y entrega todo en calidad original.", "description": "Un producto completo para bodas y eventos, de la idea al cobro. El invitado entra desde el QR, sube sus fotos y listo. La organizadora tiene un panel con el muro en directo, favoritas, álbumes y descarga de todo en un ZIP sin recomprimir. Los novios reciben un enlace privado.\n\nIncluye planes y pago con tarjeta, usuarios por evento y una administración desde la que se da de alta a cada organizadora y se lleva su cuenta por separado.", "features": ["Subida desde el QR, sin app ni registro para el invitado", "Muro en directo con favoritas, álbumes y fotos ocultas", "Descarga en ZIP con los archivos originales, sin recomprimir", "Enlace privado para los novios y usuarios con contraseña por evento", "Planes y cobro con tarjeta (Stripe)", "Administración de organizadoras, cada una con sus eventos", "App Android y tarjeta de mesa lista para imprimir"], "tech": ["TypeScript", "Cloudflare Workers", "D1", "R2", "Stripe", "PWA", "Android"], "liveUrl": "https://crafter-eventos.crafteragency.workers.dev/panel", "images": [{"url": "/portfolio/crafter-eventos-1.webp", "alt": "Muro en directo de la organizadora", "w": 780, "h": 1688}, {"url": "/portfolio/crafter-eventos-2.webp", "alt": "Lo que ve el invitado al escanear el QR", "w": 780, "h": 1688}, {"url": "/portfolio/crafter-eventos-3.webp", "alt": "QR de subida del evento", "w": 780, "h": 1688}, {"url": "/portfolio/crafter-eventos-4.webp", "alt": "Galería privada de los novios", "w": 780, "h": 1688}, {"url": "/portfolio/crafter-eventos-5.webp", "alt": "Tarjeta de mesa lista para imprimir", "w": 796, "h": 1120}], "sortOrder": 2, "appUrl": null},
  {"slug": "warriors-hardcore", "title": "Warriors Hardcore · web de lanzamiento", "client": "Warriors Hardcore", "category": "Webs y apps", "status": "Entregado", "summary": "Web de lanzamiento de una línea de suplementación deportiva, en cuatro idiomas, con el producto girando en 3D y una versión cinematográfica guiada por el scroll.", "description": "La marca necesitaba presentar su línea con la fuerza de su imagen. Diseñamos y construimos la web de lanzamiento en español, inglés, alemán e italiano, con cada producto mostrado con su foto oficial y una versión con el bote en 3D real.\n\nPreparamos además una versión inmersiva en la que el visitante recorre un mundo 3D al hacer scroll, los QR para imprenta y el material gráfico de la campaña.", "features": ["Cuatro idiomas: español, inglés, alemán e italiano", "Producto en 3D real que gira en pantalla", "Versión cinematográfica: un mundo 3D recorrido con el scroll", "Versión ligera que funciona sin conexión", "QR para imprenta y material de campaña", "Adaptada a móvil, tablet y escritorio"], "tech": ["HTML", "CSS", "JavaScript", "Three.js", "WebGL", "Cloudflare Workers"], "images": [{"url": "/portfolio/warriors-hardcore-1.webp", "alt": "Portada de la web de Warriors Hardcore", "w": 1440, "h": 830}, {"url": "/portfolio/warriors-hardcore-2.webp", "alt": "Bote en 3D girando en la web", "w": 1440, "h": 830}, {"url": "/portfolio/warriors-hardcore-3.webp", "alt": "Escenas de producto de la web", "w": 1440, "h": 830}, {"url": "/portfolio/warriors-hardcore-4.webp", "alt": "La web en el móvil", "w": 390, "h": 788}], "sortOrder": 3, "liveUrl": null, "appUrl": null},
  {"slug": "warriors-instagram", "title": "Warriors Insta · app de contenido para Instagram", "client": "Warriors Hardcore", "category": "Apps con IA", "status": "Entregado", "summary": "Una app Android para crear, aprobar, programar y publicar en Instagram, con un asistente de IA que redacta, monta carruseles y dirige vídeos.", "description": "El trabajo de redes de la marca en una sola app. Desde el móvil se crean publicaciones de producto, carruseles y reels; pasan por una cola de aprobación y se publican solas a su hora. Nada sale sin el visto bueno de quien decide.\n\nIncluye un asistente con el que se trabaja en lenguaje natural («crea un post de la creatina con este gancho»), un estudio de vídeo con IA, el perfil real de la cuenta y sus métricas.", "features": ["Crear posts, carruseles y reels desde el móvil", "Cola con aprobación: borrador, aprobado, programado, publicado", "Publicación automática a la hora programada", "Asistente de IA con 30 herramientas reales de trabajo", "Estudio de vídeo: guion, planos y revisión con IA", "Perfil y métricas reales de la cuenta"], "tech": ["Flutter", "Android", "Python", "Instagram API", "IA generativa", "Cloudflare Workers"], "images": [{"url": "/portfolio/warriors-instagram-1.webp", "alt": "App de Instagram: crear, cola y métricas", "w": 1600, "h": 844}, {"url": "/portfolio/warriors-instagram-2.webp", "alt": "Asistente y estudio de vídeo dentro de la app", "w": 800, "h": 844}], "sortOrder": 4, "liveUrl": null, "appUrl": null},
  {"slug": "lph-app", "title": "LPH · app de redes en piloto automático", "client": "LimpiezaPorHora", "category": "Apps con IA", "status": "En producción", "summary": "La app con la que una empresa de servicios lleva sus redes: planifica el mes entero, genera cada publicación con IA y responde a comentarios y mensajes.", "description": "LimpiezaPorHora quería presencia constante en redes sin dedicarle horas. Construimos su app Android y el motor que hay detrás: conoce la marca, propone el calendario del mes, genera imágenes, vídeos y textos, y publica.\n\nTambién atiende: responde a comentarios y mensajes de Instagram. Es el motor del que después nacieron las apps de redes de otros clientes.", "features": ["Piloto automático: planifica el mes y genera cada publicación", "Estudio de contenido: imagen, vídeo, carruseles e infografías", "Respuestas automáticas a comentarios y mensajes", "ADN de marca que guía todo lo que se genera", "Varios motores de IA, elegibles en caliente", "App Android que se conecta sola al servidor"], "tech": ["Flutter", "Android", "Python", "Meta API", "IA generativa", "Cloudflare"], "images": [], "sortOrder": 5, "liveUrl": null, "appUrl": null},
  {"slug": "redes-del-grupo", "title": "Redes del Grupo · una app para todos los locales", "client": "Brasa y Paellas · Bar Alexanca", "category": "Apps con IA", "status": "En desarrollo", "summary": "Lo siguiente que estamos construyendo: una app para crear, aprobar, programar y publicar en Instagram, Facebook, TikTok y Google Business de cada local del grupo.", "description": "Un grupo de hostelería con varios locales y cuatro redes por local. La app reúne todo: arriba se elige el local y la app entera cambia a su marca. La IA conoce la carta y el horario de cada uno, así que propone ideas y redacta con datos reales.\n\nEl dueño lo aprueba todo; el equipo solo prepara borradores. El servidor está siempre encendido en la nube y publica a su hora, aunque el móvil esté apagado.", "features": ["Instagram, Facebook, TikTok y Google Business desde una sola app", "Varios locales, cada uno con su marca y sus cuentas", "IA que conoce la carta y el horario de cada local", "Roles: el dueño aprueba, el equipo prepara borradores", "Publicación programada desde la nube, siempre encendida", "Permisos de las redes guardados cifrados"], "tech": ["Flutter", "Android", "TypeScript", "Cloudflare Workers", "D1", "R2", "IA generativa"], "images": [{"url": "/portfolio/redes-del-grupo-2.webp", "alt": "Crear una publicación", "w": 1080, "h": 2200}, {"url": "/portfolio/redes-del-grupo-3.webp", "alt": "Planificador", "w": 1080, "h": 2200}, {"url": "/portfolio/redes-del-grupo-4.webp", "alt": "Perfil de Instagram del local", "w": 1080, "h": 2200}, {"url": "/portfolio/redes-del-grupo-5.webp", "alt": "La misma app con la marca del segundo local", "w": 1080, "h": 2200}], "sortOrder": 6, "liveUrl": null, "appUrl": null},
  {"slug": "agente-j-bond", "title": "Agente J.Bond · plataforma de agentes de IA", "client": "Plataforma propia", "category": "Plataformas e IA", "status": "En producción", "summary": "La plataforma con la que trabajamos: equipos de agentes de IA especializados que analizan el problema de un negocio y construyen la solución completa.", "description": "Nuestra herramienta de trabajo diaria, diseñada y construida por nosotros. Reúne equipos de agentes especializados (frontend, backend, datos, calidad, fiscal, marca) que trabajan juntos sobre un mismo proyecto, con varios motores de IA y memoria compartida.\n\nDesde la misma plataforma se gestionan los proyectos y archivos de cada cliente, los chatbots y asistentes telefónicos, el estudio de QR y la administración de nuestros productos.", "features": ["Equipos de agentes especializados que trabajan en paralelo", "Varios motores de IA: Claude, Gemini y ChatGPT", "Proyectos, archivos y memoria por cliente", "Chatbots de WhatsApp y asistentes telefónicos", "Estudio de QR y NFC integrado", "Acceso desde el móvil con su propia app"], "tech": ["Python", "JavaScript", "Agentes IA", "MCP", "Cloudflare", "Android"], "images": [{"url": "/portfolio/agente-j-bond-1.webp", "alt": "Equipo de agentes de la plataforma", "w": 1600, "h": 1000}, {"url": "/portfolio/agente-j-bond-2.webp", "alt": "Estudio de QR dentro de la plataforma", "w": 1600, "h": 982}], "sortOrder": 7, "liveUrl": null, "appUrl": null},
  {"slug": "qr-artisticos-3d", "title": "QR artísticos y en 3D", "client": "Varias marcas", "category": "Diseño 3D", "status": "En producción", "summary": "Códigos QR que son una pieza de marca: con arte, dentro del dibujo del cliente o como una escena en 3D que se resuelve en el código. Y todos se leen.", "description": "Un QR puede ser lo más feo de un cartel o lo que haga que alguien se pare. Diseñamos QR con la imagen de la marca, con arte generado alrededor del código o como escenas en 3D: un árbol, una ciudad o un paisaje que, al tocarlo, se ordena y se convierte en el código.\n\nCada pieza se comprueba con lectores reales, a varios tamaños y en impresión simulada, antes de entregarla. Si no se lee, no sale.", "features": ["QR con arte generado alrededor del código", "QR dentro del dibujo o la foto del cliente, sin deformarla", "Escenas en 3D: árbol, ciudad, relieve de un logo o paisaje", "Vídeo de la transformación en vertical y horizontal", "Dinámicos: cambian de destino sin reimprimir y cuentan escaneos", "Lectura verificada con lectores reales antes de entregar"], "tech": ["Three.js", "WebGL", "IA generativa", "Python", "Cloudflare Workers"], "images": [{"url": "/portfolio/qr-artisticos-3d-1.webp", "alt": "QR en 3D: el árbol", "w": 1121, "h": 1122}, {"url": "/portfolio/qr-artisticos-3d-2.webp", "alt": "El mismo árbol resuelto en código escaneable", "w": 1121, "h": 1122}, {"url": "/portfolio/qr-artisticos-3d-3.webp", "alt": "QR en 3D: paisaje en relieve", "w": 1121, "h": 1122}, {"url": "/portfolio/qr-artisticos-3d-4.webp", "alt": "Pino de otoño", "w": 1121, "h": 1122}, {"url": "/portfolio/qr-artisticos-3d-5.webp", "alt": "QR en 3D: la ciudad", "w": 1121, "h": 1122}], "sortOrder": 8, "liveUrl": null, "appUrl": null},
  {"slug": "bots-trading", "title": "Terminal y bots de trading", "client": "Desarrollo propio", "category": "Plataformas e IA", "status": "En producción", "summary": "Un terminal con mercados en vivo, laboratorio para probar estrategias con datos reales y ejecución automática dentro de los límites que fija su dueño.", "description": "Un sistema para investigar y automatizar estrategias con cabeza. El laboratorio prueba cada idea con datos históricos reales y la juzga con datos que no ha visto. Lo que no supera la prueba no llega a operar.\n\nLa ejecución real exige dos llaves del dueño y respeta sus límites de importe y de riesgo. Es una herramienta de trabajo, no una promesa de resultados ni un consejo de inversión.", "features": ["Mercados en vivo y gráficos en un solo panel", "Laboratorio de estrategias con datos históricos reales", "Validación con datos no vistos antes de operar", "Cartera de papel para probar sin arriesgar", "Ejecución real con doble llave y límites del dueño", "Registro de cada decisión y cada orden"], "tech": ["Python", "APIs de mercado", "Backtesting", "Automatización", "Agentes IA"], "images": [{"url": "/portfolio/bots-trading-1.webp", "alt": "Terminal de trading de la plataforma", "w": 1600, "h": 1000}], "sortOrder": 9, "liveUrl": null, "appUrl": null},
  {"slug": "rastalo-tpv", "title": "RastaLo TPV", "client": "RastaLo", "category": "Sistemas a medida", "status": "En producción", "summary": "Terminal punto de venta desarrollado a medida para el negocio, con un asistente de voz integrado.", "description": "Un TPV hecho a la medida de cómo trabaja el negocio, en lugar de adaptar el negocio a un programa genérico. Incluye un asistente de voz para consultar y operar sin soltar lo que se tiene entre manos.", "features": ["TPV adaptado al flujo real del negocio", "Asistente de voz integrado", "Instalación y soporte directos"], "tech": ["TPV", "Asistente de voz", "Python", "JavaScript"], "images": [], "sortOrder": 10, "liveUrl": null, "appUrl": null},
  {"slug": "pequenos-genios", "title": "Pequeños Genios", "client": "Producto propio", "category": "Webs y apps", "status": "Publicada", "summary": "35 minijuegos educativos para niños de 4 a 12 años.", "description": "Juegos de matemáticas, lengua, ciencias, historia, tecnología y destreza con dificultad adaptada a la edad, progreso guardado en el dispositivo y modo sin cuenta. App Android con Capacitor.", "features": ["35 minijuegos de seis áreas", "Dificultad adaptada a la edad", "Progreso guardado en el dispositivo", "Se puede jugar sin crear cuenta"], "tech": ["React", "Capacitor", "Android"], "images": [], "sortOrder": 11, "liveUrl": null, "appUrl": null},
];

/** Las descripciones genéricas de la versión 1: una fila que aún las tiene no ha sido editada a mano. */
export const GENERIC_V1: Record<string, string> = {
  "warriors-hardcore": "Diseño y desarrollo de la landing de la marca y de su aplicación.",
  "crafter-eventos": "Proyecto completo para Crafter Eventos.",
  "brasas-y-paellas": "Sistema completo para un negocio de brasas y paellas: asistente conversacional para atender a los clientes, registro y una aplicación con CRM para gestionarlos.",
  "rastalo-tpv": "Terminal punto de venta desarrollado a medida.",
  "agente-j-bond": "Plataforma del agente J-Bond con interfaz y flujos diseñados a medida.",
  "bots-trading": "Desarrollo de bots que ejecutan estrategias de trading de forma automática.",
  "qr-artisticos-3d": "Diseño de códigos QR artísticos y en 3D para marcas.",
  "pequenos-genios": "Juegos de matemáticas, lengua, ciencias, historia, tecnología y destreza con dificultad adaptada a la edad, progreso guardado en el dispositivo y modo sin cuenta. App Android con Capacitor.",
};
