// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cover-pages/Classic.tsx": () => import("../components/mockups/cover-pages/Classic.tsx"),
  "./components/mockups/cover-pages/Elegance.tsx": () => import("../components/mockups/cover-pages/Elegance.tsx"),
  "./components/mockups/cover-pages/Prestige.tsx": () => import("../components/mockups/cover-pages/Prestige.tsx")
};
