import {
  pgTable,
  text,
  serial,
  timestamp,
  boolean,
  integer,
  varchar,
  jsonb,
} from "drizzle-orm/pg-core";
import { projectsTable } from "./projects";

export const emailTemplates = pgTable("email_templates", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projectsTable.id),
  name: varchar("name", { length: 255 }).notNull(),
  templateType: varchar("template_type", { length: 100 }).notNull(),
  category: varchar("category", { length: 50 }).notNull().default("agency"),
  subjectA: text("subject_a"),
  subjectB: text("subject_b"),
  previewText: text("preview_text"),
  htmlContent: text("html_content"),
  textContent: text("text_content"),
  tone: varchar("tone", { length: 50 }).default("profesional"),
  language: varchar("language", { length: 10 }).default("es"),
  brandName: varchar("brand_name", { length: 255 }),
  brandLogoUrl: text("brand_logo_url"),
  brandColors: jsonb("brand_colors").default({}),
  brandTagline: text("brand_tagline"),
  variablesUsed: text("variables_used"),
  fromEmail: varchar("from_email", { length: 255 }),
  fromName: varchar("from_name", { length: 255 }),
  replyEmail: varchar("reply_email", { length: 255 }),
  klaviyoTemplateId: varchar("klaviyo_template_id", { length: 100 }),
  klaviyoStatus: varchar("klaviyo_status", { length: 20 }).default("draft"),
  klaviyoError: text("klaviyo_error"),
  pushedAt: timestamp("pushed_at", { withTimezone: true }),
  isFavorite: boolean("is_favorite").default(false),
  version: integer("version").default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
