import {
  pgTable,
  text,
  serial,
  timestamp,
  integer,
  varchar,
  real,
} from "drizzle-orm/pg-core";
import { projectsTable } from "./projects";

export const emailFlows = pgTable("email_flows", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projectsTable.id),
  name: varchar("name", { length: 255 }).notNull(),
  flowType: varchar("flow_type", { length: 100 }),
  triggerType: varchar("trigger_type", { length: 100 }),
  sendDelay: varchar("send_delay", { length: 20 }).default("1h"),
  subjectA: text("subject_a"),
  subjectB: text("subject_b"),
  previewText: text("preview_text"),
  tone: varchar("tone", { length: 50 }).default("urgente"),
  language: varchar("language", { length: 10 }).default("es"),
  htmlContent: text("html_content"),
  textContent: text("text_content"),
  variablesUsed: text("variables_used"),
  fromEmail: varchar("from_email", { length: 255 }),
  fromName: varchar("from_name", { length: 255 }),
  replyEmail: varchar("reply_email", { length: 255 }),
  klaviyoTemplateId: varchar("klaviyo_template_id", { length: 100 }),
  klaviyoFlowId: varchar("klaviyo_flow_id", { length: 100 }),
  klaviyoStatus: varchar("klaviyo_status", { length: 20 }).default("draft"),
  klaviyoError: text("klaviyo_error"),
  openRate: real("open_rate"),
  clickRate: real("click_rate"),
  pushedAt: timestamp("pushed_at", { withTimezone: true }),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
