import { pgTable, text, real, integer, timestamp, jsonb } from "drizzle-orm/pg-core";

export const inventoryTrackingTable = pgTable("inventory_tracking", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  productId: text("product_id").notNull(),
  variantId: text("variant_id"),
  productTitle: text("product_title"),
  variantTitle: text("variant_title"),
  sku: text("sku"),
  barcode: text("barcode"),
  option1Name: text("option1_name"),
  option1Value: text("option1_value"),
  option2Name: text("option2_name"),
  option2Value: text("option2_value"),
  option3Name: text("option3_name"),
  option3Value: text("option3_value"),
  productType: text("product_type"),
  vendor: text("vendor"),
  costPerItem: real("cost_per_item"),
  price: real("price"),
  compareAtPrice: real("compare_at_price"),
  weight: real("weight"),
  weightUnit: text("weight_unit"),
  currentStock: integer("current_stock"),
  avgDailySales: real("avg_daily_sales"),
  totalUnitsSold: integer("total_units_sold").default(0),
  daysRemaining: integer("days_remaining"),
  restockThreshold: integer("restock_threshold").default(15),
  supplierEmail: text("supplier_email"),
  supplierLeadDays: integer("supplier_lead_days").default(14),
  lastRestockDate: text("last_restock_date"),
  inventoryPolicy: text("inventory_policy"),
  requiresShipping: integer("requires_shipping").default(1),
  status: text("status"),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const restockOrdersTable = pgTable("restock_orders", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  productId: text("product_id"),
  productTitle: text("product_title"),
  quantitySuggested: integer("quantity_suggested"),
  urgency: text("urgency"),
  emailDraft: text("email_draft"),
  sentAt: timestamp("sent_at"),
  adminApproved: integer("admin_approved").default(0),
  createdAt: timestamp("created_at").defaultNow(),
});

export const salesAnalyticsTable = pgTable("sales_analytics", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  orderId: text("order_id").notNull(),
  orderNumber: text("order_number"),
  orderDate: timestamp("order_date"),
  customerId: text("customer_id"),
  customerEmail: text("customer_email"),
  customerName: text("customer_name"),
  productId: text("product_id"),
  variantId: text("variant_id"),
  productTitle: text("product_title"),
  variantTitle: text("variant_title"),
  sku: text("sku"),
  option1Name: text("option1_name"),
  option1Value: text("option1_value"),
  option2Name: text("option2_name"),
  option2Value: text("option2_value"),
  option3Name: text("option3_name"),
  option3Value: text("option3_value"),
  quantity: integer("quantity").default(1),
  unitPrice: real("unit_price"),
  totalPrice: real("total_price"),
  discount: real("discount").default(0),
  currency: text("currency").default("EUR"),
  fulfillmentStatus: text("fulfillment_status"),
  financialStatus: text("financial_status"),
  country: text("country"),
  city: text("city"),
  createdAt: timestamp("created_at").defaultNow(),
});
