import { pgTable, text, real, integer, timestamp } from "drizzle-orm/pg-core";

export const omnicoreMemoriesTable = pgTable("omnicore_memories", {
  id: text("id").primaryKey(),
  memoryType: text("memory_type").notNull(),
  niche: text("niche"),
  subNiche: text("sub_niche"),
  productType: text("product_type"),
  market: text("market").default("es"),
  title: text("title").notNull(),
  content: text("content").notNull(),
  confidence: real("confidence").default(0.5),
  useCount: integer("use_count").default(0),
  successCount: integer("success_count").default(0),
  successRate: real("success_rate").default(0.0),
  sourceType: text("source_type").default("manual"),
  tags: text("tags"),
  isVerified: integer("is_verified").default(0),
  lastUsedAt: timestamp("last_used_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const omnicoreNicheProfilesTable = pgTable("omnicore_niche_profiles", {
  id: text("id").primaryKey(),
  niche: text("niche").unique().notNull(),
  subNiches: text("sub_niches"),
  avgPriceMin: real("avg_price_min"),
  avgPriceMax: real("avg_price_max"),
  avgPriceSweetSpot: real("avg_price_sweet_spot"),
  typicalMarginPct: real("typical_margin_pct"),
  seasonalPeaks: text("seasonal_peaks"),
  topKeywords: text("top_keywords"),
  topImageTypes: text("top_image_types"),
  bestCtaWords: text("best_cta_words"),
  toneDescription: text("tone_description"),
  knownCompetitors: text("known_competitors"),
  avgCompetitorCount: integer("avg_competitor_count"),
  marketSaturation: text("market_saturation").default("medium"),
  bestPromptStyle: text("best_prompt_style"),
  productDescriptionTemplate: text("product_description_template"),
  pricingPsychology: text("pricing_psychology"),
  storesAnalyzed: integer("stores_analyzed").default(0),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const omnicorePromptLibraryTable = pgTable("omnicore_prompt_library", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  niche: text("niche"),
  useCase: text("use_case"),
  promptTemplate: text("prompt_template").notNull(),
  variables: text("variables"),
  avgQualityScore: real("avg_quality_score").default(0),
  useCount: integer("use_count").default(0),
  createdBy: text("created_by").default("system"),
  isPublic: integer("is_public").default(1),
  createdAt: timestamp("created_at").defaultNow(),
});

export const omnicoreKnowledgeDomainsTable = pgTable("omnicore_knowledge_domains", {
  id: text("id").primaryKey(),
  domain: text("domain").unique().notNull(),
  knowledgeDepth: integer("knowledge_depth").default(0),
  verifiedInsights: integer("verified_insights").default(0),
  totalInsights: integer("total_insights").default(0),
  lastStudySession: timestamp("last_study_session"),
  specialtyPrompt: text("specialty_prompt"),
  corePrinciples: text("core_principles"),
  commonMistakes: text("common_mistakes"),
  bestPractices: text("best_practices"),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const omnicoreInsightsTable = pgTable("omnicore_insights", {
  id: text("id").primaryKey(),
  domain: text("domain").notNull(),
  subDomain: text("sub_domain"),
  insightType: text("insight_type").notNull(),
  title: text("title").notNull(),
  insight: text("insight").notNull(),
  evidence: text("evidence"),
  confidence: real("confidence").default(0.5),
  impactScore: real("impact_score").default(0.5),
  relatedDomains: text("related_domains"),
  relatedInsights: text("related_insights"),
  timesApplied: integer("times_applied").default(0),
  timesSuccessful: integer("times_successful").default(0),
  timesFailed: integer("times_failed").default(0),
  successRate: real("success_rate").default(0),
  source: text("source").default("manual"),
  retroactiveVersion: integer("retroactive_version").default(0),
  lastRetroactiveUpdate: timestamp("last_retroactive_update"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const omnicoreStudySessionsTable = pgTable("omnicore_study_sessions", {
  id: text("id").primaryKey(),
  sessionType: text("session_type").notNull(),
  domainsStudied: text("domains_studied"),
  trigger: text("trigger"),
  durationSeconds: integer("duration_seconds"),
  insightsCreated: integer("insights_created").default(0),
  insightsUpdated: integer("insights_updated").default(0),
  insightsInvalidated: integer("insights_invalidated").default(0),
  retroactiveUpdates: integer("retroactive_updates").default(0),
  summary: text("summary"),
  keyDiscoveries: text("key_discoveries"),
  tokensUsed: integer("tokens_used"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const omnicoreCrossConnectionsTable = pgTable("omnicore_cross_connections", {
  id: text("id").primaryKey(),
  insightA: text("insight_a").notNull(),
  insightB: text("insight_b").notNull(),
  connectionType: text("connection_type"),
  connectionStrength: real("connection_strength").default(0.5),
  discoveredAt: timestamp("discovered_at").defaultNow(),
});

export const agencyCostStructureTable = pgTable("agency_cost_structure", {
  id: text("id").primaryKey(),
  costClaudeApi: real("cost_claude_api").default(0),
  costReplicate: real("cost_replicate").default(0),
  costHosting: real("cost_hosting").default(0),
  costStripeFeesFixed: real("cost_stripe_fees_fixed").default(0),
  costDomainTools: real("cost_domain_tools").default(0),
  costYourTimeHourly: real("cost_your_time_hourly").default(80),
  avgHoursPerClient: real("avg_hours_per_client").default(4),
  costPerImageGenerated: real("cost_per_image_generated").default(0.25),
  costPerAuditRun: real("cost_per_audit_run").default(0.08),
  costPerBoostMasivo: real("cost_per_boost_masivo").default(2.50),
  costPerSeoUpdate: real("cost_per_seo_update").default(0.15),
  costPerAbTestSetup: real("cost_per_ab_test_setup").default(0.05),
  costPerReportPdf: real("cost_per_report_pdf").default(0.20),
  targetMarginSetup: real("target_margin_setup").default(0.70),
  targetMarginRetainer: real("target_margin_retainer").default(0.65),
  targetMarginExtras: real("target_margin_extras").default(0.75),
  minimumHourlyRate: real("minimum_hourly_rate").default(80),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const serviceCatalogTable = pgTable("service_catalog", {
  id: text("id").primaryKey(),
  serviceName: text("service_name").notNull(),
  serviceType: text("service_type"),
  costTimeHours: real("cost_time_hours").default(0),
  costPlatform: real("cost_platform").default(0),
  costTools: real("cost_tools").default(0),
  totalCost: real("total_cost").default(0),
  priceCurrent: real("price_current"),
  priceSuggested: real("price_suggested"),
  priceMin: real("price_min"),
  priceMax: real("price_max"),
  marketAvgPrice: real("market_avg_price"),
  marketPriceLow: real("market_price_low"),
  marketPriceHigh: real("market_price_high"),
  ourPositioning: text("our_positioning").default("premium"),
  timesSold: integer("times_sold").default(0),
  timesRejected: integer("times_rejected").default(0),
  avgClientSatisfaction: real("avg_client_satisfaction"),
  lastPriceReview: timestamp("last_price_review"),
  omnicoreRecommendation: text("omnicore_recommendation"),
  omnicoreConfidence: real("omnicore_confidence"),
  priceChangeSuggested: real("price_change_suggested"),
  isActive: integer("is_active").default(1),
  createdAt: timestamp("created_at").defaultNow(),
});

export const pricingDecisionsTable = pgTable("pricing_decisions", {
  id: text("id").primaryKey(),
  decisionType: text("decision_type"),
  entityId: text("entity_id"),
  entityName: text("entity_name"),
  oldPrice: real("old_price"),
  newPrice: real("new_price"),
  priceDelta: real("price_delta"),
  priceDeltaPct: real("price_delta_pct"),
  reasoning: text("reasoning"),
  dataUsed: text("data_used"),
  confidence: real("confidence"),
  riskLevel: text("risk_level").default("medium"),
  expectedImpact: text("expected_impact"),
  decisionMadeAt: timestamp("decision_made_at"),
  decisionBy: text("decision_by").default("omnicore_auto"),
  outcomeMeasuredAt: timestamp("outcome_measured_at"),
  actualRevenueChange: real("actual_revenue_change"),
  actualConversionChange: real("actual_conversion_change"),
  predictionAccuracy: real("prediction_accuracy"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const pricingRulesTable = pgTable("pricing_rules", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  ruleName: text("rule_name"),
  ruleType: text("rule_type"),
  conditionJson: text("condition_json"),
  actionJson: text("action_json"),
  limitsJson: text("limits_json"),
  isActive: integer("is_active").default(1),
  autoApply: integer("auto_apply").default(0),
  requiresApproval: integer("requires_approval").default(1),
  timesTriggered: integer("times_triggered").default(0),
  lastTriggered: timestamp("last_triggered"),
  createdAt: timestamp("created_at").defaultNow(),
});
